checkstyle.xml
Makes filtering by message work globally.
This is after the discussion from #6 and closes #6.
=> Set locale to EN for checkstyle messages.

src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java
The openapi.json specified the created/updated date were strings, but it was returning numbers.
I noticed the comment about the ISO8601 and changed the dates to be string.
=> Set Json type of Date's as string

src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java
- This clears the "Response" object in the openapi
when in reality is returning an empty string
=> Set empty responses

src/main/resources/db/migration/V1.0.0__notifications.sql
Current proposal is to attempt to include the 'pgcrypto' install as part of the migration definition. As this change should be idempotent, if we merge this change we will then need to confirm that it addresses the container instantiation issue without requiring elevated permissions for OSDv4.
=>  Add command to include pgcrypto in migrated configuration.

src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java
By specifying the schema as string for empty responses.
=> Remove "Response" object from openapi

src/main/java/com/redhat/cloud/notifications/auth/RbacIdentityProvider.java, src/main/java/com/redhat/cloud/notifications/auth/RbacRaw.java, src/main/resources/application.properties, src/test/java/com/redhat/cloud/notifications/routers/AuthenticationTest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java
Setting this property to false allows full access always (still requires x-rh-identity)
=> Add new property: rbac.enabled

src/main/java/com/redhat/cloud/notifications/auth/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/auth/RbacClientResponseFilter.java, src/main/java/com/redhat/cloud/notifications/auth/RbacRestClientRequestFilter.java, src/main/java/com/redhat/cloud/notifications/auth/RbacServer.java, src/test/java/com/redhat/cloud/notifications/openapi/OpenApiTest.java, src/test/java/com/redhat/cloud/notifications/routers/AuthenticationTest.java
Also be more explicit about dealing with missing x-rh-id header.
This also adds the `-Ddevelop.exceptional.user.auth.info` property like for policies-ui-backend.
=> Another try to log Rbac-failures. 

src/main/resources/templates/Policies/instantEmailBody.html, src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, src/test/java/com/redhat/cloud/notifications/templates/TestPoliciesTemplate.java
- Adds the triggered policy name
Before:
After:
=> Fix instant email body

src/main/java/com/redhat/cloud/notifications/routers/LivenessService.java, src/test/java/com/redhat/cloud/notifications/routers/HealthCheckTest.java
If we don't close them, we leak connections and deplete the pool.
=> Close DB-connections after health-checking

src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, src/test/java/com/redhat/cloud/notifications/models/TestEndpointType.java
Something I noticed, we need to be careful with the EndpointType enum, and always add new entries at the end of it. The ordinal number is the one stored in the db as "endpoint_type".
=> Test EndpointType order is not changed

pom.xml, src/main/java/com/redhat/cloud/notifications/auth/RbacIdentityProvider.java, src/main/java/com/redhat/cloud/notifications/auth/RbacRaw.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/test/java/com/redhat/cloud/notifications/MockServerClientConfig.java, src/test/java/com/redhat/cloud/notifications/RbacParsingTest.java, src/test/resources/rbac-examples/rbac_example_two_apps1.json
This queries the RBAC server for both notifications and integrations data and then sets the roles accordingly.
The RBAC-server needs a configuration for integrations before this can be deployed.
=> NOTIF-69 Separate RBAC for Notifications and Integrations.

helpers/create_application.py, helpers/helpers.py, pom.xml, src/main/java/com/redhat/cloud/notifications/db/AbstractGenericResource.java, src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/BundleResources.java, src/main/java/com/redhat/cloud/notifications/models/Application.java, src/main/java/com/redhat/cloud/notifications/models/Bundle.java, src/main/java/com/redhat/cloud/notifications/models/EventType.java, src/main/java/com/redhat/cloud/notifications/routers/ApplicationService.java, src/main/java/com/redhat/cloud/notifications/routers/BundlesService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/resources/db/migration/V1.5.0__NOTIF-116_add_bundles.sql, src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/BundleServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
Introduce Bundles as group of applications. 
Bundle->Applications is 1:n
The application now has a field bundle_id.
Application names are now only unique within a bundle.
The PR also adds some python code in helpers that one can use to quickly generate a Bundle+Application+EventType
=> NOTIF-116 Introduce Bundles

pom.xml, src/test/java/com/redhat/cloud/notifications/RbacParsingTest.java
While investigating a deserialization issue with the Hibernate Reactive migration branch, I noticed Yasson in the POM. Since Jackson is already available and the app is relying on it, I think we can get rid of Yasson.
=> Remove Yasson from test dependencies

src/main/resources/templates/Policies/dailyEmailBody.html, src/main/resources/templates/Policies/instantEmailBody.html, src/main/resources/templates/insightsEmailBody.html, src/test/java/com/redhat/cloud/notifications/templates/TestPoliciesTemplate.java
- Split into insightsEmailTemplate base and policies
The content should be same but more compatible with browsers and email clients.
Took them from https://github.com/RedHatInsights/frontend-assets/tree/master/src/email-assets/email-templates
- Had to manually update image urls from github to cloud.redhat.com
- Use qute to prevent evaluation of some parts. {padding:0} was picked by qute and throw errors when running the tests
- Remove some content to match the "simple" templates.
=> NOTIF-22 Update policies templates

src/main/java/com/redhat/cloud/notifications/db/EmailAggregationResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/resources/db/migration/V1.9.0__NOTIF-138_hibernate_reactive_remove_jsonb.sql
The `jsonb` native type from PostgreSQL isn't natively supported by Hibernate (Reactive or ORM). Someone from the Quarkus community created a [Quarkiverse extension](https://github.com/quarkiverse/quarkus-hibernate-types) (based on Vlad Mihalcea's [hibernate-types](https://github.com/vladmihalcea/hibernate-types)) to add `jsonb` support to Hibernate ORM with Quarkus, but it does not work with Hibernate Reactive.
@josejulio I tested this locally, everything seemed OK from a backend point of view. My tests included manipulating data saved from `master` with the `jsonb` type and then reused from this branch with the migrated `text` type.
As we discussed earlier, could you please test this with the full notifications app?
cc @pilhuhn
=> NOTIF-138 Replace jsonb with text in database

src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java, src/main/resources/application.properties, src/test/resources/application.properties
This PR contains some preparation work for the Hibernate Reactive migration.
`quarkus-hibernate-reactive` is not currently compatible with `quarkus-flyway` because:
- Flyway requires a JDBC connection
- `quarkus-flyway` creates a JDBC datasource to satisfy Flyway's requirement
- `quarkus-hibernate-reactive` cannot start if there is a JDBC datasource in the application
This incompatibility is in the process of being fixed. More infos in the following Quarkus ticket: https://github.com/quarkusio/quarkus/issues/10716
In the meantime, we can work around this issue with this PR which can be merged into `master` as soon as it has been reviewed.
FYI, the same issue happens with `quarkus-liquibase`.
=> NOTIF-138 Work around Quarkus flyway/hibernate-reactive incompatibility

src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/BundleServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
This PR contains some preparation work for the Hibernate Reactive migration.
Unlike R2DBC or Hibernate ORM, Hibernate Reactive does not allow us to retrieve values (UUID or timestamp) generated by PostgreSQL during an `INSERT` or an `UPDATE`. Because of that, if we want to keep sending generated values in the REST responses without performing an additional `SELECT` each time we change something in the database, the generation has to happen in the Java code (which is fairly easy with Hibernate). But the Hibernate UUID generator is only run if the `id` attribute is `null` when the data is about to be persisted, so we have to make sure that an `id` will never come from an API request. Therefore, in the Hibernate Reactive migration PR, all API classes identifiers will be annotated with …
=> NOTIF-138 Prepare tests for the Hibernate Reactive migration

src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java
This PR contains some preparation work for the Hibernate Reactive migration.
It prevents exisiting (and yet mostly invisible) concurrent accesses to the database which will become a blocking problem with Hibernate Reactive since the `Session` (and the underlying `EntityManager`) should not be used concurrently.
@cescoffier Could you please review these changes? I know there are many other things we need to fix regarding the way Mutiny is used in this project. We will take care of them soon, but not in this PR :)
=> NOTIF-138 Fix database concurrency issues

src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java
`flatMap()` is a shortcut for `onItem().transformToMulti(mapper).merge()`.
We shouldn't `merge()` here because it will cause DB queries to be executed concurrently, which is not allowed by Hibernate Reactive within a single unit of work.
=> Fix hidden database concurrency issue

pom.xml, src/main/java/com/redhat/cloud/notifications/auth/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/auth/RbacIdentityProvider.java, src/main/java/com/redhat/cloud/notifications/auth/RhIdentityAuthenticationRequest.java, src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java
We need that Quarkus version for many reasons, including Hibernate Reactive.
Tests are failing, it seems to be caused by:
https://github.com/RedHatInsights/notifications-backend/blob/c46eecf5d808081fb7fef1bf7a52acecd6999422/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java#L84-L85
Smallrye Reactive Messaging is throwing the exception and its version was bumped in the Quarkus release. I'm talking with them to figure out what's wrong and how to fix that.
=> Bump Quarkus to 1.13.0.Final

src/main/docker/Dockerfile-build.jvm
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12
> Starting the application
The biggest change here is that to start your Quarkus application, you should now use:
java -jar target/quarkus-app/quarkus-run.jar
(instead of using the versioned -runner jar)
=> Update Quarkus JAR path for Docker

src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java
@josejulio found an issue on CI: after he successfully changed a webhook URL (the change was persisted), `EndpointProcessor` was still using the old URL while processing a new payload.
I will confirm that tomorrow, but I'm pretty sure this happened because the Hibernate `session` is a `@RequestScoped` bean and it seems there are no request boundaries for a Smallrye RM inbound connector. The request context seems to be created when the first incoming message is received and is never destroyed after that.
This PR contains a simple fix for that issue: the `session` L1 cache is cleared after each processed message. I'll talk with the SM RM and/or Hibernate Reactive teams to determine if that's the best approach. In the meantime, this can be merged to fix the bug.
=> Clear Hibernate session L1 cache after message processing

src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/resources/db/migration/V1.12.0__notification_history_id.sql, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
This PR changes the notification_history.id type from integer to uuid.
We need that for the delivery-via-camel PoC, but it will also be better if we decide to expose the history through an API in the future (exposing an auto-incremented integer id would be a security flaw).
It's a draft for now because I need to figure out how to update the frontend.
=> Change NotificationHistory.id type from Integer to UUID

helpers/policies-notification-to-sql.py, pom.xml, src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/migration/policynotification/PoliciesEmailSubscription.java, src/main/java/com/redhat/cloud/notifications/migration/policynotification/PoliciesMigrationService.java, src/main/java/com/redhat/cloud/notifications/migration/policynotification/PolicyNotifications.java, src/main/resources/application.properties, src/test/java/com/redhat/cloud/notifications/migration/policynotification/PoliciesMigrationServiceTest.java
This PR adds an internal endpoint to migrate the data from `policies-notification`. 
It subscribes each user to the email type (instant/daily) found and updates the actions of the `policies-triggered` eventType of every account to use "Email" (deletes others if found).
=> NOTIF-161 Adding internal endpoint to pull data from policies-notifications

src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, src/test/java/com/redhat/cloud/notifications/CounterAssertionHelper.java, src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
`LifecycleITest.t02_pushMessage()` started failing on my machine (because of the counter check at the end) after #151 was merged.
This PR introduces a reliable way to assert counters increments during tests.
=> Introduce CounterAssertionHelper and fix test instability

src/test/java/com/redhat/cloud/notifications/db/DbCleaner.java, src/test/java/com/redhat/cloud/notifications/db/DbIsolatedTest.java, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/migration/policynotification/PoliciesMigrationServiceTest.java, src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/BundleServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/OldUserConfigServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
Our tests are full of side-effects: many of them depend on / suffer from data persisted by other tests. This makes the tests unreliable and sometimes very hard to maintain.
This PR fixes that issue by resetting the database before and after each test. I wanted to do that using [io.quarkus.test.TestTransaction](https://github.com/gwenneg/quarkus/blob/main/test-framework/common/src/main/java/io/quarkus/test/TestTransaction.java) but unfortunately it does not work with Hibernate Reactive. I'll create a Quarkus issue about this later.
I need this PR to be merged before I can finish the behavior groups PR.
⚠️ Check `Hide whitespace changes` for an easier review.
=> Improve tests isolation and maintainability

src/main/java/com/redhat/cloud/notifications/auth/RHIdentityAuthMechanism.java, src/main/resources/application.properties
Let's align with https://github.com/RedHatInsights/policies-ui-backend/pull/179, it will make things easier to maintain if all projects have the same behavior.
=> Make the non-application-root-path consistent with policies

.github/workflows/build.yml, pom.xml
I think we don't need to call "mvn install" here. As far as I understand our code, it is not necessary to put the build artefacts in the local .m2/repository folder. So "mvn verify" should be enough, faster and the better option in this case.
=> Build applications with mvn verify

src/main/java/com/redhat/cloud/notifications/templates/LocalDateTimeExtension.java, src/main/java/com/redhat/cloud/notifications/utils/TimeAgoFormatter.java, src/main/resources/templates/Advisor/newRecommendationInstantEmailBody.html, src/test/java/com/redhat/cloud/notifications/utils/TestTimeAgoFormatter.java
- Transforms dates(or date-strings) to a "1 year ago" format
- Fixes on Advisor templates
I ended up using an implementation based on `Period` to mimic what Advisor has in their [UI](https://cloud.redhat.com/insights/advisor/recommendations?rule_status=enabled&sort=-total_risk&limit=10&offset=0&text=%2Fvar%2Fww).
=> Introduces timeAgo() function on templates.

src/test/java/com/redhat/cloud/notifications/db/DbCleaner.java, src/test/java/com/redhat/cloud/notifications/db/DbIsolatedTest.java
`DbCleaner` currently shares the `Mutiny.Session` of the tests (because they have a common CDI request context), which prevents us from testing DB exceptions (like constraints violations for example) because when such an exception is thrown, the Hibernate session becomes unusable (see [here](http://hibernate.org/reactive/documentation/1.0/reference/html_single/#_using_the_reactive_session)). As a consequence, the database cannot be cleaned if a `PgException` is thrown.
This PR fixes that issue. `DbCleaner` is now executed through a REST call which automatically creates a dedicated request context. The `DbCleaner` session is therefore isolated from the tests session.
=> Run DbCleaner with a dedicated Session

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/events/DefaultProcessor.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroupAction.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroupActionId.java, src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, src/main/java/com/redhat/cloud/notifications/models/EndpointDefault.java, src/main/java/com/redhat/cloud/notifications/models/EndpointTarget.java, src/main/java/com/redhat/cloud/notifications/models/EndpointTargetId.java, src/main/java/com/redhat/cloud/notifications/models/EndpointType.java, src/main/java/com/redhat/cloud/notifications/models/EventTypeBehavior.java, src/main/java/com/redhat/cloud/notifications/models/EventTypeBehaviorId.java, src/main/java/com/redhat/cloud/notifications/models/filter/ApiResponseFilter.java, src/main/java/com/redhat/cloud/notifications/routers/BundlesService.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/resources/db/migration/V1.13.0__NOTIF-150_behavior_groups_phase1.sql, src/test/java/com/redhat/cloud/notifications/TestHelpers.java, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, src/test/java/com/redhat/cloud/notifications/db/DbCleaner.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/events/Lifecycle_BG_ITest.java, src/test/java/com/redhat/cloud/notifications/models/TestEndpointType.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
This is phase 1 of #170. It's meant to be non-breaking, without any effect on the production.
It can be used to test the behavior groups on CI/QA.
`notifications-frontend` does not have to be updated right away, this PR can be merged without breaking the UI.
=> NOTIF-150 Introduce behavior groups - Phase 1

src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacClientResponseFilter.java, src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacIdentityProvider.java, src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacRaw.java, src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacRestClientRequestFilter.java, src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacServer.java, src/main/java/com/redhat/cloud/notifications/auth/rhid/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/auth/rhid/RhIdPrincipal.java, src/main/java/com/redhat/cloud/notifications/auth/rhid/RhIdentity.java, src/main/java/com/redhat/cloud/notifications/auth/rhid/RhIdentityAuthenticationRequest.java, src/main/java/com/redhat/cloud/notifications/routers/AdminService.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java, src/test/java/com/redhat/cloud/notifications/MockServerClientConfig.java, src/test/java/com/redhat/cloud/notifications/TestHelpers.java, src/test/java/com/redhat/cloud/notifications/auth/rbac/RbacParsingTest.java
add separate packages for rhid and rbac auth so we have a cleaner code base and don't violate the separation of concerns principle.
=> add separate packages for rhid and rbac auth

src/main/java/com/redhat/cloud/notifications/db/BundleResources.java, src/main/java/com/redhat/cloud/notifications/routers/BundlesService.java, src/test/java/com/redhat/cloud/notifications/routers/BundleServiceTest.java
If a Bundle `name` is modified, the integration with onboarded apps will break. As suggested by @theute, we need some kind of alias for the name to give the apps the opportunity to migrate from the old one to the new one. This will be taken care of in a separate PR.
=> NOTIF-165 Add API to modify a Bundle

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/routers/ApplicationService.java, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java
If an Application `name` is modified, the integration with onboarded apps will break. As suggested by @theute, we need some kind of alias for the name to give the apps the opportunity to migrate from the old one to the new one. This will be taken care of in a separate PR.
=> NOTIF-166 Add API to modify an Application

src/main/resources/templates/Drift/newBaselineDriftInstantEmailBody.html
I was using insights_id instead of inventory_id to create URLs in the email template.  This fixes it.
=> [DRFT-334] use inventory_id in email template, not insights_id

src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java
The prod schema was successfully migrated today, we no longer need that.
=> Disable the flyway_schema_history repair on startup

src/main/java/com/redhat/cloud/notifications/db/EmailAggregationResources.java, src/test/java/com/redhat/cloud/notifications/db/EmailAggregationResourcesTest.java
This PR fixes a small Hibernate migration oversight (which is luckily harmless) in an HQL query.
Since it scared me for a second, I added a few tests to better detect `EmailAggregationResources` regressions.
=> Add EmailAggregationResourcesTest

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/BundleResources.java, src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/routers/BundlesService.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java
Hibernate Reactive result sets are emitted as a `Uni` item. We should not transform them to `Multi` when we don't need to.
=> Stop transforming Uni to Multi when not relevant

src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroupAction.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/resources/db/migration/V1.15.0__behavior_group_actions.sql, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
@josejulio: Here's what we talked about last week.
`DELETE /api/notifications/v1.0/notifications/behaviorGroups/{behaviorGroupId}/actions` no longer exists.
`PUT /api/notifications/v1.0/notifications/behaviorGroups/{behaviorGroupId}/actions` now takes care of actions addition, removal and order in the UI. I couldn't use `order` since it's a SQL reserved word so I used `BehaviorGroupAction.position` instead, but I hesitated with `rank`. This is super easy to rename so don't hesitate to suggest a different name.
=> Insert, update and delete behavior group actions with a single REST call

src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java
Not related to the production exception, but still important.
Currently, when a Kafka message is processed, the Hibernate session is not cleared in case of failure during the message processing. Also, in case of success, the clear is done in a blocking way.
This PR fixes both of these issues: the session is now _always_ cleared and it's done in a non-blocking way.
=> Clear the Hibernate session when a message processing fails

src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacIdentityProvider.java, src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacRestClientRequestFilter.java, src/test/java/com/redhat/cloud/notifications/TestHelpers.java
`UTF_8` should always be enforced when the `String` constructor is called. Same for `String.getBytes`.
=> Enforce UTF_8 for all Base64 encoding/decoding

helpers/helpers.py, src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/BundleResources.java, src/main/java/com/redhat/cloud/notifications/models/Application.java, src/main/java/com/redhat/cloud/notifications/models/EventType.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, src/test/java/com/redhat/cloud/notifications/db/DbCleaner.java, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/events/Lifecycle_BG_ITest.java, src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java
@josejulio Sorry, I need your help again reviewing an internal APIs PR 😃
This one shortens:
- `POST /applications/{appId}/eventTypes` to `POST /eventTypes`
- `POST /bundles/{bundleId}/applications` to `POST /applications`
Helper scripts were updated.
=> Shorten Application and EventType POST URLs

src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java
This is a proposal to not log potentially private info but the info that would be useful to us.
A log line would look like:
`Processing received payload: (123456) rhel/policies/triggered-policy`
Additional I changed from DEBUG to INFO
=> Limit what we show in logs

src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacIdentityProvider.java
Quarkus throws the following exception if a try to access an API which requires authentication and `rbac.enabled=false`:
```
2021-05-07 13:00:23,526 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-11) HTTP Request to /api/integrations/v1.0/endpoints failed, error id: 4e3cef90-66e9-4caf-8872-a5e1c995a26d-1: java.lang.IllegalStateException: Principal is null but anonymous status is false
at io.quarkus.security.runtime.QuarkusSecurityIdentity$Builder.build(QuarkusSecurityIdentity.java:235)
at com.redhat.cloud.notifications.auth.rbac.RbacIdentityProvider.lambda$authenticate$0(RbacIdentityProvider.java:56)
[...]
```
Since we're not performing any authentication and we're giving full permissions when `rbac.enabled=false`, using `new RhIdPrincipal("-noauth-", "-1")` seems …
=> Fix RbacIdentityProvider when rbac.enabled=false

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/EmailAggregationResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointEmailSubscriptionResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/events/DefaultProcessor.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java, src/test/java/com/redhat/cloud/notifications/db/EmailAggregationResourcesTest.java, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java
This is preparation work for #202.
I found something about the response time issue with `quarkus-resteasy-reactive`: the response time can be bad only with APIs that return `Multi`. There's no problem with methods returning `Uni<List>`, which should always be the type we use anyway because we never need to stream data back to the client. I created https://github.com/quarkusio/quarkus/issues/17094 to report the issue with `Multi` to the Quarkus team.
Since we're using `Multi` in many places for wrong reasons, I did some spring cleaning and replaced `Multi` with `Uni<List>`. A few methods could be cleaned further but I chose not to because they will be removed with phase 2 of behavior groups.
Here are some ground rules for future developments:
- The persistence layer (`*Resources` classes) …
=> NOTIF-55 Use Multi when relevant, replace with Uni<List> otherwise

src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java
Quarkus [default scope for JAX-RS resources](https://quarkus.io/guides/rest-json#lifecycle-of-resources) is `@Singleton`. It is used for all of our JAX-RS resources except this one and I don't see any valid reason why things would be different here.
=> Fix UserConfigService CDI scope

pom.xml, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/test/java/com/redhat/cloud/notifications/routers/AuthenticationTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
Blocked by https://github.com/quarkusio/quarkus/issues/16577: the `x-rh-identity` header is not sent because of a Quarkus bug, which leads to a failed RBAC call.
It should be fixed in Quarkus `1.13.3.Final`.
=> NOTIF-55 Migrate to resteasy-reactive and rest-client-reactive

src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/test/java/com/redhat/cloud/notifications/events/Lifecycle_BG_ITest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
So this is probably be cause of the recent migration to reasteasy-reactive-*.
The UI code started failing because it was receiving empty/string responses with the "application/json" content-type in the response. It looks like we need to annotate each method. I think that the previous implementation used the `@Schema` annotation to decide.
=> Mark endpoints that return a string as text/plain

src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/models/WebhookProperties.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java
@gwenneg This is an idea I had while working on https://github.com/RedHatInsights/notifications-backend/pull/242 to reduce the N-required queries to only 1 per type.
Could you review it does what I think it does? :) - Using only 1 extra SQL call per found type -
=> Batch "properties endpoint" SQL queries

src/main/java/com/redhat/cloud/notifications/templates/AdvisorOpenshift.java, src/main/resources/templates/AdvisorOpenshift/newRecommendationInstantEmailBody.html, src/main/resources/templates/AdvisorOpenshift/newRecommendationInstantEmailTitle.txt, src/main/resources/templates/AdvisorOpenshift/weeklyDigestEmailBody.html, src/main/resources/templates/AdvisorOpenshift/weeklyDigestEmailTitle.txt, src/test/java/com/redhat/cloud/notifications/templates/TestOpenshiftAdvisorTemplate.java
I just spotted and fixed that spelling issue in the templates that were recently added.
I only fixed the "public" part of the templates (the one that is displayed to the end user). There are still many occurrences of `Openshift` (without a capital `S`) in the code but that's only code so it's less important.
=> Fix OpenShift spelling in email templates

src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java
The goal of this PR is to investigate the following error on stage:
```
2021-06-01 06:01:42,520 INFO  [com.red.clo.not.eve.EventConsumer] (vert.x-eventloop-thread-0) Could not process the payload: [...]: javax.persistence.PersistenceException: org.hibernate.HibernateException: io.vertx.pgclient.PgException: insert or update on table "notification_history" violates foreign key constraint "notification_history_endpoint_id_fkey"
```
=> Add internal API to investigate stage endpoint issue

.github/workflows/build.yml, src/main/java/com/redhat/cloud/notifications/auth/rhid/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/java/com/redhat/cloud/notifications/routers/OApiService.java, src/test/java/com/redhat/cloud/notifications/openapi/OpenApiTest.java
- This is most for dev usage on features that are not "released" yet.
Allows the UI to read and generate the types required for querying
the server.
=> Exposing private api internally

src/main/java/com/redhat/cloud/notifications/db/EmailAggregationResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointEmailSubscriptionResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/db/session/StatelessSessionProducer.java, src/main/java/com/redhat/cloud/notifications/events/DefaultProcessor.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
This PR replaces the Hibernate Reactive regular session with a `StatelessSession` for all database queries executed during a Kafka message processing.
> A stateless session:
>- doesn’t have a first-level cache (persistence context), nor does it interact with any second-level caches, and
>- doesn’t implement transactional write-behind or automatic dirty checking, so all operations are executed immediately when they’re explicitly called.
https://hibernate.org/reactive/documentation/1.0/reference/html_single/#_stateless_sessions
⚠️ Persistence operations never cascade to associated instances with a `StatelessSession` (it's not a problem in this PR).
Why do that? Because:
1. The regular session is supposed to be short-lived and discarded at the end of a single logical unit of work. In other …
=> Process Kafka messages with a StatelessSession

src/main/java/com/redhat/cloud/notifications/models/EndpointTarget.java, src/main/java/com/redhat/cloud/notifications/routers/BehaviorGroupMigrationService.java, src/main/resources/application.properties, src/test/java/com/redhat/cloud/notifications/routers/BehaviorGroupMigrationServiceTest.java
This PR:
- introduces the API that will be used to trigger the behavior groups data migration
- does _not_ enable the Kafka messages processing using behavior groups
- does _not_ modify any existing DB data (the migration only consists in adding new data)
- does _not_ delete the `endpoint_targets` and `endpoint_defaults` DB tables (we'll do that later, there's no rush)
ℹ️ Merging it won't have any effect on the app or the database as long as the migration isn't triggered.
To trigger the migration, simply call `GET /internal/behaviorGroups/migrate?confirmation-token=ready-set-go`. The confirmation token may be removed before this is merged.
If the migration is successful, the HTTP response will contain a small report about what's been migrated:
```
{
"duration_in_ms": 262, …
```
=> NOTIF-150 Add behavior groups data migration API

src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java
The API served its purpose: the endpoint was never actually deleted from the database when we had a foreign key constraint violation.
=> Remove stage endpoint issue investigation API

src/main/java/com/redhat/cloud/notifications/Constants.java, src/main/java/com/redhat/cloud/notifications/auth/rhid/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/db/StatusResources.java, src/main/java/com/redhat/cloud/notifications/db/converters/StatusConverter.java, src/main/java/com/redhat/cloud/notifications/models/CurrentStatus.java, src/main/java/com/redhat/cloud/notifications/models/Status.java, src/main/java/com/redhat/cloud/notifications/models/validation/MaintenanceWithTimeInterval.java, src/main/java/com/redhat/cloud/notifications/models/validation/MaintenanceWithTimeIntervalValidator.java, src/main/java/com/redhat/cloud/notifications/routers/AdminService.java, src/main/java/com/redhat/cloud/notifications/routers/BehaviorGroupMigrationService.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/main/java/com/redhat/cloud/notifications/routers/StatusService.java, src/main/java/com/redhat/cloud/notifications/routers/filters/MaintenanceModeRequestFilter.java, src/main/resources/application.properties, src/main/resources/db/migration/V1.20.0__NOTIF-226_maintenance_mode.sql, src/test/java/com/redhat/cloud/notifications/db/DbCleaner.java, src/test/java/com/redhat/cloud/notifications/db/DbIsolatedTest.java, src/test/java/com/redhat/cloud/notifications/routers/StatusServiceTest.java
⚠️ This does NOT include a maintenance mode for the Kafka messages processing. It only affects REST APIs calls.
Get the current status: `GET /api/notifications/v1.0/status`
Change the current status: `PUT /internal/status`
`GET`/`PUT` will respectively return/accept this data structure:
```
{
"status": "UP",
"start_time": "2021-06-11T13:09:31.213141",
"end_time": "2021-06-11T13:09:31.213141"
}
```
The status can be set to:
- `UP`: all APIs are available
- `MAINTENANCE`: `/internal/*`, `/health/*`, `/metrics*` and `/api/notifications/v1.0/status` are available, all other APIs return 503
**❓ How does maintenance mode work?**
I introduced `MaintenanceModeRequestFilter` which performs two checks before a REST API call is processed:
- First it checks whether the API should be affected by …
=> NOTIF-226 Introduce maintenance mode

src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
With this PR, if:
- `endpoint` is linked with `behavior group A` and `behavior group B`
- `event type` is linked with `behavior group A` and `behavior group B`
when we will process a Kafka message for `event type`, `endpoint` will only be notified once.
Duplicate email notifications are still possible (with different endpoints), that's only the first step towards duplicates prevention.
=> NOTIF-150 Prevent duplicate notifications for a single endpoint

src/main/java/com/redhat/cloud/notifications/NotificationsApp.java
Fixes:
```
[INFO] [io.quarkus.arc.processor.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
- @Inject field com.redhat.cloud.notifications.NotificationsApp#loggerName
```
=> Fix build time injection warning

src/main/resources/application.properties
Based on #312.
The Docker image resulting from this PR build should be deployed on prod:
- After the data migration is done.
- Before the maintenance mode is disabled.
=> NOTIF-150 Enable Kafka ingress channel

pom.xml, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
This fixes a test race condition:
1. The test produces a Kafka message in the `ingress` channel and waits for a webhook call.
2. The message is processed and the webhook call is done.
3. Then in an unpredictable order, an history entry is persisted and the test tries to retrieve that entry. Sometimes, the retrieval happens before the entry was persisted.
cc @josejulio
=> Fix test race condition

src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/EndpointTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java
This ticket will be divided into two PRs (reviews will be easier). This one changes the way actions are processed:
| Before | After |
| - | - |
| Each target endpoint is processed separately by the relevant processor. There is no way to detect multiple `EMAIL_SUBSCRIPTION` endpoints and prevent email duplicates. | Each processor receives all the endpoints it has to notify at once for a single action. Email duplicates prevention becomes possible. |
Next step: email duplicates prevention implementation.
=> NOTIF-236 Lay some groundwork for email duplicates prevention

pom.xml, src/test/java/com/redhat/cloud/notifications/MockServerClientConfig.java, src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
While adding mockserver to policies-engine, I realized we're not actually stuck with `mockserver-client-java:5.5.4`.
=> Bump mockserver-client-java to 5.11.2

backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, pom.xml
`mockserver:5.11.2` is causing the tests instability.
I tried to fix the issue without success so let's rollback to `5.5.4` for now.
=> Fix tests instability

backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
The second part is shorter than what I had in mind initially.
This code is kind of temporary. It will change if we add fields to `EmailSubscriptionProperties` and we certainly will in the future.
=> NOTIF-236 Prevent duplicate email notifications

backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/DriftEmailPayloadAggregator.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/EmailPayloadAggregatorFactory.java, backend/src/main/java/com/redhat/cloud/notifications/templates/Drift.java, backend/src/main/resources/templates/Drift/dailyEmailBody.html, backend/src/main/resources/templates/Drift/dailyEmailTitle.txt, backend/src/test/java/com/redhat/cloud/notifications/DriftTestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/DriftEmailPayloadAggregatorTest.java, backend/src/test/java/com/redhat/cloud/notifications/templates/TestDriftTemplate.java
Run:
`./mvnw install --projects :notifications-backend -Dtest=DriftEmailPayloadAggregatorTest -Dskip.yarn`
You may see a result like this is the logs:
```
{
"drift": {
"baseline_01": {
"baseline_id": "baseline_01",
"baseline_name": "drift_baseline_test",
"hosts": [
{
"display_name": "Drift test machine",
"inventory_id": "host-01",
"tags": []
},
{
"display_name": "Drift test machine",
"inventory_id": "host-02",
"tags": []
}
],
"unique_system_count": 2
},
"baseline_02": {
"baseline_id": "baseline_02",
"baseline_name": "drift_baseline_test",
"hosts": [
{
"display_name": "Drift test machine",
"inventory_id": "host-01",
"tags": []
},
{
"display_name": "Drift test machine",
"inventory_id": "host-03",
"tags": []
}
],
"unique_system_count": 2
}
},
"unique_system_count": 3,
"start_time": null, …
```
=> DRFT-344 Add Daily email template for Drift

backend/src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, backend/src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, backend/src/main/java/com/redhat/cloud/notifications/models/EmailSubscriptionProperties.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EmailEndpointMigrationService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/TestEmailEndpointMigrationService.java
This prevents the creation of multiple Endpoint with type `EmailSubscription` and adds an API to get the `Endpoint` (with `EmailSubscription` type) represented by the `EmailSubscriptionProperties`. 
Currently the properties is an empty object, but going soon this will change to be able to configure it. 
This PR also has a migration function that is in charge of collapsing the multiple `EmailSubscription Endpoint's` into a single one (per account) and update the `BehaviorGroupAction` (The link between a `BehaviorGroup` and an `Endpoint`) to use the account's default - Removing any duplicate in the process so that each behavior group can at max one `EmailSubscription Endpoint`.
To merge with https://github.com/RedHatInsights/notifications-frontend/pull/141
=> NOTIF-242 Prevent from creating/updating Email_Subscription endpoints

backend/src/main/webapp/package.json, backend/src/main/webapp/public/index.html
URL was fixed on `/internal`, moved so it can be relative to the base of the `index.html` file.
=> Use relative urls for internal UI

backend/src/main/webapp/package.json, backend/src/main/webapp/public/index.html
Tested locally opening build assets in the browser.
Previous attempt didn't work, because react adds the scripts to `index.html` at build time using the `PUBLIC_URL` as a base.
Changing the PUBLIC_URL to `.` yields base as `./` instead.
```
<script src="./static/js/main.0af8c67b.chunk.js">
```
=> Other attempt to have the internal UI relative

backend/src/main/java/com/redhat/cloud/notifications/processors/email/RecipientResolver.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/RecipientResolverTest.java
Adds a feature flag to avoid querying RBAC for the users. 
This does not actually revert back to the state before the personalized emails, what this does instead is avoiding querying for the user data with RBAC (which is the setup that we are missing).
There is still one email sent for each user, but the only data that can be personalized is the username.
Everything else is null, but no one is using it yet. It should be fine™.
=> Feature flag for rbac user query

backend/src/main/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilter.java, backend/src/test/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilterTest.java
Look like the `AuthRequestfilter` does not process the `@PostProcess`, maybe related to this one: https://github.com/quarkusio/quarkus/issues/5752
Maybe it works on quarkus 2.0+? Anyway, meanwhile I'm going to use the constructor to load the required params.
=> Fixes issue with recipients query

aggregator/src/main/java/com/redhat/cloud/notifications/NotificationsApp.java, aggregator/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/DailyEmailAggregationJob.java
In OpenShift ci we are getting this exception in every cronjob run:
2021-08-06 14:45:41,165 ERROR [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-0) SRMSG18206: Unable to write to Kafka from channel aggregation (topic: ...): org.apache.kafka.common.KafkaException: Producer closed while send in progress
Locally this doesn't happen with the same code, but when I add a System.exit(1) after sending the first AggregationCommand in the kafka topic, I get the same exception.
The Thread of the run() method is faster than the kafka connection thingy somehow.
This PR is just to see if this solves the issue on ci. If anyone has got a better idea of how to fix this issue... :-)
=> NOTIF-190 Add sleep to test if this fixes the exception in OpenShift

backend/src/main/java/com/redhat/cloud/notifications/processors/webhooks/ServerErrorException.java, backend/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, backend/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java
This PR adds retry logic to webhook calls when one of the following happens:
- The remote server returned a 5xx HTTP status, which could be caused by a temporary remote server issue.
- We had a technical communication issue during the call (e.g. `IOException`).
The `WebhookTypeProcessor#shouldRetry` method is meant to contain all exceptions that should cause a retry.
The retry logic is entirely configurable:
| Key | Description | Default |
| - | - | - |
| processor.webhook.retry.max-attempts | Max number of retries for a single webhook call (initial call included) | 3 |
| processor.webhook.retry.back-off.initial-value | Initial delay before the first retry attempt | 1S |
| processor.webhook.retry.back-off.max-value | Max delay before the last retry attempt (delay grows exponentially) | …
=> NOTIF-184 Retry on webhook call failure

backend/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, backend/src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/RenderEmailTemplateRequest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/RenderEmailTemplateResponse.java, backend/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateService.java, backend/src/main/java/com/redhat/cloud/notifications/utils/ActionParser.java, backend/src/main/webapp/src/Routes.tsx, backend/src/main/webapp/src/app/Navigation.tsx, backend/src/main/webapp/src/generated/OpenapiInternal.ts, backend/src/main/webapp/src/pages/RenderEmailPage.tsx, backend/src/main/webapp/src/services/RenderEmailRequest.ts
This could help devs into trying an email template without actually having to put the code in the repository and trigger an event.
The idea is to write the templates (subject, body) and the payloads to render on the page.
There is sample data to get started.
=> Render emails on admin UI 

backend/src/test/java/com/redhat/cloud/notifications/routers/NonApplicationRootPathTest.java
This guarantees the path to `/health`, `/metrics` and `/openapi.json` will not be broken and will still return `200` without any `301` redirection after a Quarkus migration.
=> Prevent non-application path regressions

.github/workflows/codeql-analysis.yml
The following error happens randomly during a CodeQL analysis after a @dependabot push:
```
Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
```
Example: see the checks from https://github.com/RedHatInsights/notifications-backend/commit/602c34d37ff44e0f9b8d838a2c6b5c2c3f711b98.
This PR should fix the issue.
=> Fix CodeQL analysis failure because of Dependabot

backend/src/main/java/com/redhat/cloud/notifications/routers/EventLogMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventLogMigrationServiceTest.java
CI database contains 265241 records in `notification_history`. The migration failed because it tried to load all these records into an `ArrayList` which caused an `OutOfMemoryError`.
The new code migrates 1000 records at a time and repeats itself until there's nothing more to migrate.
=> NOTIF-291 Fix OutOfMemoryError during notifications history migration

backend/src/test/java/com/redhat/cloud/notifications/TestConstants.java, backend/src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/DbCleaner.java, backend/src/test/java/com/redhat/cloud/notifications/db/EmailAggregationResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
This PR moves resources-related test code around to reduce code duplication and ease tests maintenance.
It will also help me with NOTIF-273 and NOTIF-291.
- 100% test code, no impact on prod
- 0% tests coverage change, it is exactly like it was before this PR
- 100% boring to review, I'll merge it by the end of the day (without approval) unless someone likes boring reviews 😄
=> Refactor resources usage in tests

backend/src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java
https://github.com/RedHatInsights/notifications-backend/pull/536 removed some Flyway scripts that had already been executed on CI and stage (not prod).
This PR repairs the Flyway schema history and in particular fixes that kind of error:
```
Detected applied migration not resolved locally: 1.23.0. If you removed this migration intentionally, run repair to mark the migration as deleted.
```
=> NOTIF-291 Repair CI and stage Flyway schema history

backend/src/main/java/com/redhat/cloud/notifications/routers/models/RequestEmailSubscriptionProperties.java
Fixes
```
ERROR in /notifications-frontend/src/services/Integrations/GetDefaultSystemEndpoint.ts
./src/services/Integrations/GetDefaultSystemEndpoint.ts 10:16-62
[tsl] ERROR in /notifications-frontend/src/services/Integrations/GetDefaultSystemEndpoint.ts(10,17)
TS2322: Type '{ only_admins: boolean; }' is not assignable to type 'RequestEmailSubscriptionProperties'.
Object literal may only specify known properties, but 'only_admins' does not exist in type 'RequestEmailSubscriptionProperties'. Did you mean to write 'onlyAdmins'?
```
=> Fix integrations OpenAPI casing issue

backend/src/main/resources/application.properties
As suggested by @pilhuhn during the team sync.
=> Increase expiration delay of cached RBAC data

backend/src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java
`repair()` was required because the Flyway scripts `V1.22` to `V1.26` were deleted and replaced with `V1.27` while some of them had already been executed on some environments.
CI, stage and prod were already migrated to `V1.27`. I'm leaving this around a bit more to help fixing migration issues in the devs local database.
=> NOTIF-291 Remove Flyway repair

backend/src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, backend/src/main/java/com/redhat/cloud/notifications/models/Event.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/SecurityContextUtil.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EventLogEntry.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EventLogEntryAction.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/PageLinksBuilder.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/models/PageLinksBuilderTest.java
This PR introduces the main REST API for the event log.
We will probably need two more (much smaller) REST APIs to retrieve:
- the properties of an endpoint displayed in the event log
- the details of an event
If this is confirmed, the missing APIs will be added in a separate PR.
=> NOTIF-291 Add EventService

backend/src/main/java/com/redhat/cloud/notifications/db/EventLogCleaner.java, backend/src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/EmailAggregationResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
This is phase 1 of the preparation work, there will be more. As a consequence, some parts of this PR may look unfinished but that's perfectly normal.
Quarkus 2 requires all tests involving Hibernate Reactive to be written in a reactive way. In other words, `.await().indefinitely()` has to be removed completely from tests (it won't happen before the bump).
=> NOTIF-273 Prepare tests for the Quarkus 2 bump

backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
After reviewing #576 I noticed that we could use `isEmailSubscriptionSupported` in this check.
=> Update method to check if subscription is supported

backend/src/main/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilter.java, backend/src/test/java/com/redhat/cloud/notifications/Json.java, backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/AuthenticationTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/StatusServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
Here's another prep work PR for Quarkus 2.
With Quarkus 1, we currently serialize the RestAssured request bodies with an `ObjectMapper` instance provided by Vert.x. That instance is customized in our test code because we use Jackson filters and `LocalDate(Time)`.
With Quarkus 2, the instance that was provided by Vert.x has been replaced by another one from Quarkus which is not customizable from tests. I created a Quarkus PR that made it customizable but it was refused, so we can no longer use the old way of serializing bodies.
This PR also contains a few unrelated changes that are all required for the Quarkus 2 bump.
=> NOTIF-273 Fix RestAssured body serialization with Quarkus 2

backend/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, backend/src/main/java/com/redhat/cloud/notifications/events/KafkaMessageDeduplicator.java, backend/src/main/java/com/redhat/cloud/notifications/events/KafkaMessagesCleaner.java, backend/src/main/java/com/redhat/cloud/notifications/models/KafkaMessage.java, backend/src/main/resources/db/migration/V1.29.0__message_deduplicator.sql, backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/KafkaMessagesCleanerTest.java
By default, Kafka guarantees that each message will be consumed/processed _at least once_. This PR introduces Kafka messages deduplication in order to consume each message _exactly once_. The underlying goal is to protect us against Kafka failures like the one we had recently on prod when our consumer failed to commit its offset because it was kicked out of the consumer group. We never confirmed it but it most probably led to duplicate notifications being sent during the incident.
This PR is based on two things:
- A new optional (for now) `rh-message-id` Kafka header which can be sent by the onboarded apps with their message. It is then used as a unique identifier for the message.
- A new `kafka_message` DB table where all valid messages IDs are stored for a limited period of time …
=> NOTIF-309 Deduplicate incoming ingress Kafka messages

backend/src/main/resources/application.properties
`backend` fails to start because of that missing conf value.
=> NOTIF-273 Add missing configuration value

backend/src/main/java/com/redhat/cloud/notifications/db/EmailAggregationResources.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
With this PR, the `cronjob_run.last_run` DB field will be updated each time the old aggregator is done processing aggregations. As a consequence, when the new aggregator will run for the first time on prod, it won't use the following date:
https://github.com/RedHatInsights/notifications-backend/blob/ea5d165851c8a736d58423e02741bb67c90cf52d/backend/src/main/resources/db/migration/V1.28.0__NOTIF-190_cronjob_timestamp.sql#L8
Otherwise, this would be sent on prod (it happened on stage today):
=> Fix daily aggregation date on new aggregator first execution

backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java
This fixes the following warning:
```
HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!
```
The warning cause as well as the solution implemented in this PR are explained here: https://vladmihalcea.com/fix-hibernate-hhh000104-entity-fetch-pagination-warning-message/
=> NOTIF-314 Prevent in memory events pagination

backend/src/main/java/com/redhat/cloud/notifications/events/KafkaMessagesCleaner.java, backend/src/main/resources/application.properties
This will prevent this warning from Kafka which showed up in Sentry:
```
The configuration 'messages.cleaner.period' was supplied but isn't a known config.
```
=> Prevent Kafka warning about a notifications config key

backend/src/main/resources/application.properties
We just had what seems to be a connection pool starvation on prod.
I'd like to see if there's anything useful regarding the prod issue in the Hibernate metrics.
=> Enable Hibernate Reactive metrics

backend/src/main/resources/application.properties
Related to #651.
With `quarkus.hibernate-orm.metrics.enabled=true`, Hibernate logs tons of statistics which are way too noisy for prod. We only need the Hibernate metrics available at `/metrics`.
```
2021-09-28T08:15:18.8092201Z 2021-09-28 08:15:18,798 INFO  [info] (vert.x-eventloop-thread-0) 127.0.0.1 - -noauth- 28/Sep/2021:08:15:18 +0000 "GET /internal/bundles/69efff0f-841d-4c1e-aa94-b05d37162618 HTTP/1.1" 200 133 "-" "Apache-HttpClient/4.5.13 (Java/11.0.11)"
2021-09-28T08:15:18.8131884Z 2021-09-28 08:15:18,799 INFO  [org.hib.eng.int.StatisticalLoggingSessionEventListener] (vert.x-eventloop-thread-0) Session Metrics {
2021-09-28T08:15:18.8138734Z     0 nanoseconds spent acquiring 0 JDBC connections;
2021-09-28T08:15:18.8144242Z     0 nanoseconds spent releasing 0 JDBC connections; …
```
=> Silence Hibernate statistics in logs

.rhcicd/grafana/grafana-dashboard-jvm.configmap.yaml
Adding a Grafana dashboard for JVM metrics.
This isn't specific to Notifications but that's the most convenient place I know right now...
This is a modified version of: https://grafana.com/grafana/dashboards/4701
This is to provision: 
https://grafana.stage.devshift.net/d/nID67wNnz/jvm-micrometer?orgId=1&from=now-1h&to=now&refresh=30s
=> Adding JVM dashboard

backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, backend/src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/main/resources/db/migration/V1.30.0__NOTIF-320_event_log_static_endpoint_type.sql, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java
This PR duplicates the `Endpoint#type` field into `NotificationHistory#endpointType` to make sure the data shown in the event log will not be altered by an endpoint deletion.
Deleting an `Endpoint` no longer causes a cascade delete of `NotificationHistory`.
=> NOTIF-320 Use static endpoint type in the event log

backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java
This PR adds the `endpointTypes` and `invocationResults` query params to the existing `/notifications/events` API.
=> NOTIF-324 Filter event log by endpoint type and invocation result

backend/src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java
https://github.com/RedHatInsights/notifications-backend/pull/733 served its purpose. The issue on ephemeral is fixed and we no longer need that log entry.
=> Revert "Log the Flyway JDBC URL (#733)"

backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java
This will fix a NPE that triggered Sentry alerts during QE tests.
=> Replace NotificationService NPE with a clean HTTP error

.rhcicd/clowdapp.yaml
- All dependencies are now mandatory (in opposition to optional before).
- `aggregator` and `backend` now have their own resources requests and limits.
- The `/tmp` volume is now named `rds-client-ca` because it may be used by `clowder-quarkus-config-source` to write the RDS certificate.
- Database name changed from `notifications` to `notifications_backend`.
- Several container vars (`APP_NAME`, `ENV_NAME`, `PATH_PREFIX`...) have been removed because they seemed unused. We may need to reintroduce them in case something got broken by that change.
- `CLOWDER_FILE` container var replaced with `ACG_CONFIG`. It will actually work that way once https://github.com/RedHatInsights/clowder-quarkus-config-source/pull/41 is merged and we depend on it here. In the meantime, we will use the default …
=> NOTIF-336 Prepare clowdapp.yaml for cutover to Clowder deployed stage

.rhcicd/clowdapp.yaml
```
01:16:26 W1104 00:16:26.224755   28410 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource
```
=> NOTIF-336 Fix clowdapp.yaml apiVersion

backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
This showed up in Jenkins during a clowderized pr_check:
```
09:44:48 [INFO] /home/jboss/backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java: Some input files use or override a deprecated API.
09:44:48 [INFO] /home/jboss/backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java: Recompile with -Xlint:deprecation for details.
```
=> Fix deprecated API message at compilation time

.rhcicd/clowdapp.yaml, backend/src/main/java/com/redhat/cloud/notifications/ClowderConfigInitializer.java
Tests from `pr_check.sh` are failing because RBAC isn't ready fast enough when the first test is run.
=> NOTIF-336 Work around an ephemeral RBAC timeout issue

.rhcicd/clowdapp-aggregator.yaml, backend/src/main/java/com/redhat/cloud/notifications/ClowderConfigInitializer.java
The timeout value is now managed from app-interface.
=> NOTIF-336 Remove the ephemeral RBAC timeout workaround

.rhcicd/build_deploy.sh
Or it won't build the rest since the Quay repo hasn't been provisioned yet ( https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/notifications/app.yml#L34 ) 
See https://ci.ext.devshift.net/job/RedHatInsights-notifications-backend-gh-build-master/548/
=> Disable Camel Demo Log build and deploy

.rhcicd/clowdapp-backend.yaml, README.adoc, backend/src/main/java/com/redhat/cloud/notifications/clowder/ClowderConfigInitializer.java, backend/src/main/java/com/redhat/cloud/notifications/db/FlywayEndEvent.java, backend/src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java, backend/src/main/java/com/redhat/cloud/notifications/ephemeral/Application.java, backend/src/main/java/com/redhat/cloud/notifications/ephemeral/Bundle.java, backend/src/main/java/com/redhat/cloud/notifications/ephemeral/EphemeralData.java, backend/src/main/java/com/redhat/cloud/notifications/ephemeral/EphemeralDataInitializer.java, backend/src/main/java/com/redhat/cloud/notifications/ephemeral/EventType.java, backend/src/main/resources/ephemeral/ephemeral_data.sample.json
This PR introduces data initialization on ephemeral environments.
▶️ **Which data?**
The init will persist any provided `Bundle`, `Application` or `EventType`.
We can't initialize any other kind of data because it would require an `accountId` which can only be found when a REST API is called from the UI (or the python helpers) or when we receive a Kafka message.
▶️ **When?**
The init will only happen if the `ENV_NAME` environment variable contains a value that starts with `env-ephemeral`.
It is guaranteed to happen _after_ the Flyway DB migration is done. For now, we're migrating the DB with [FlywayWorkaround](https://github.com/RedHatInsights/notifications-backend/blob/master/backend/src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java) which observes `StartupEvent`, so …
=> NOTIF-373 Introduce EphemeralDataInitializer

backend/src/main/java/com/redhat/cloud/notifications/ephemeral/EphemeralDataInitializer.java
Fixes this:
```
2021-11-10 20:22:16,757 ERROR [com.red.clo.not.eph.EphemeralDataInitializer] (main) Ephemeral data loading from file failed: java.nio.file.FileSystemNotFoundException
at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
at java.base/java.nio.file.Path.of(Path.java:208)
at com.redhat.cloud.notifications.ephemeral.EphemeralDataInitializer.loadFromFile(EphemeralDataInitializer.java:51)
```
=> NOTIF-373 Fix ephemeral data file loading

.rhcicd/clowdapp-backend.yaml
This is the preferred deployment naming which is already used in most migrated Clowdapps.
=> NOTIF-336 Fix clowdapp.yaml deployment name

.rhcicd/clowdapp-backend.yaml
This is a temporary fix, the value should come from `clowder-quarkus-config-source` eventually.
=> NOTIF-336 Add Postgres verification algorithm to clowdapp.yaml

.rhcicd/pr_check.sh
The IQE notifications plugin is currently broken which causes a PR check failure.
=> NOTIF-336 Disable PR check

.rhcicd/clowdapp-backend.yaml
`clowder-quarkus-config-source` should [take care of this](https://github.com/RedHatInsights/clowder-quarkus-config-source/blob/f5c72bc35de95d88d5303ea86017530f58797365/src/main/java/com/redhat/cloud/common/clowder/configsource/ClowderConfigSource.java#L192) now.
=> NOTIF-336 Remove POSTGRES_HOSTNAME_VERIFICATION_ALGORITHM env var

.rhcicd/pr_check.sh, .rhcicd/pr_check_backend.sh
The IQE plugin is fixed.
I had to increase the ephemeral deployment timeout because 300 seconds (default value) is too close from the average deployment time.
=> NOTIF-336 Restore backend PR check

backend/src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java
The query will never return more than one DB record. There's no point sorting or limiting the data.
=> Remove sort and limit from the notification details API

backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java
- Do not parse using the action parser.
Aggregation does not follow the same encoding rules
Reverts changes on `EmailAggregator` from https://github.com/RedHatInsights/notifications-backend/pull/595
`Hide whitespace` makes it easier to review
=> Reverting changes on the aggregator code

backend/src/main/resources/templates/Advisor/newRecommendationInstantEmailBody.html, backend/src/main/resources/templates/Advisor/newRecommendationInstantEmailTitle.txt, backend/src/main/resources/templates/Advisor/resolvedRecommendationInstantEmailBody.html, backend/src/main/resources/templates/Advisor/resolvedRecommendationInstantEmailTitle.txt, backend/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java
https://issues.redhat.com/browse/ADVISOR-1985
Better distinguish between Red Hat Enterprise Linux Advisor and OpenShift Advisor Instant Notification emails.
This issue showed up on the Advisor Jira board even though it was really a Notifications ticket.  I thought I'd knock it over anyway.
=> ADVISOR-1985 distinguish RHEL vs Openshift Advisor

.github/workflows/build.yml, docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-camel-demo-log.jvm
Build logs will be much shorter with this in Jenkins and GH.
=> Hide Maven downloads progress in build logs

.rhcicd/pr_check_backend.sh
The current 360 seconds timeout can lead to PR check failures if some dependencies are slower than usual.
Let's see how it goes with 420 seconds.
=> Increase backend PR check timeout

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java
This will silence the many `IllegalArgumentException: No enum constant com.redhat.cloud.notifications.models.EndpointType.TYPE` alerts we received on Sentry lately.
=> Return 400 on unknown endpoint types

backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java
This failure appeared in the GitHub build after #771 was merged:
```
2021-12-02T13:06:19.8068789Z 1 expectation failed.
2021-12-02T13:06:19.8069614Z Expected status code <200> but was <403>.
2021-12-02T13:06:19.8070222Z 
2021-12-02T13:06:19.8072779Z 	at com.redhat.cloud.notifications.events.LifecycleITest.createBehaviorGroup(LifecycleITest.java:290)
2021-12-02T13:06:19.8075898Z 	at com.redhat.cloud.notifications.events.LifecycleITest.test(LifecycleITest.java:109)
```
It doesn't happen on my machine so I'm not sure yet but this PR should fix it.
=> Fix RBAC mock settings collision in tests

.rhcicd/clowdapp-backend.yaml
This will be used from app-interface to prevent the issue we had on prod last night:
```
SRMSG18231: The record 5170910 from topic-partition 'platform.notifications.ingress-1' has waited for 61 seconds to be acknowledged. This waiting time is greater than the configured threshold (60000 ms). At the moment 1 messages from this partition are awaiting acknowledgement. The last committed offset for this partition was 5170909. This error is due to a potential issue in the application which does not acknowledged the records in a timely fashion. The connector cannot commit as a record processing has not completed.
```
See https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.1/kafka/kafka.html for more details.
=> Make unprocessed Kafka messages max age configurable

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Looks like the `* 60` shouldn't be there
=> Fixed sec/min issue in Grafana

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Made several adjustments, the most important is to have the most important info at the top about the health of the application.
So it shows the number of running pods and the current number of restarts.
There are additional graphs as well with historical details below:
I added the request/min for notifications-gw (and I can't explain why we have 1 request/sec)
=> Updated Grafana dashboard

backend/pom.xml
All scheduled tasks have been moved to an OpenShift CronJob. We no longer need that dependency.
Seen on prod:
```
@timestamp:Dec 8, 2021 @ 07:14:25.109 log.level:INFO message:No scheduled business methods found - Simple scheduler will not be started service.environment:prod process.thread.name:main log.logger:io.quarkus.scheduler.runtime.SimpleScheduler @id:36550235969418795718896017338455303230515520878533935108 @message:{"@timestamp":"2021-12-08T13:14:25.109Z", "log.level": "INFO", "message":"No scheduled business methods found - Simple scheduler will not be started", [...]
```
=> Remove quarkus-scheduler dependency

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Grafana is overwriting the label in the ui and we still have to add the label by hand.
=> Fix issue with datasource labels in grafana dashboard

.rhcicd/clowdapp-backend.yaml
=> Remove env vars used for the Clowder prod migration

backend/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java
Our logs currently contain the HTTP status of each webhook call but when something is wrong we have no way to determine which host failed from the logs. This PR will change that.
=> Log webhook target host

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
- Fixed some titles
- Added some descriptions
- Used stacked when it made sense
- Separated metrics for applications of same name (different bundles, like RHEL Advisor and OpenShift Advisor)
- Fix number of restarts charts
=> Several changes in the Grafana dashboard

.rhcicd/clowdapp-backend.yaml
`web` is deprecated and [will go away](https://docs.google.com/document/d/1m_MgEhZjb-z-bE8RbTrii559e9Sb3yS7P3gYsqAwveI/edit#).
We'll need to do the same for:
- https://github.com/RedHatInsights/notifications-gw/blob/main/.rhcicd/clowdapp.yaml
- https://github.com/RedHatInsights/policies-ui-backend/blob/master/.rhcicd/clowdapp.yaml#L27
- https://github.com/RedHatInsights/policies-engine/blob/master/.rhcicd/clowdapp.yaml#L47
But testing here before...
=> Updating Clowdapp

backend/helpers/send_notification.sh
Adds a helper script to help sending a notification. 
It's built to send a policy-triggered event-type from app Policies. 
Requires `jq` and `kafkacat`
=> Add helper to send notifications

backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EventLogEntry.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java
FYI we are loading the payload from the database even when it is not returned in the response, which is bad for performances.
I'll change that in another PR.
=> NOTIF-427 Return the payload on demand in the /events response

.rhcicd/clowdapp-backend.yaml, backend/pom.xml, backend/src/main/java/com/redhat/cloud/notifications/health/KafkaConsumedRateChecker.java, backend/src/main/java/com/redhat/cloud/notifications/health/LivenessService.java, backend/src/main/resources/application.properties
This adds a new check (disabled by default) to the existing health checks.
After a 5 minutes initial delay (configurable), every 1 minute (configurable) the `kafka.consumer.fetch.manager.records.consumed.rate` Micrometer gauge value will be tested.
A gauge value equal to zero will be recorded as a minor failure. If the number of _consecutive_ minor failures exceeds the maximum number allowed (configurable), then the app will be marked as `DOWN` the next time OpenShift calls `/health`.
If the gauge value is greater than zero when it is tested, the minor failures counter will be reseted.
=> Include Kafka records consumed rate in health check

backend/src/main/resources/db/migration/V1.34.0__NOTIF-410_events_response_time.sql
I expect this PR to have a major impact on the `/events` response time issue we currently have on prod. It may not fix it entirely though, we'll need to confirm that with tests on prod.
I created a local database similar to prod, with millions of `notification_history` and `event` records, which allowed me to reproduce the prod issue on my machine. Then I analyzed (with Postgres' `EXPLAIN`) and timed each SQL query involved during an `/events` call. I tested several fix candidates and this one had the bigger impact by far.
⚠️ This PR will remain a draft until `app-interface!31022` is merged. I need to know the exact numbers of rows on prod before I can determine the final `autovacuum` settings changes.
For more information about autovacuum tuning, here's an interesting article: …
=> NOTIF-410 Improve the /events response time

backend/src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/internal/RequestDefaultBehaviorGroupPropertyList.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java
- It doesn't make sense to specify a groupId in the default email action
as is not linked to any account
- Adds endpoint to query all the default behavior groups
- Adding tests
=> Remove superflous property and adding get all defaults behaviorgroups

.rhcicd/clowdapp-aggregator.yaml
- Ephemeral environment doesn't have a Prometheus Push Gateway (yet?)
- I haven't checked that the code would work without it
=> Making Prometheus push gateway optional

backend/src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/EndpointEmailSubscriptionResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailSubscriptionRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventTypeRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/NotificationHistoryRepository.java, backend/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, backend/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, backend/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/FromCamelHistoryFillerTest.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
This is preparation work for the notifications-backend split. Step 1: DB resources.
I moved the DB methods that will be part of the future `notifications-engine` app to new classes.
I also changed the naming convention for the files responsible for the DB queries: they are now named `*Repository` instead of `*Resources` because that's what they are and also because `*Resource` is a name much more suitable IMO for a file containing REST operations. Opinions on this are welcome, it can be reverted very easily.
=> NOTIF-450 Split the ui-backend and engine DB resources

common/src/main/java/com/redhat/cloud/notifications/Dummy.java
`quarkus:dev` does not like dependencies on empty modules.
=> NOTIF-450 Add temp dummy class in common to fix quarkus:dev

backend/src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, backend/src/main/java/com/redhat/cloud/notifications/templates/BadRequestExceptionMapper.java, backend/src/main/java/com/redhat/cloud/notifications/templates/TemplateEngineClient.java, backend/src/main/java/com/redhat/cloud/notifications/templates/TemplateEngineResource.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java
This is preparation work for the notifications-backend split. Step 2: templates rendering.
To avoid having to share all templates-related classes and files (HTML) between `notifications-ui-backend` and `notifications-engine`, the engine will be solely responsible for rendering templates.
When `notifications-ui-backend` receives a REST request from the admin UI to render a template, that request will be forwarded to a `notifications-engine` REST endpoint (`TemplateEngineResource`) that will perform the rendering and return the result.
=> NOTIF-450 Decouple the templates rendering from notifications-ui-backend

backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/PoliciesEmailPayloadAggregator.java, backend/src/main/java/com/redhat/cloud/notifications/recipients/RecipientResolver.java, backend/src/main/java/com/redhat/cloud/notifications/recipients/RecipientSettings.java, backend/src/main/java/com/redhat/cloud/notifications/recipients/request/ActionRecipientSettings.java, backend/src/main/java/com/redhat/cloud/notifications/recipients/request/EndpointRecipientSettings.java, backend/src/test/java/com/redhat/cloud/notifications/recipients/RecipientResolverTest.java, pom.xml
Allows notification message to specify a list of users.
This allows an applications to specify users they want to send a specific notification. This list of users is added to whatever the notification administrator already set and does not overwrite the setting.
=> NOTIF-152 Add recipient users

.rhcicd/clowdapp-aggregator.yaml, aggregator/pom.xml, aggregator/src/main/java/com/redhat/cloud/notifications/NotificationsApp.java, aggregator/src/main/resources/application.properties
Apparently all config keys starting with `quarkus.http` are no longer supported if the Quarkus app does depend on an HTTP-related extension. We received an alert on Sentry from stage because of that.
=> Remove HTTP config keys from aggregator

.rhcicd/clowdapp-backend.yaml
Fixes
```
11:47:34 2022-01-25 10:47:34 [    INFO] [           pid-26005]  |stderr| W0125 10:47:34.765681   26005 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
=> Fix deprecated CronJob apiVersion

.rhcicd/clowdapp-engine.yaml
Two DB pods are currently deployed on ephemeral because `sharedDbAppName` in missing in the `engine` template.
=> NOTIF-450 Share the DB pod between backend and engine

engine/src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java
Copied from [policies-engine](https://github.com/RedHatInsights/policies-engine/blob/master/external/src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java) which was successfully tested on `fedramp-stage` with SASL enabled.
=> Init Kafka SASL config using Clowder

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml, .rhcicd/pr_check_backend.sh
This will be needed as soon as the `engine` becomes responsible for rendering all templates.
=> NOTIF-450 Make the backend ClowdApp depend on engine

engine/src/main/resources/application.properties
Fixes
```
Unrecognized configuration key "quarkus.datasource.jdbc" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
=> NOTIF-450 Fix Sentry warning

.rhcicd/clowdapp-backend.yaml
Since the `engine` hasn't been deployed yet on prod, the ClowdApp dependency has to be optional. Otherwise, we can't deploy the `backend` on prod.
=> Make notifications-engine ClowdApp dependency optional

backend/src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/Query.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EventLogEntryAction.java, backend/src/test/java/com/redhat/cloud/notifications/db/EndpointResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/builder/QueryBuilderTest.java, backend/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/BasicAuthentication.java, common/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/CompositeEndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, common/src/main/java/com/redhat/cloud/notifications/models/EndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, database/src/main/resources/db/migration/V1.37.0__add_subtype_to_endpoint.sql, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java
Exposes subtypes in the `Endpoint`. This allows to better filter the camel related subtypes to show in the UI
With this new addition, the `subType` is expected on the `Endpoint` level, for backwards compatibility, we are going to keep it on the Camel for a short time to allow migrations. 
The filter now accepts the subtypes of a specifc type separated by a colon i.e. `camel:splunk`
```
GET /api/integrations/v1.0/endpoints?limit=10&offset=0&type=webhook&type=camel%3Asplunk&type=camel%3Aanycamel
```
It has some backwards compatbility changes. We still have the `sub_type` on `CamelProperties` but it's readonly and backed by the endpoint.sub_type.
Includes work of: https://github.com/RedHatInsights/notifications-backend/pull/892
=> NOTIF-429 Expose subtypes

.rhcicd/pr_check_backend.sh
The number of our transitive Clowder dependencies increased on ephemeral and it causes frequent PR check failures, so we need to increase the deployment timeout.
=> Increase bonfire deployment timeout on ephemeral

database/src/main/resources/db/migration/V1.37.0__add_subtype_to_endpoint.sql
That query caused a lock on stage twice because of the huge amount of history data.
If possible, it would be safer to remove it and wait for the `notification_history` table to be filled with records containing the subtype, which should take 31 days after the endpoints subtype code deployment.
=> Remove endpoints subtype migration query

database/src/main/resources/db/migration/V1.38.0__notification_history_index.sql
This PR should hopefully speed up the query that is causing issues on stage with the QA account.
It will have an impact on this part of the code:
https://github.com/RedHatInsights/notifications-backend/blob/dd67d02115c1a661bb174dc262050a8d2eb4cdf3/backend/src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java#L25-L56
See https://www.postgresql.org/docs/13/indexes-ordering.html for more details about the impact of indexes on sorting operations.
=> NOTIF-483 Speed up the last connection attempt frontend query

.rhcicd/clowdapp-engine.yaml
This should fix:
```
[2022-02-10 17:04:55] [ERROR] [openshift_base.py:_realize_resource_data:474] - [crcs02ue1/notifications-stage] [https://api.crcs02ue1.urby.p1.openshiftapps.com:6443/]: The ClowdApp "notifications-engine" is invalid: spec.deployments.podSpec.volumeMounts.mountPath: Required value
(error details: https://github.com/RedHatInsights/notifications-backend/blob/fa551d53b8edf40993115bda269cabc8fa0dcc99/.rhcicd/clowdapp-engine.yaml)
```
=> Fix mount path typo

backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java
This PR is based on the results from the analysis described in [NOTIF-491](https://issues.redhat.com/browse/NOTIF-491).
Postgre's `EXPLAIN ANALYZE` showed that half of the DB time was spent retrieving the events identifiers and the other half was spent counting the events. This PR merges these two operations into a single one, thanks to Postgre's `COUNT(*) OVER()` [window function](https://www.postgresql.org/docs/13/tutorial-window.html). When used in a limited query, that function returns the total count of records that would have been returned without the limit.
Hopefully, this will have some kind of impact on prod...
=> NOTIF-491 Merge getEventIds and count SQL queries

backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java
This is a new attempt at improving the response time of the `GET /events` endpoint.
Last week, we deployed on stage a version with modified SQL queries (#987) but the results were really bad so that PR was reverted.
Log entries showed that we spend a significant amount of time outside of Postgres, so I am now focusing on Jackson's serialization time. Since we return the events and their actions in a single response, the important data volume could cause a slow serialization.
Depending on the results of this PR, we may split the `/events` endpoint into two endpoints:
- one would still return the events **_without_** the actions
- the other one would take an events identifiers list and return the corresponding actions
=> NOTIF-491 Return events actions on demand

database/src/main/resources/db/migration/V1.40.0__events_order_by_indexes.sql
This PR takes advantage of [Postgres' index-only scans](https://www.postgresql.org/docs/13/indexes-index-only-scans.html) for the `event` table.
When all columns (selected or filtered on) from a query are available in the index, Postgres can return a result without using the indexed table at all. Otherwise, Postgres first identifies candidate rows in the index, then checks if they are still alive and finally retrieves the data from the indexed table.
=> NOTIF-491 Allow index-only scan in the events table

backend/src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java, common/src/main/java/com/redhat/cloud/notifications/StartupUtils.java
@dgaikwad With this PR, `GET /internal/version` will return the Git commit short hash that can be used to identify the version of the code that is tested.
For example, the endpoint could return `3b2e51c` which would identify https://github.com/RedHatInsights/notifications-backend/commit/3b2e51c. This short hash is also the tag of the Docker image we push on [Quay](https://quay.io/repository/cloudservices/notifications-backend?tab=tags).
=> Expose Git commit hash with /internal/version

backend/src/main/java/com/redhat/cloud/notifications/health/LivenessService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/HealthCheckTest.java, engine/src/main/java/com/redhat/cloud/notifications/health/LivenessService.java
`SELECT * FROM pg_stat_activity` shows that 6 `SELECT 1` queries are executed each second on stage. This puts a lot of pressure on the datasource connection pool for nothing.
Our query isn't needed because Quarkus already runs it. Removing it will decrease the number from 6 to 3 on stage.
~The 6 queries on stage come from 3 different IP addresses. We could try to understand why 3 machines are calling our `/health` each second, but that will be for another time.~ That's actually one query per replica which is totally normal 😄
=> NOTIF-491 Remove duplicate DB health check

.rhcicd/clowdapp-backend.yaml, database/src/main/resources/db/migration/V1.41.0__NOTIF-491_autovacuum_settings.sql, database/src/main/resources/db/migration/V1.42.0__NOTIF-491_initial_manual_vacuum.sql
The following results from the investigation conducted with `gabi` on stage.
`EXPLAIN ANALYZE` on the `COUNT(*)` query from the `/events` endpoint showed that Postgres is sometimes unable to perform [index-only scans](https://www.postgresql.org/docs/13/indexes-index-only-scans.html) during that query because it has to fetch records that have been deleted by the DB cleaning cron job.
```
EXPLAIN ANALYZE SELECT COUNT(*) FROM event e...
[...]
->  Index Only Scan using ix_event_service_index_only_scan_desc on event e  (cost=0.42..8138.76 rows=31651 width=16) (actual time=16.074..26.006 rows=3446 loops=11)
Index Cond: ((account_id = 'HIDDEN'::text) AND (created >= '2022-02-03 00:00:00'::timestamp without time zone) AND (created <= '2022-02-10 00:00:00'::timestamp without time zone) AND …
```
=> NOTIF-491 Change events purge and vacuum strategy

.rhcicd/clowdapp-backend.yaml, backend/src/main/java/com/redhat/cloud/notifications/db/DenormalizedEventsMigrationService.java, backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/Event.java, database/src/main/resources/db/migration/V1.43.0__NOTIF-491_denormalize_events.sql, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EventTypeRepository.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
This PR adds a new (and disabled by default) way to retrieve the events data from the DB. The `event` table now contains denormalized data that can be used to answer to `GET /events` requests.
If `notifications.event-service.use-denormalized-events` is `true`, then the denormalized data will be used. Otherwise, the old normalized data will be used.
A data migration is required for the events that already exist in the DB. I expect it to be quite long which is why I didn't put that migration in a Flyway script. It will be run from an internal REST request instead.
Both the PR and the data migration can be easily reverted in case something goes wrong or if the performance impact isn't good enough.
@josejulio Let's try this on stage 😃
=> NOTIF-491 Denormalize events

backend/src/main/java/com/redhat/cloud/notifications/db/EventResources.java, common/src/main/java/com/redhat/cloud/notifications/models/Event.java
I just realized we could get rid of the `DATE()` function is `/events` SQL queries. That function is slowing things down so it's better if we remove it.
=> NOTIF-491 Remove date conversion function in SQL queries

.rhcicd/clowdapp-backend.yaml
Temporary commit.
The pod is killed on prod before it's done migrating the DB.
=> Increase backend probes initial delay

.rhcicd/clowdapp-backend.yaml
Prod has been deployed. We can go back to the old probes values.
=> Revert "Increase backend probes initial delay (#1013)"

engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacServiceToService.java
Stage is broken because of a `BlockingNotAllowedException` when the RBAC rest client is invoked.
=> NOTIF-488 Add @Blocking to RBAC rest client methods

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepository.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepositoryTest.java
This should fix the following issue on stage:
```
2022-03-09 05:00:15,579 INFO  [com.red.clo.not.pro.ema.EmailSubscriptionTypeProcessor] (vert.x-eventloop-thread-0) Error while processing aggregation: javax.persistence.TransactionRequiredException: Executing an update/delete query
at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:431)
at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1692)
at com.redhat.cloud.notifications.db.repositories.EmailAggregationRepository.purgeOldAggregation(EmailAggregationRepository.java:50)
```
=> NOTIF-488 Make the aggregation purge query transactional

engine/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
#1033 fixed one issue and revealed another one:
```
2022-03-09 10:00:25,548 DEBUG [com.red.clo.not.pro.web.WebhookTypeProcessor] (vert.x-eventloop-thread-0) Failed: The current thread cannot be blocked: vert.x-eventloop-thread-0
2022-03-09 10:00:25,549 INFO [com.red.clo.not.pro.ema.EmailSubscriptionTypeProcessor] (vert.x-eventloop-thread-0) Error while processing aggregation: io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread.
```
=> NOTIF-488 Make all Kafka messages processing methods blocking

engine/src/main/resources/application.properties
See [this](https://github.com/quarkusio/quarkus/blob/03746b894bcdf9b83f12c7ab77ebd4bc2c0d52ec/extensions/resteasy-reactive/rest-client-reactive/runtime/src/main/java/io/quarkus/rest/client/reactive/runtime/RestClientCDIDelegateBuilder.java#L219-L239).
=> Fix keystore location for MP rest-client

backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/MicrometerAssertionHelper.java, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, pom.xml
`5.11.2` didn't work well but let's see how it goes with `5.12.0`.
=> Bump mockserver-client-java to 5.13.0

common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeEventService.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java
A list that should be `[]` was becoming a Json-Object with `"list": [...]`
=> Use a JsonObject as argument and not a Map, as the Map is serialised in an odd way

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleAuthMechanism.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalPermissionService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/InternalUserPermissions.java, backend/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/InternalPermissionsServiceTest.java
Adds the `roles` an user has to the `/access/me` response.
This will allow the UI to present some roles the user can access, to make it easier to create the applications.
=> NOTIF-482 Add roles to access/me response

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/ComplianceEmailAggregator.java, engine/src/test/java/com/redhat/cloud/notifications/ComplianceTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/ComplianceEmailAggregatorTest.java
From the test output:
```json
{
"compliance": {
"report-upload-failed": [
{
"policy_condition": "not-used-condition",
"policy_description": "not-used-desc",
"policy_id": "policy1",
"policy_name": "not-tested-name"
},
{
"policy_condition": "not-used-condition",
"policy_description": "not-used-desc",
"policy_id": "policy2",
"policy_name": "not-tested-name"
}
],
"compliance-below-threshold": [
{
"policy_condition": "not-used-condition",
"policy_description": "not-used-desc",
"policy_id": "policy3",
"policy_name": "not-tested-name"
},
{
"policy_condition": "not-used-condition",
"policy_description": "not-used-desc",
"policy_id": "policy4",
"policy_name": "not-tested-name"
}
]
},
"start_time": null,
"end_time": null
}
```
=> RHICOMPL-2763: implemented the compliance aggregator

.rhcicd/clowdapp-engine.yaml
This should help fixing the following issue:
```
{"@timestamp":"2022-03-27T00:02:18.509Z", "log.level": "INFO", "message":"SRHCK01001: Reporting health down status: {\"status\":\"DOWN\",\"checks\":[{\"name\":\"SmallRye Reactive Messaging - liveness check\",\"status\":\"DOWN\",\"data\":{\"fromCamel\":\"[OK]\",\"ingress\":\"[OK]\",\"aggregation\":\"[KO] - The record 2461 from topic/partition 'platform.notifications.aggregation-0' has waited for 64 seconds to be acknowledged. At the moment 1 messages from this partition are awaiting acknowledgement. The last committed offset for this partition was 2460.\",\"toCamel\":\"[OK]\",\"egress\":\"[OK]\"}},{\"name\":\"Notifications liveness check\",\"status\":\"UP\"}]}", "service.environment":"prod","process.thread.name":"executor-thread-750","log.log …
```
=> Make Kafka messages max age configurable for aggregation channel

common/src/test/java/com/redhat/cloud/notifications/MockServerLifecycleManager.java, pom.xml
It looks like we're still stuck with `mockserver-client-java 5.5.4`... I'll keep looking for a way to use the latest version, but in the meantime this PR will fix the current instabilities.
=> Downgrade mockserver to 5.5.4

engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProviderTest.java
If the group no longer exists, just ignore it.
Now that we are going to accept groups, they could be deleted without us noticing it. So instead of failing, lets just ignore it.
=> NOTIF-347 Check if the group exists

database/src/main/resources/db/migration/V1.48.0__NOTIF-484_template_name_unique.sql, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/templates/DbTemplateLocator.java, engine/src/main/java/com/redhat/cloud/notifications/templates/TemplateEngineResource.java, engine/src/main/java/com/redhat/cloud/notifications/templates/TemplateService.java, engine/src/main/java/com/redhat/cloud/notifications/templates/extensions/LocalDateTimeExtension.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/TemplateRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java
This PR is necessary to allow the injection of a DB template into another DB template.
Outer template:
```
Hello, {#include inner-template /}
```
Inner template:
```
World!
```
Rendering outcome:
```
Hello, World!
```
It is based on [this part](https://quarkus.io/guides/qute-reference#standalone) of the Qute doc.
ℹ️ This PR has not impact on prod. It can be safely merged.
=> NOTIF-484 Render DB templates with standalone Qute engine

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java, backend/src/main/java/com/redhat/cloud/notifications/auth/principal/ConsoleIdentity.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacGroup.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacGroupValidator.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacServer.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/RequestEmailSubscriptionProperties.java, backend/src/test/java/com/redhat/cloud/notifications/MockServerConfig.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Requires doing a validation with rbac to confirm the group id really exists.
We might need a way to delete rbac groups that are deleted.
=> NOTIF-347 Allow to create endpoints with rbac groups

engine/src/main/java/com/redhat/cloud/notifications/templates/Rbac.java
I noticed that while working on the DB templates migration.
=> Fix RBAC email template title selection

.rhcicd/clowdapp-backend.yaml
Adds `apiPath` to fix frontend <--> backend networking in Ingress. Without this field, Clowder will use the app name `notifications-backend-service` by default.
=> Support external API path for frontend

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/AdminResource.java, backend/src/main/java/com/redhat/cloud/notifications/templates/TemplateEngineClient.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java
- The migration will be triggered with a REST call to `/internal/admin/templates/migrate`.
- `backend` is exposing the migration endpoint and forwarding the request to `engine` which does the actual migration work.
- We can run the migration multiple times. If a template was previously migrated, it won't be changed by a new run.
- The DB templates can be wiped if there's a problem with the migration result on stage, allowing multiple attempts if necessary.
- ℹ️ As usual, this PR does not affect prod.
=> NOTIF-484 Introduce templates migration service

common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeHelper.java
Getting the AuthToken must be request scoped, as it would otherwise not expire locally, but in OpenBridge.
As it is currently CDI is sort of caching the token forever.
=> Getting the AuthToken must be request scoped

backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java
We received a Sentry alert on stage about the following exception:
```
java.lang.NullPointerException: null
at com.redhat.cloud.notifications.routers.NotificationResource.updateEventTypeBehaviors(NotificationResource.java:238)
```
This PR replaces the exception with a proper HTTP 400 status code.
=> Fix NPE in notifications REST API

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java
This PR should fix the following exception which reached our Sentry channel on stage:
```
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:221)
at java.util.ImmutableCollections$AbstractImmutableList.indexOf(ImmutableCollections.java:170)
at java.util.ImmutableCollections$AbstractImmutableList.contains(ImmutableCollections.java:201)
at com.redhat.cloud.notifications.routers.EndpointResource.checkSystemEndpoint(EndpointResource.java:447)
at com.redhat.cloud.notifications.routers.EndpointResource.deleteEndpoint(EndpointResource.java:269)
```
ℹ️ I checked the DB with `gabi`, all endpoints have a non-null `endpoint_type` field on stage.
=> Fix NPE in endpoints REST API

engine/src/main/java/com/redhat/cloud/notifications/templates/DbTemplateLocator.java, engine/src/main/java/com/redhat/cloud/notifications/templates/TemplateService.java, engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java
As discussed on Slack, this PR introduces a scheduled job which periodically clears all templates for the Qute internal cache.
=> NOTIF-484 Clear Qute templates cache periodically

README.adoc, backend/pom.xml, backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/pom.xml, common/src/test/java/com/redhat/cloud/notifications/MockServerLifecycleManager.java, engine/pom.xml, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java, pom.xml
Our build is unstable on GitHub when the `mockserver-client-java` version is higher than `5.5.4`.
This branch will be used to try and stabilize the build with the latest mockserver version.
=> Bump MockServer to 5.13.2

engine/src/main/java/com/redhat/cloud/notifications/recipients/RecipientResolver.java
coming from a discussion with @josejulio some minutes ago. We would like to get to know how many users we are fetching from IT User Service and how many of them we are actually using after fetching. With this gauge we can compare both.
=> Add gauge for the actual count of users used

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/CompositeEndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, database/src/main/resources/db/migration/V1.49.0__NOTIF-324_ensure-subtypes-are-lower-case.sql
There is a PR to add some filters on the frontend - one of these is the Splunk integration, which is of type camel and subtype splunk. 
Before this PR, EventLog API did not support searching for sub_types. This PR enables searching for type with optional subtypes.
=> NOTIF-324 Allow to filter events by composite types

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java
`IS TRUE` should always be preferred over `= TRUE`:
| Field value | `= TRUE` evaluation result | `IS TRUE` evaluation result |
| - | - | - |
| null | null | false |
| true | true | true |
| false | false | false |
=> Fix SQL endpoint queries conditions

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
The endpoints when passed an invalid ID with the correct "ID" format return an empty list with a 200 status code. should return a 404 "Not Found" exception.
=> NOTIF-628 Return 404 when id not found

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/MicrometerAssertionHelper.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java
Metrics after sending 2 events to slack
```
processor_camel_processed_total{subType="slack",} 2.0
```
Not sure why there is an additional `,` in the output, but that is what `curl localhost:8087/metrics | grep processor  ` shows
=> NOTIF-646 Emit Camel metrics with subtype as tag.

checkstyle/src/main/resources/checkstyle/checkstyle.xml
This is to help developers to make sure the Jupiter `@Test` is used and not the one from Junit4
=> Put old Junit 4 Test annotation on the forbidden list.

engine/src/main/resources/templates/Rbac/insightsEmailBody.html
The preprod image url will not work because google will proxy the url
in email and will not show the logo image.
=> Use prod image url

engine/src/main/java/com/redhat/cloud/notifications/recipients/itservice/pojo/request/AllOf.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/itservice/pojo/request/ITUserRequest.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/itservice/pojo/request/AllOfTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/itservice/pojo/request/ITUserRequestTest.java
It's still a pita to get a certificate, but we will have to do the change of the query anyway. I could not integration test (only comparing sample requests so far) the new query against the real IT User Service API for now.
=> NOTIF-603 Add orgId to IT User Service requests

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java
Not needed, and may lead to confusion later
=> Reverting OpenAPI schema change

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/NotificationRepository.java
Fixes
```
2022-05-23 12:29:43,312 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-13) HTTP Request to /api/integrations/v1.0/endpoints/c0e716da-3641-49cc-8cd2-5bec8eb6f17d/history/7832943c-5064-4c0d-8d40-1c45e251b42f/details failed, error id: e403de80-6246-4614-b62a-d623979e15f0-1: java.lang.NullPointerException
at io.vertx.core.json.JsonObject.<init>(JsonObject.java:71)
at com.redhat.cloud.notifications.db.repositories.NotificationRepository.getNotificationDetails(NotificationRepository.java:66)
at com.redhat.cloud.notifications.db.repositories.NotificationRepository_ClientProxy.getNotificationDetails(Unknown Source)
at com.redhat.cloud.notifications.routers.EndpointResource.getDetailedEndpointHistory(EndpointResource.java:381)
at …
```
=> Fix NPE in NotificationRepository

backend/src/main/java/com/redhat/cloud/notifications/db/Query.java
The hyphen character doesn't work out of the box with Postgres and our code does not include the small details that could make it work.
This change will prevent some Sentry alerts we got over last night because of illegal SQL queries.
=> Reject hyphen in sort_by filtering param

.rhcicd/clowdapp-aggregator.yaml, .rhcicd/clowdapp-backend.yaml
This will finally ensure that both cronjobs meet the serviceaccount and annotation requirement (now managed by clowder), so the alerts will clean up in dashdb, and onboarding can progress
=> Clowdappizing the cronjob

backend/src/main/java/com/redhat/cloud/notifications/routers/NotFoundExceptionMapper.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/TemplateResource.java, backend/src/test/java/com/redhat/cloud/notifications/CrudTestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
- Adding NotFoundExceptionMapper to ensure NFE are always plain text
- Specify the 404 state of the template in the openapi
=> API fixes to templates/email/instant/eventType/{eventTypeId}

engine/src/main/java/com/redhat/cloud/notifications/templates/models/Environment.java, engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailBody.html, engine/src/main/resources/templates/Compliance/dailyEmailBody.html, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailBody.html, engine/src/main/resources/templates/EdgeManagement/insightsEmailBody.html, engine/src/main/resources/templates/Patch/dailyEmailBody.html, engine/src/main/resources/templates/Patch/newAdvisoriesInstantEmailBody.html, engine/src/main/resources/templates/Rbac/customGroupCreatedEmailBody.html, engine/src/main/resources/templates/Rbac/customGroupUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/customPlatformGroupUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/customRoleCreatedEmailBody.html, engine/src/main/resources/templates/Rbac/customRoleUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/insightsEmailBody.html, engine/src/main/resources/templates/Rbac/nonPlatformRoleUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/platformGroupToCustomEmailBody.html, engine/src/main/resources/templates/Rbac/platformRoleUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/roleAddedToPlatformGroupEmailBody.html, engine/src/main/resources/templates/Rbac/roleRemovedFromPlatformGroupEmailBody.html, engine/src/main/resources/templates/Rbac/systemRoleAvailableEmailBody.html, engine/src/main/resources/templates/Sources/availabilityStatusEmailBody.html, engine/src/main/resources/templates/Vulnerability/anyCveKnownExploitBody.html, engine/src/main/resources/templates/Vulnerability/dailyEmailBody.html, engine/src/main/resources/templates/Vulnerability/newCveCritSeverityEmailBody.html, engine/src/main/resources/templates/Vulnerability/newCveHighCvssEmailBody.html, engine/src/main/resources/templates/Vulnerability/newCveSecurityRuleBody.html, engine/src/test/java/com/redhat/cloud/notifications/templates/models/EnvironmentTest.java
- environment.url() no longer adds a trailing slash
- environment.url(string) no longer exists
- Updates all the templates to take into account the new usage.
These changes make it easier to read the templates (IMO).
A major problem with `environment.url(string)` is that it didn't allow to concatenate strings inside the method, thus:
`{environment.url('stuff/' + variable)}` would yield: `https://console.redhat.com/stuff/ + variable` (yes, literally that)
Users had to do: `{environment.url("stuff/")}{variable}` to get the desired output, which is harder to read and defeats the purpose of the argument anyway.
With the latest changes it can to be now: `{environment.url}/stuff/{variable}` which feels more natural.
This change was motivated by the review of …
=> Updating Enviroment.url methods from templates

pom.xml
1.0.1 has some issues - especially the log.type field is not populated in the provided config files and thus makes the evaluation of cloudwatch entries fail.
=> Roll back clowder config source to 1.0.0

engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java
It was useful to have, but now it adds extra cardinality and makes queries more complex when comparing accounts
=> Removing 'users' tag on rbac.get-users.total Prometheus metric

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java
This PR should fix the deadlock exceptions that happened on stage recently.
Check `Hide whitespace` for an easier review.
=> Lock data before updating ET behaviors and BG actions

engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java, pom.xml
Quarkus 2.10 wasn't the cause of the IQE tests instability on stage.
=> Bump Quarkus to 2.10.0.Final (again)

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java
Someone called `POST /api/notifications/v1.0/user-config/notification-preference?bundleName=rhel` on stage will a `null` request body which caused a NPE and an HTTP 500 status. After this PR, the returned HTTP status will be 400.
=> Prevent NPE in UserConfigResource

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacClientResponseFilter.java
This PR reduces the Sentry alerts from 3 to 1 when the RBAC calls fail because of a timeout or a closed connection.
=> Reduce RBAC failures noise in Sentry

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailSubscriptionRepository.java, common/src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, common/src/main/java/com/redhat/cloud/notifications/models/EmailSubscription.java, common/src/main/java/com/redhat/cloud/notifications/models/EmailSubscriptionId.java, common/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, database/src/main/resources/db/migration/V1.52.0__NOTIF-603_org_id.sql, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
#1271 is too big and hard to rebase, so I'm breaking it down into smaller PRs.
This is step 1: adding the `orgId` field to all  DB entities where it was missing.
=> NOTIF-603 Add orgId to DB entities

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregator.java, engine/src/main/resources/templates/Patch/dailyEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/PatchTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregatorTest.java
Patch was sending too much notifications and now is going to notify only once for each new advisory per account instead of system.
=> SPM-1485 Handle advisories uniquely per account in Patch aggregator

common/src/main/java/com/redhat/cloud/notifications/OrgIdHelper.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepository.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailSubscriptionRepository.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
#1271 is too big and hard to rebase, so I'm breaking it down into smaller PRs.
This is step 3: introducing `orgId` in all notifications-engine repositories.
=> NOTIF-603 Introduce orgId in engine repositories

common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
```
2022-07-01 08:25:36,499 INFO  [com.red.clo.not.con.FeatureFlipper] (main) === FeatureFlipper startup status ===
2022-07-01 08:25:36,499 INFO  [com.red.clo.not.con.FeatureFlipper] (main) The behavior groups unique name constraint is disabled
2022-07-01 08:25:36,499 INFO  [com.red.clo.not.con.FeatureFlipper] (main) The RHOSE (OpenBridge) integration is disabled
2022-07-01 08:25:36,499 INFO  [com.red.clo.not.con.FeatureFlipper] (main) The actions reinjection in case of Camel integration error is disabled
2022-07-01 08:25:36,499 INFO  [com.red.clo.not.con.FeatureFlipper] (main) The Kafka outage detector is disabled
2022-07-01 08:25:36,500 INFO  [com.red.clo.not.con.FeatureFlipper] (main) The org ID migration is disabled
```
=> Log features status at application startup

engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java, pom.xml
Quarkus 2.10.0.Final is not the cause of the memory leak.
=> Revert "Downgrade Quarkus to 2.9.2.Final (#1334)"

aggregator/src/test/java/com/redhat/cloud/notifications/helpers/TestHelpers.java, engine/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, engine/src/main/java/com/redhat/cloud/notifications/models/EmailAggregationKey.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/AbstractEmailPayloadAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/transformers/BaseTransformer.java, engine/src/test/java/com/redhat/cloud/notifications/ComplianceTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/DriftTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/PatchTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/VulnerabilityTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/ComplianceEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/DriftEmailPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/PoliciesEmailPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/VulnerabilityEmailPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java, engine/src/test/java/com/redhat/cloud/notifications/transformers/BaseTransformerTest.java
This PR adds the `orgId` in most places where it was missing in `notifications-engine`.
After that, `CamelTypeProcessor` should be the only class where the `orgId` is missing. As explained below, it will be updated separately.
=> NOTIF-603 Polish the orgId migration in engine

backend/src/main/java/com/redhat/cloud/notifications/auth/principal/rhid/RhIdPrincipal.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailSubscriptionRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/NotificationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/TemplateRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/SecurityContextUtil.java, backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/IntegrationTemplateRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/IntegrationTemplate.java, database/src/main/resources/db/migration/V1.54.0__NOTIF-603_integration_template_org_id.sql
All the `backend` tests still rely on the `accountId`. I'm not sure of the most reasonable approach regarding the `orgId` integration into tests. This is gonna be painful.
Anyway the `orgId` is disabled for now so let's move forward and start by merging this.
=> NOTIF-603 Add orgId to DB repositories and REST resources

aggregator/src/main/java/com/redhat/cloud/notifications/DailyEmailAggregationJob.java, aggregator/src/test/java/com/redhat/cloud/notifications/helpers/BaseTransformer.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/IntegrationTemplateRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/AuthenticationTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/InternalResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/ValidationResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/InternalPermissionsServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/TemplateResourceTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/FromCamelHistoryFillerTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java
After this PR, most of the notifications tests will be run twice:
- with `notifications.use-org-id=false`
- with `notifications.use-org-id=true`
The test code is almost unchanged and there is only one runtime code change highlighted below.
=> NOTIF-603 Add orgId tests

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
`GET /events` cannot rely on the `org_id` that comes from the user authentication headers yet because some onboarded apps still send Kafka messages without an `org_id` value. If we want these messages to be returned by `/events`, then we need to retrieve all events from the DB using the `account_id` for now.
`notifications.use-org-id` will be set to `true` shortly on stage and prod.
`notifications.events.use-org-id` will be set to `true` a bit later when all the Kafka messages we receive will contain an `org_id`.
=> NOTIF-603 Add dedicated orgId feature flag for /events

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/CreateBehaviorGroupRequest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/CreateBehaviorGroupResponse.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/UpdateBehaviorGroupRequest.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
The create behavior group (and the update) will now accept the eventTypes(ids) and endpoints(ids) properties.
If these are provided (not null) the create event will create all the required relations.
For the update, it will act as a "set" and the backend will remove current relations that were not specified in the current request and add those that were not currently set.
New request objects were created to make the request explicit on what is expecting, instead of relaying on guessing if the attributes of the BehaviorGroup are used in the request or not.
=> Saving behavior group actions and linked event types in a single call

database/src/main/resources/db/migration/V1.55.0__NOTIF-603_email_subscriptions_org_id.sql, database/src/main/resources/db/migration/V1.55.1__NOTIF-603__split_dml_ddl.sql
Same SQL instructions than before, but the `endpoint_email_subscriptions` PK removal is now done before any other migration query is executed.
That PK caused the following error on stage:
```
2022-07-13 08:21:15,481 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.postgresql.util.PSQLException: ERROR: null value in column "org_id" violates not-null constraint
```
=> NOTIF-603 Remove endpoint_email_subscriptions PK before updating data

.rhcicd/stage-post-deployment-tests.yaml
For now, let's use clowder smoke env.
We need further investigation into why in ephemeral env we are not able to authenticate with stage user and now changes for default user iqe-core need to apply in all other dependent plugins.
=> use clowder_smoke env

.rhcicd/stage-post-deployment-tests.yaml
reverting my changes: https://github.com/RedHatInsights/notifications-backend/pull/1368
clowder smoke env user not applicable for stage env so lets try to fix stage_post_deploy env only
=> [NOTIF-716] Revert stage post deployment env

admin-console/src/main/webapp/src/pages/ApplicationPage.tsx
At some point we reverted it back (I assume while fixing a conflict).
This PR uses the EventTypeTable again.
=> Using the EventTypeTable component again

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java
No other effect than letting us know that we are using org ids and not account ids.
=> Fixes the names on the log when using org id

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/test/java/com/redhat/cloud/notifications/MicrometerAssertionHelper.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
This PR should help us identify which onboarded apps do not send the `org_id` field yet.
The counter is now incremented even if the org ID is disabled.
=> Add bundle and app to the input.missing.orgid metric

checkstyle/pom.xml, common/pom.xml, pom.xml
Basically Level 1 of https://github.com/rfichtner/maven-survival-guide
We (only) require Maven 3.8.1 as Quarkus uses that version. Locally it works well with 3.8.6
=> Pom updates for a more reproducible build

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/Bop.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/OrgIdTranslator.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/MockServerConfig.java, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
The translation is disabled by default and can be enabled with `notifications.translate-account-id-to-org-id=true`.
If the call to BOP fails for any reason, the Kafka message processing will continue (with a missing org ID) and a warn message will be logged and trigger a Sentry alert.
Org IDs are cached indefinitely because the translation result never changes for a given EAN.
=> NOTIF-744 Translate account_id to org_id using BOP

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/ITUserServiceV2.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/OrgIdRequest.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/OrgIdRequestBy.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/OrgIdResponse.java, engine/src/main/java/com/redhat/cloud/notifications/events/orgid/OrgIdTranslator.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/MockServerConfig.java, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
Calling BOP to translate an `account_id` to an `org_id` didn't work on stage because of certificate issues.
This PR replaces the BOP call with an IT users service call, which should work because we already configured the certificate for that service. I reverse engineered BOP to determine how to call the IT users service and translate the `account_id`. It may not work on first try but it's still disabled by default with the feature flag so it won't do any harm.
=> NOTIF-744 Replace BOP with IT users service

engine/src/main/java/com/redhat/cloud/notifications/recipients/itservice/ITUserService.java, engine/src/main/resources/application.properties
I just noticed that the IT users service configuration was a bit "unusual" and because of that the new service that translates `account_id` to `org_id` didn't work. Things should work better after this PR.
=> NOTIF-744 Clean up IT users service configuration

database/src/main/resources/db/migration/V1.56.0__purge_email_aggregation.sql
Because of the EAN to OrgID migration, I took a look using `gabi` at the `email_aggregation` table on prod and noticed that we have a lot of records that have been stuck for almost two months there:
```
Query: select count(*) from email_aggregation where created < '2022-08-01'
Result: 262363
```
The aggregated data got stuck between June 23rd and July 21st:
```
Query: select min(created) from email_aggregation where created < '2022-08-01'
Result: 2022-06-23T00:01:11.21142Z
Query: select max(created) from email_aggregation where created < '2022-08-01'
Result: 2022-07-21T23:28:07.344388Z
```
That data came almost exclusively from the QA account: (:warning: Sensitive data hidden on purpose :warning:)
```
Query: select account_id, count(*) from email_aggregation where created < '2022-08-01' …
```
=> Purge old data in email_aggregation

.rhcicd/clowdapp-backend.yaml
`ANALYZE` updates Postgres' optimizer statistics. The query planner can only work better after that.
I don't know why I didn't add it to the cronjob initially. We already used `VACUUM ANALYZE` from Flyway scripts in the past.
=> Run ANALYZE after daily VACUUM

aggregator/src/test/java/com/redhat/cloud/notifications/db/EmailAggregationResourcesTest.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailSubscriptionRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/EventsMigrationResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/EmailSubscription.java, common/src/main/java/com/redhat/cloud/notifications/models/EmailSubscriptionId.java, database/src/main/resources/db/migration/V1.58.0__NOTIF-603_anemic_tenants.sql, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailSubscriptionRepository.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepositoryTest.java
Depends on #1354.
:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning:
This PR must be merged after #1354 and after the Event Log has been successfully tested with `NOTIFICATIONS_EVENTS_USE_ORG_ID=true` on prod.
:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning:
This change is required to make the app compatible with anemic tenants.
=> NOTIF-603 Make Org ID mandatory and account optional in DB

.rhcicd/clowdapp-backend.yaml
The [big DB migration](https://github.com/RedHatInsights/notifications-backend/pull/1354) is done, we don't need huge failure thresholds anymore.
=> NOTIF-603 Restore initial probes failure thresholds

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java
Remove (from user preferences) applications  that don't have any valid option.
e.g. We want to stop showing empty applications here such as `Storage broker` or `Internal`:
=> Remove unavailable settings from user preferences call

common/src/main/java/com/redhat/cloud/notifications/models/Event.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, pom.xml
Uses the version 0.16 of the schema, where the `account_id` can be the null value in the json string 
In a JSON a property can be `null`, `undefined` (explicitely or by not being present) or have other value. The java implementation considers a null java values for both the received `undefined` and `null` json values.
The only limitation is that `account_id` now is a java `Object` (by the way the json schema was made and maybe my poor knowledge of it, see [here](https://github.com/RedHatInsights/insights-schemas-java/pull/59))
=> Support for account_id being null in the json string

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java
`iqe-notifications-plugin` can no longer parse the response of that REST endpoint. The recent changes from #1427 probably caused that issue.
=> NOTIF-753 Fix POST /endpoints OpenAPI definition

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/TemplateRepository.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Default.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/TemplateEngineResource.java, engine/src/main/java/com/redhat/cloud/notifications/templates/TemplateService.java, engine/src/main/java/com/redhat/cloud/notifications/templates/extensions/ActionExtension.java, engine/src/main/resources/templates/Default/instantEmailBody.html, engine/src/main/resources/templates/Default/instantEmailTitle.txt, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateFactoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestDefaultTemplate.java, engine/src/test/resources/qute/expected-pretty-json-action.json
Adds a new flag to decide if we use a default email template. This is meant for pre-production as it will include the json content of the notification.
The default email template is only going to be used if the application didn't provide (already) a template themselves.
Todo:
For a fake notification with bundle: `my-bundle`, application: `my-app` and event type: `test-email-subscription-instant`
The title is: `03 Aug 2020 15:22 UTC - my-bundle/my-app/test-email-subscription-instant triggered`
And the content of the email is:
=> NOTIF-181 Adding default template for preprod environments

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java, backend/src/main/java/com/redhat/cloud/notifications/auth/principal/ConsolePrincipalFactory.java, backend/src/main/java/com/redhat/cloud/notifications/auth/principal/IllegalIdentityHeaderException.java, backend/src/test/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProviderTest.java
If the `org_id` field is missing in the `x-rh-identity` header, the client will receive a 401 HTTP status in the response and an exception will be logged at `ERROR` level from this location:
https://github.com/RedHatInsights/notifications-backend/blob/5364662f96b485d735440c1373ddaa8b591196e5/backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java#L160-L164
```
2022-09-05 10:37:42,201 ERROR [com.red.clo.not.aut.ConsoleIdentityProvider] (vert.x-eventloop-thread-0) Error while processing identity: io.quarkus.security.AuthenticationFailedException
at com.redhat.cloud.notifications.auth.ConsoleIdentityProvider.lambda$authenticate$3(ConsoleIdentityProvider.java:115)
[...]
Caused by: com.redhat.cloud.notifications.auth.principal.IllegalIdentityHeaderException: The …
```
=> NOTIF-764 Return 401 when org_id is missing in the x-rh-identity header

engine/src/main/java/com/redhat/cloud/notifications/templates/Default.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
Checks if the wrapped email template is supported - if not, returns null.
Updated tests to reflect the actual use case (throws exceptions instead of returning null)
=> NOTIF-181 Check if the wrapped template supports the type

engine/src/main/resources/templates/Default/instantEmailBody.html, engine/src/main/resources/templates/Default/instantEmailTitle.txt
Content in context is free-form and depending the application - we cannot assume anything there.
=> NOTIF-181 Remove references to context in default templates

backend/src/main/resources/application.properties
I fixed several issues in `app-interface` and `do-nothing.yaml` files earlier today. The `notifications-stage-ref` pipeline run in Tekton is stuck with old notifications (backend/gw) commits for some reason so far. Let's see if a new commit will update the ref to the latest one.
=> Dummy commit to trigger a fresh deployment on stage

.rhcicd/do-nothing.yaml
Fixes:
```
error creating resource *v1.CronJob notifications-do-nothing-job-283be2b-do-nothing-backend: CronJob.batch "notifications-do-nothing-job-283be2b-do-nothing-backend" is invalid: metadata.name: Invalid value: "notifications-do-nothing-job-283be2b-do-nothing-backend": must be no more than 52 characters
```
=> Rename do-nothing ClowdApp and job

.rhcicd/do-nothing.yaml
`do-nothing` currently does even less than before (which was already nothing): the commits refs are not updated anymore in `stage-ref.yml`. Let's see if a job will work better than a cronjob.
=> Make do-nothing a job instead of a cronjob

.rhcicd/do-nothing.yaml
Making it a `job` wasn't a good idea 😄
=> Revert "Make do-nothing a job instead of a cronjob (#1474)"

.rhcicd/pr_check.sh, .rhcicd/pr_check_engine.sh
Until now, the `notifications-engine` version that was tested by the IQE plugin on ephemeral was not the latest one.
Things would be simpler if `backend` and `engine` were hosted in separate repos.
=> Run PR check with the latest engine image

database/src/main/resources/db/migration/v1.60.0__NOTIF-512_webhook_disabled_event_type.sql, engine/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, engine/src/main/java/com/redhat/cloud/notifications/events/IntegrationDisabledNotifier.java, engine/src/main/java/com/redhat/cloud/notifications/events/KafkaMessageWithIdBuilder.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/templates/ConsoleNotifications.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/application.properties, engine/src/main/resources/templates/ConsoleNotifications/insightsEmailBody.html, engine/src/main/resources/templates/ConsoleNotifications/integrationDisabledBody.html, engine/src/main/resources/templates/ConsoleNotifications/integrationDisabledTitle.txt, engine/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/events/IntegrationDisabledNotifierTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java
▶️ **Part 2 of NOTIF-512**
When a webhook is automatically disabled because of 4xx or 5xx failures, an action is emitted on the `platform.notifications.ingress` topic with the following information:
- bundle: `console`
- application: `notifications`
- event type: `integration-disabled`
The action also contains additional information about the issue:
- the endpoint ID and name
- the type of the error (client or server)
- the HTTP status in case of client error
- the number of errors in case of server errors
Using a default behavior group, the event type described above will be used to send an email notification to the org admins of the account that owns the disabled integration. The email body will vary depending on the type of the error.
=> NOTIF-512 Notify org admins when a webhook is disabled

engine/src/main/resources/templates/ConsoleNotifications/integrationDisabledTitle.txt
Fixes
```
io.quarkus.qute.TemplateException: Rendering error in template [ConsoleNotifications/integrationDisabledTitle.txt] line 1: Property "toUtcFormat" not found on the base object "null" in expression {action.context.system_check_in.toUtcFormat()}
```
=> Fix integration disabled template title

engine/src/main/resources/templates/Advisor/insightsEmailBody.html, engine/src/main/resources/templates/Advisor/newRecommendationInstantEmailBody.html, engine/src/main/resources/templates/Advisor/resolvedRecommendationInstantEmailBody.html, engine/src/main/resources/templates/AdvisorOpenshift/insightsEmailBody.html, engine/src/main/resources/templates/Ansible/insightsEmailBody.html, engine/src/main/resources/templates/Ansible/instantEmailBody.html, engine/src/main/resources/templates/Compliance/insightsEmailBody.html, engine/src/main/resources/templates/CostManagement/insightsEmailBody.html, engine/src/main/resources/templates/Drift/dailyEmailBody.html, engine/src/main/resources/templates/Drift/insightsEmailBody.html, engine/src/main/resources/templates/Drift/newBaselineDriftInstantEmailBody.html, engine/src/main/resources/templates/Inventory/insightsEmailBody.html, engine/src/main/resources/templates/Patch/insightsEmailBody.html, engine/src/main/resources/templates/Policies/dailyEmailBody.html, engine/src/main/resources/templates/Policies/insightsEmailBody.html, engine/src/main/resources/templates/Policies/instantEmailBody.html, engine/src/main/resources/templates/Rhosak/actionRequiredBody.html, engine/src/main/resources/templates/Rhosak/dailyRhosakEmailsBody.html, engine/src/main/resources/templates/Rhosak/instanceCreatedBody.html, engine/src/main/resources/templates/Rhosak/instanceDeletedBody.html, engine/src/main/resources/templates/Rhosak/rhosakEmailBody.html, engine/src/main/resources/templates/Rhosak/scheduledUpgradeBody.html, engine/src/main/resources/templates/Rhosak/serviceDisruptionBody.html, engine/src/main/resources/templates/Sources/insightsEmailBody.html, engine/src/main/resources/templates/Vulnerability/insightsEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestDriftTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOpenshiftAdvisorTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestPoliciesTemplate.java
This will fix a lot of links from email notifications sent on stage.
=> NOTIF-781 Use dynamic ConsoleDot host in all email templates

backend/src/main/java/com/redhat/cloud/notifications/db/Query.java, backend/src/main/java/com/redhat/cloud/notifications/db/builder/QueryBuilder.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/NotificationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/PageLinksBuilder.java, backend/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/QueryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/builder/QueryBuilderTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, common/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, common/src/main/java/com/redhat/cloud/notifications/models/Event.java, common/src/main/java/com/redhat/cloud/notifications/models/EventType.java, common/src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java
Continues work from #1269 
- Limit the fields that are acceptable for sorting to fixed lists of field names.
- Provides an option to specify a mapping from "nice_field" to "e.blabla.fooBar.NotSoNiceField".
- Backwards compatible with Events api `sortBy` (`sort_by` is used elsewhere)
=> NOTIF-674 Limit fields of sort expressions

common/src/main/java/com/redhat/cloud/notifications/routers/models/Meta.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacUser.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/rbac/RbacUserTest.java
- SnakeCaseStrategy turns `isActive` to `active` - we are receiving `is_active` - adding the explicit property instead
- The same applies for `isOrgAdmin`
=> Fix the JsonProperty of isAdmin and isOrgAdmin

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, common/src/test/java/com/redhat/cloud/notifications/MockServerLifecycleManager.java
Requires Quarkus 2.11
Unfortunately it looks like the underlying VertX.Web imp has changed, so that engine would not compile. 
And on top there seem to be changes in the authentication, as the tests work in Quarkus 2.10.2, but fail in 2.11
The backend code works though (with -Drbac.enabled=false) and then shows the right log:
`2022-07-26 15:21:32,622 INFO  [access_log] (executor-thread-1) "127.0.0.1 - hrupp 26/Jul/2022:15:21:32 +0200 "GET /api/integrations/v1.0/endpoints HTTP/1.1" 200 622 orgId=1234567"`
=> Log orgId in access_log

backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/UpdateBehaviorGroupRequest.java
This removes the workaround that was added to the Update behavior group.
The `bundle_id` was never used, but there are QA tests checking that the value has to be a valid UUID.
=> Remove QA workaround for the Update behavior group endpoint

common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeHelper.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java
This will remove the following entries from the engine log: (we currently have tons of them)
```
2022-10-04 15:06:42,000 DEBUG [com.red.clo.not.ope.BridgeHelper] (executor-thread-3) In getAuthToken()
2022-10-04 15:06:41,588 INFO  [com.red.clo.not.eve.EventConsumer] (executor-thread-3) NOID: Event with openshift/advisor/new-recommendation did not have an incoming id or messageId 
```
It also changes another log entry a bit:
```
2022-10-04 15:30:29,847 INFO  [com.red.clo.not.eve.EventConsumer] (executor-thread-0) Processing received action [id=null, rh-message-id=null, orgId=default-org-id, baet=my-bundle/policies-lifecycle-test/all]
2022-10-04 15:30:27,824 INFO  [com.red.clo.not.eve.EventConsumer] (executor-thread-0) Processing received action [id=null, …
```
=> Reduce noise in engine log

engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java
4xx errors shouldn't go unnoticed when we call BOP.
From now on, they will be logged at `warn` level (and generate a Sentry alert) instead of `debug`.
=> Log 4xx errors at warn level while calling BOP

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java
The prod DB contains a few email endpoints with `status = UNKNOWN`. Emails endpoints should always be `READY`.
This PR must be deployed on prod before #1546 is merged.
=> NOTIF-820 Make email endpoints READY when created

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointReadyChecker.java, common/src/main/java/com/redhat/cloud/notifications/openbridge/Processor.java
This will help us understand why a processor creation failed in RHOSE.
=> Log processor status_message in EndpointReadyChecker

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
The following exception is thrown because when an aggregation email is sent, we're passing a fake Event object to WebhookTypeProcessor#doHttpRequest. That event does not exist in the DB (which is perfectly normal).
```
2022-10-19 20:00:20,910 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-249) ERROR: insert or update on table "notification_history" violates foreign key constraint "fk_notification_history_event_id"
Detail: Key (event_id)=(d079d730-9557-4ad1-b17c-211538cdc281) is not present in table "event".
2022-10-19 20:00:20,911 ERROR [com.red.clo.not.pro.EndpointTypeProcessor] (executor-thread-249) Notification history creation failed for Endpoint{id=40ab7fad-b7fa-4c34-8a39-4075f8a8d86c, accountId='5685364', orgId='7931872', name='Email subscription', description='', …
```
=> RHCLOUD-22541 Stop persisting notification history for aggregation email

database/src/main/resources/db/migration/V1.66.0__notification_history_status.sql, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java
- If there was an exception in the sending mechanism, the history was created without status, causing the NPE
=> RHCLOUD-22573 Fix NPE when saving a notificationHistory

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/transformers/BaseTransformer.java, engine/src/test/java/com/redhat/cloud/notifications/ComplianceTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/DriftTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/PatchTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/VulnerabilityTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/ResourceOptimizationPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/transformers/BaseTransformerTest.java
The PR:
- Removes the `transform` function in favor of `toJsonObject`, since we could use just a single function instead of having scattered calls to the two functions.
- Adds a test to make sure that, at least, the structure we've defined will remain consistent in the future.
- Adds the environment URL every time the action gets serialized, so that it can be associated with the environment it must be checked on.
=> [RHCLOUD-22178] Include environment URLs when serializing Actions

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
This is what we were talking earlier - updated so it does the check per bundle
Will follow up with a migration PR to move rename all the repeated behavior groups and integrations
=> NOTIF-370 Ensure the behavior group name is per bundle

.rhcicd/clowdapp-engine.yaml
This change will allow us to specify the Sentry DSN on AppInterface.
[[RHCLOUD-22543]](https://issues.redhat.com/browse/RHCLOUD-22543)
=> [RHCLOUD-22543] feature: parametrize the Sentry DSN for the engine

database/src/main/resources/db/migration/V1.67.0__RHCLOUD-21733_remove-default-endpoints.sql
After researching we have found out that it is safe to remove the endpoints from the database.
[[RHCLOUD-21733]](https://issues.redhat.com/browse/RHCLOUD-21733)
=> [RHCLOUD-21733]feature: remove default endpoints from the database

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java
Kibana has a [256 chars limit](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html) for log entry messages that are indexed. If that limit is exceeded, the messages are still displayed in the Kibana UI but they can't be queried to build Kibana dashboards.
This PR removes the integration name from our log entry which guarantees that the log entry will never exceed 256 characters. We didn't really need that name in the first place. The `processorName` field of the log entry already contains the endpoint ID from the Notifications DB.
=> Shorten RHOSE log entry to fix Kibana dashboard

.rhcicd/clowdapp-backend.yaml
I forgot to include the required environment variables to be able to enable the Sources integration in Clowder.
[RHCLOUD-22065](https://issues.redhat.com/browse/RHCLOUD-22065)
=> [RHCLOUD-22065] feature: Clowder environment variables for the Sources integration

engine/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java, engine/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This adds a test to verify the status after an exception has been throw at any part of the processing.
It does so by mocking the `Failsafe.with` method to throw an exception.
=> RHCLOUD-22573 Add a test to verify NotificationHistory status

backend/src/main/resources/application.properties
We need to reference the ClowdApp name plus the deployment name for it to work.
[RHCLOUD-22065](https://issues.redhat.com/browse/RHCLOUD-22065)
=> [RHCLOUD-22065] fix: reference to the Sources endpoint in the properties

.rhcicd/clowdapp-aggregator.yaml, .rhcicd/clowdapp-backend.yaml
This change will allow us to specify the Sentry DSN for the backend and the aggregators on AppInterface.
[[RHCLOUD-22543]](https://issues.redhat.com/browse/RHCLOUD-22543)
=> [RHCLOUD-22543] feature: parametrize the Sentry DSN

common/src/main/java/com/redhat/cloud/notifications/routers/sources/SecretUtils.java
Basically:
* Includes the created secret ID for all the log statements that make sense to have it.
* Puts the "the secret was not created due to null/blank objects" log statement in the "debug" level.
* Removes the endpoint's IDs when creating the secrets, because at that point the endpoints are not yet persisted, and their IDs are null.
[[RHCLOUD-22065]](https://issues.redhat.com/browse/RHCLOUD-22065)
=> [RHCLOUD-22065] Sources logs tweaks

backend/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/WebhookProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrl.java, common/src/main/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrlValidator.java, common/src/test/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrlValidatorTest.java
This annotation should help in filtering the URLs that we are given that have internal IPs or hostnames that point to internal IPs. That way we can mitigate part of the SSRF attacks.
[[RHCLOUD-21830]](https://issues.redhat.com/browse/RHCLOUD-21830)
=> [RHCLOUD-21830] feature: annotation to disallow internal hosts

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointReadyChecker.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Instead of immediatly delete the endpoints, if they are managed by RHOSE  mark them for deletion and start the deletion process in the processor
=> RHCLOUD-22519 Use RHOSE delete lifecycle

backend/src/main/java/com/redhat/cloud/notifications/db/Query.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/NotificationRepository.java, backend/src/test/java/com/redhat/cloud/notifications/db/QueryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, common/src/main/java/com/redhat/cloud/notifications/models/EventType.java, common/src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java
As confirmed by sentry - all the unknown columns used in the last 30 days come from the unknown sort tests (things like: `08EEXZP9vB`, `KSvIe2Qm5h`, etc).
There is however one using `endpoint_id` - which is used in  [EndpointResource.getEndpointHistory](https://github.com/RedHatInsights/notifications-backend/blob/f5ece5f791d33ebce78d5e59a4b12ef3399453a8/backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java#L570-L575)
https://github.com/RedHatInsights/notifications-backend/blob/f5ece5f791d33ebce78d5e59a4b12ef3399453a8/backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java#L570-L575
This is however useless, as all the contents belong to the same endpoint, so adding and marking as deprecated.
=> RHCLOUD-22344 Fail requests with unknown sort configuration

common/src/main/java/com/redhat/cloud/notifications/models/EventType.java
This should fix the following bug found by @Mishrasubha while calling `GET /eventTypes` with the `name` sort param:
> ERROR: column reference "name" is ambiguous
=> Fix event type sort field

aggregator/src/main/java/com/redhat/cloud/notifications/db/AggregationOrgConfigRepository.java, database/src/main/resources/db/migration/V1.69.1__RHCLOUD-22474_reset_daily_digest_scheduling_table.sql
When a new OrgId have to be aggregted, the initialisation is one year in the past.
This date have no sens for the end user, but it is included on report email like `02 Dec 2021 - 7 policies triggered on 1 system`
=> RHCLOUD-22474 fix daily digest init date

database/src/main/resources/db/migration/V1.70.0__RHCLOUD-22943_no_more_endpoint_type_ordinal.sql
This PR contains step 1 of the migration from endpoints `ordinal` to `name` in the DB. It prepares the DB for a subsequent migration of the Java code which won't require any maintenance mode.
=> RHCLOUD-22943 Migrate from endpoints ordinal to name in the DB (step 1)

backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointReadyCheckerTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Adding some tests for the `EndpointReadyChecker`. 
The tests covers the add (success/failed) and deleting scenarios.
=> RHCLOUD-23167 Adding tests for EndpointReadyChecker

admin-console/src/main/webapp/src/components/EmailTemplates/RenderEmailTemplate.tsx, admin-console/src/main/webapp/src/pages/RenderEmailPage.tsx
The previous way I did it as a string broke the JSX rendering of the page.  This PR does the inline style in JSX friendly way.
=> Resize iframe inline style in JSX accepted way

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/AdvisorEmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/EmailPayloadAggregatorFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Advisor.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Advisor/dailyEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/AdvisorTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/AdvisorEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java
Advisor will produce a daily digest including:
* Number of new recommendations
* Number of resolved recommendations
* Number of deactivated recommendations
* The list of new recommendations, with the count of systems newly affected
* The list of resolved recommendations, with the count of systems previously affected
* The list of deactivated recommendations
This aggregator attempts to gather this information from the events over the last 24 hours.
Signed-off-by: Paul Wayper <paulway@redhat.com>
=> Initial write-up of Advisor daily digest notification aggregator

engine/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/rhose/RhoseTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java
This PR:
- introduces a clean separation of the Camel and RHOSE processors
- refactors everything to make the code simpler and easier to test/maintain
- does not contain any major tests changes to ensure that the refactoring didn't break something
`CamelTypeProcessorTest` will be refactored as well, later.
=> RHCLOUD-22545 Split the Camel and RHOSE processors

engine/src/main/java/com/redhat/cloud/notifications/events/CamelHistoryFillerHelper.java, engine/src/test/java/com/redhat/cloud/notifications/events/FromCamelHistoryFillerTest.java
We found an issue when the duration was too big, the deserialization method uses Long when the number is too big to fit an Integer.
Without the fix the updated tests fails with:
```
2023-01-04 12:21:17,746 INFO  [com.red.clo.not.eve.FromCamelHistoryFiller] (executor-thread-0) Processing return from camel: {"id":"e3c90a94-751b-4ce1-b345-b85d825795a4","source":"demo-log","data":"{\"duration\":2415706709,\"details\":{\"target\":\"1.2.3.4\",\"type\":\"com.redhat.console.notification.toCamel.tower\"},\"finishTime\":1639476503209,\"outcome\":null,\"successful\":true}","content-type":"application/json","specversion":"1.0","time":"2021-12-14T10:08:23.217Z","type":"com.redhat.cloud.notifications.history"}
2023-01-04 12:21:17,865 INFO  [com.red.clo.not.eve.FromCamelHistoryFiller] …
```
=> Casts to Number instead of Integer (or Long)

.rhcicd/clowdapp-engine.yaml
We enabled Sources in the backend, but not in the engine. This will allow us to enable Sources in the notifications engine too.
[[RHCLOUD-22065]](https://issues.redhat.com/browse/RHCLOUD-22065)
=> [RHCLOUD-22065] feature: environment variable to enable Sources in the engine

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BundleRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/CreateBehaviorGroupRequest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BundleRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/models/behaviorgroup/CreateBehaviorGroupRequestTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
The frontend team has requested us to implement a change to be able to create a behavior group by using the bundle's name, instead of its UUID. The reason behind this is that they seem to be able to provide the bundle name directly, but for the UUID, they need to fetch all the bundles to find the right one by name.
[[RHCLOUD-22513]](https://issues.redhat.com/browse/RHCLOUD-22513)
=> [RHCLOUD-22513] feature: create behavior groups specifying the bundle name

engine/src/main/resources/templates/EdgeManagement/imageCreationBody.html, engine/src/main/resources/templates/EdgeManagement/imageCreationTitle.txt
Fixed issues with Edge image creation email template.
Fixed these issues that were listed in this [slack thread](https://coreos.slack.com/archives/C01UC7NRV19/p1664437926331259):
- no button to go to Images
- Instant email but not timestamp
- Subject doesn't mention Edge, nor timestamp
- Extra ' ' (space) before final point
- No name/link to the image name
- Sentence is not grammatically correct..
- 'Egde' typo in title
~~Currently setting this PR to draft because this PR depends on a [PR from Edge-api](https://github.com/RedHatInsights/edge-api/pull/1825) to be merged first.~~
=> Fixed Edge image creation email template

common/src/main/java/com/redhat/cloud/notifications/routers/sources/SecretUtils.java, engine/src/main/resources/application.properties
Let's see if this helps understanding why Sources is returning 401s for Notifications.
[[HCLOUD-23722]](https://issues.redhat.com/browse/RHCLOUD-23722)
=> feature: debug what "x-rh-identity" header is being sent to Sources

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/templates/models/Environment.java, engine/src/test/java/com/redhat/cloud/notifications/templates/models/EnvironmentTest.java
The idea behind this change is to allow developers to customize the environment's URL that is used across notifications. By doing this all the notifications can use the specified URL instead of relying on the hard coded values.
[[RHCLOUD-23752]](https://issues.redhat.com/browse/RHCLOUD-23752)
=> [RHCLOUD-23752] refactor: specify the environment's URL via an environment variable

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/BehaviorGroupCleanupResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/BehaviorGroupCleanupResourceTest.java
This PR introduces an internal endpoint that will be used to delete all behavior groups from a few internal accounts that will not be disclosed here.
=> RHCLOUD-23546 Add temporary internal endpoint to delete behavior groups

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointReadyChecker.java
When a NPE is thrown during the processing of one of our endpoints, the scheduled job is interrupted immediately while it should process the other endpoints.
=> Make EndpointReadyChecker resilient to all kinds of exceptions

.rhcicd/clowdapp-engine.yaml
Slack and email links are incorrect on stage because of that missing env var.
=> Add ENV_BASE_URL environment variable

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java
QE has spotted that after a few thousand behavior groups that get created, the frontend's performance degrades. However, having a customer with more than 15 behavior groups configured is going to be a rare case.
That is why we are limiting the number of behavior groups that can be created, since we assume that if more need to be created, there will highly likely be old ones that are not used, and therefore need to be deleted first.
[[RHCLOUD-21842]](https://issues.redhat.com/browse/RHCLOUD-21842)
=> [RHCLOUD-21842] feature: limit the maximum allowed number of behavior group creations

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml
Another team needs to run Notifications without Sources, and they can't do that if Sources is listed as a mandatory dependency.
[[RHCLOUD-23993]](https://issues.redhat.com/browse/RHCLOUD-23993)
=> [RHCLOUD-23993] feature: turn Sources ClowdApp into an optional dependency

backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/CreateBehaviorGroupRequest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/behaviorgroup/UpdateBehaviorGroupRequest.java, backend/src/test/java/com/redhat/cloud/notifications/models/behaviorgroup/CreateBehaviorGroupRequestTest.java, backend/src/test/java/com/redhat/cloud/notifications/models/behaviorgroup/UpdateBehaviorGroupRequestTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
The front end already has that limit established, so this needs to be done in the back end as well so that direct requests are also limited in this sense.
[[RHCLOUD-23717]](https://issues.redhat.com/browse/RHCLOUD-23717)
=> [RHCLOUD-23717] feature: limit behavior groups name to 150 characters

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml
See the description of https://github.com/quarkiverse/quarkus-logging-cloudwatch/pull/375 for more information about the new env var.
After this PR, if we send log entries to CloudWatch and the remote server does not respond within 30 seconds, our request will be canceled with a timeout to prevent the accumulation of log entries in the app memory. The cancelation will be logged as an error and reported in Sentry.
=> RHCLOUD-23850 Add QUARKUS_LOG_CLOUDWATCH_API_CALL_TIMEOUT env var

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/SettingsValueJsonForm.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/SettingsValues.java
Follow up to https://github.com/RedHatInsights/notifications-backend/pull/1702 to only show the message about "forced emails" in applications that have forced emails
=> Display warning on apps forcing emails

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java
While working on the API docs, i noticed that we have a validation error:
```yml
/endpoints/{uuid}/test:
post:
tags:
- Endpoint Resource
operationId: EndpointResource_testEndpoint
parameters:
- name: uuid
in: path
description: The UUID of the endpoint to test
required: true
schema:
type: string
responses:
'204': {}
'401':
description: Not Authorized
'403':
description: Not Allowed
security:
- SecurityScheme: []
```
```
Structural error at paths./endpoints/{uuid}/test.post.responses.204
should have required property 'description'
missingProperty: description
```
=> Fix openapi error

.rhcicd/clowdapp-engine.yaml
The old `10s` value will need to be added through an env var to the stage and prod configurations.
=> Fix notifications-engine startup on ephemeral

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/AdvisorEmailAggregator.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/AdvisorEmailAggregatorTest.java
The Advisor team requested that the aggregation emails should only return the 5 most critical rules received that day, instead of all of the rules that might have been triggered.
[[RHCLOUD-23848]](https://issues.redhat.com/browse/RHCLOUD-23848)
=> [RHCLOUD-23848] feature: limit and order the returned rules for Advisor aggregations

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
An endpoint should not be deleted unless the associated RHOSE processor is also ready to be deleted along with it.
[[RHCLOUD-22355]](https://issues.redhat.com/browse/RHCLOUD-22355)
=> [RHCLOUD-22355] feature: disallow endpoint deletion if processor is not in actionable state

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
Enables adding or removing a specific behavior group from a given event type with an atomic operation.
[[RHCLOUD-22367]](https://issues.redhat.com/browse/RHCLOUD-22367)
=> [RHCLOUD-22367] feature: add or remove behavior groups to event types

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/TemplateResource.java, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/RunOnEngineStartup.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/TemplateRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorWithMigratedTemplateTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java
Be able to create/update email templates from file system, when engine starts.
Restrict write access to Template API to internal admin only for the moment.
=> [RHCLOUD-23515] Update email template in db from file system

.rhcicd/clowdapp-engine.yaml, engine/src/main/resources/application.properties
I'm removing the it keystore from `QUARKUS_HTTP_SSL_CERTIFICATE_KEY_STORE_FILE` (global keystore for http) because we might have to use a new one from clowdapp.
I'm setting it specifically for the ITservice.
=> Making IT service optional

engine/src/main/java/com/redhat/cloud/notifications/processors/slack/SlackProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/slack/SlackProcessorTest.java
`JsonObject#getMap` doesn't work well with Qute when fields from `context` need to be used in a template, so I replaced it with `ObjectMapper#readValue(String.class, Map.class)`.
=> Fix Slack notifications data deserialization

.rhcicd/clowdapp-engine.yaml
Due to the parameter not being defined in the "parameters" section of the ClowdApp, Clowder didn't replace it when deploying the engine, which caused the engine to fail and restart because of the missing parameter.
[[RHCLOUD-24718]](https://issues.redhat.com/browse/RHCLOUD-24718)
=> [RHCLOUD-24718] fix: the engine crashloops in the ephemeral environment

backend/src/main/java/com/redhat/cloud/notifications/routers/engine/DailyDigestService.java
I tried to trigger a daily digest in stage and it failed with a 404.
The REST client interface didn't match this path:
https://github.com/RedHatInsights/notifications-backend/blob/f1b415363fd28c79ddf4437685ba642b2587d502/engine/src/main/java/com/redhat/cloud/notifications/routers/DailyDigestResource.java#L49
=> Fix daily digest trigger endpoint path

.rhcicd/clowdapp-engine.yaml
`engine` currently migrates email templates at startup which sometimes leads to a pod restart because the pod isn't ready fast enough. This PR should prevent these restarts.
=> Increase engine probes initial delay and failure threshold

.rhcicd/clowdapp-engine.yaml
This will help us adapt the service to environments that don't have the BOP implemented with the HTTPS protocol.
=> refactor: allow specifying the full URL for the BOP host

.github/workflows/codeql-analysis.yml
I noticed CodeQL download all dependencies on every run.
Adding a cache for java and javascript (depending what is being run)
=> Adds Cache for CodeQL analysis

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/slack/SlackProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/teams/TeamsProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/transformers/BaseTransformer.java, engine/src/test/java/com/redhat/cloud/notifications/AdvisorTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/ComplianceTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/DriftTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/PatchTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/VulnerabilityTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/ResourceOptimizationPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/transformers/BaseTransformerTest.java
The idea is to make the messages more user friendly, by allowing them to chose the more friendlier bundle display name, instead of it's schematic name.
I was initially going to have just one single `toJsonObject` which took an `Event`, but I was unsure about which approach was better. So I decided to have two instead, but I'm open to discussing this :eyes:
[[RHCLOUD-22667]](https://issues.redhat.com/browse/RHCLOUD-22667)
=> [RHCLOUD-22667] feature: return bundle's display names on Slack notifications

engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregatorTest.java
It was missing the UTC offset when calling a local time
=> Fix test when running locally

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
The removed graph:
- was broken
- didn't make any sense
- was not critical enough to be included in the Grafana dashboard
We can always access the data directly from Prometheus.
=> Remove broken graph from Grafana

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, common/src/main/java/com/redhat/cloud/notifications/models/EndpointType.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/events/EndpointProcessorTest.java
Adds Event-Driven Ansible type that aliases WebHook processor.
RHCLOUD-25405
=> feat: create new Ansible endpoint type

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregator.java, engine/src/main/resources/templates/Patch/dailyEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/PatchTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestPatchTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/secured/TestPatchDailyDigest.java
Changes:
- Added synopsis field to aggregator
- Order of advisory types in emails
- Included synopsis column in emails
- Group `unspecified` advisories under `other` group
=> [SPM-2047] refactor: update patch daily digest to new format

common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
We forgot to put the conditional in a similar fashion to the rest of the feature flags, so it is a bit off. Nothing too urgent or important, but the patch is just to help maintain consistency.
[[RHCLOUD-25887]](https://issues.redhat.com/browse/RHCLOUD-25887)
=> [RHCLOUD-25887] fix: "instant emails" feature flag styling

.rhcicd/clowdapp-backend.yaml
This is required to include all applications regardless if they have a template or not.
=> Add default template parameter to backend

engine/pom.xml, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelCommonExceptionHandler.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelNotificationProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/ExchangeProperty.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/OutgoingCloudEventBuilder.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/ReturnRouteBuilder.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/google/chat/GoogleChatNotificationProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/google/chat/GoogleChatRouteBuilder.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/slack/SlackNotificationProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/slack/SlackRouteBuilder.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsNotificationProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsRouteBuilder.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelRoutesTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/google/chat/GoogleChatRoutesTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackRoutesTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsRoutesTest.java
This PR introduces the notification history return through the `platform.notifications.fromcamel` Kafka topic for Slack, Microsoft Teams and Google Chat.
=> RHCLOUD-26020 Return history from Camel through Kafka

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/ReturnRouteBuilder.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelRoutesTest.java
The topic name from `application.properties` is not directly used in stage or prod. It is used as a key to retrieve the actual topic name from the Clowder configuration. This only works if the config key starts with `mp.messaging` and ends with `topic`.
See [this](https://github.com/RedHatInsights/clowder-quarkus-config-source/blob/56502b08308acec1248d4feef4b5bbc5ae335625/src/main/java/com/redhat/cloud/common/clowder/configsource/ClowderConfigSource.java#L176-L189) for more details.
=> RHCLOUD-26020 Enable Kafka topic name translation using Clowder config

.rhcicd/sonarqube/Dockerfile, .rhcicd/sonarqube/scanner/scan_code.bash, .rhcicd/sonarqube/sonarqube.bash, pom.xml, sonar-project.properties
The script is intended to be run in order to analyze the code base. It will run for PR checks, and also every time we merge something to master.
The "sonarqube-project.properties" file is removed because the SonarQube Scanner's Maven plugin doesn't honor it.
[[RHCLOUD-22207]](https://issues.redhat.com/browse/RHCLOUD-22207)
=> [RHCLOUD-22207] feature: SonarQube analysis script

.rhcicd/sonarqube/scanner/scan_code.bash
The scanner was complaining that the ".java" files were not compiled,
and that should be provided via a property. It was working locally
because I always have the compiled project there, so by copying all the
contents of the project's directory it also copied the compiled classes.
However, in a pipeline, where everything is fresh, that didn't happen,
which I suppose is causing the scanner to complain.
[[RHCLOUD-22207]](https://issues.redhat.com/browse/RHCLOUD-22207)
=> RHCLOUD-22207 | fix sonarqube pipeline

engine/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
https://github.com/RedHatInsights/notifications-backend/compare/132e9fb8bdd5dfe717c79f1e32fc90dfac326992...dc3eb724b4e37e485c1346fad991b8ce610f5254
This PR does NOT revert:
- the new ClowdApp params used to change the log level of Hibernate, Kafka client and SmallRye Reactive Messaging
- the removal of `@Acknowledgment(PRE_PROCESSING)` in `EventConsumer`
- the addition of `cloud-events=false` in the Reactive Messaging channels configuration
=> Revert changes introduced to investigate the Kafka outage

.rhcicd/sonarqube/scanner/scan_code.bash, .rhcicd/sonarqube/sonarqube.bash
The pipeline sets the "GIT_BRANCH" to "origin/master", which is why the "master analysis" SonarQube pipeline was attempting to go the PR route, and failing.
[RHCLOUD-22207](https://issues.redhat.com/browse/RHCLOUD-22207)
=>  RHCLOUD-22207 | fix: SonarQube analysis in master branch

.rhcicd/clowdapp-engine.yaml
I forgot to specify the aforementioned Kafka topic which causes the engine to fail at connecting.
[[RHCLOUD-25597]](https://issues.redhat.com/browse/RHCLOUD-22207)
=> RHCLOUD-25597 | feature: specify the Kafka topic for the export service

engine/src/main/resources/application.properties
The application was complaining that the "export-service" was not being found in Clowder's endpoints section, and the reason was that the naming was wrong.
=>  RHCLOUD-25597 | fix: export service's endpoint name

engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/google/chat/GoogleChatProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsProcessorTest.java
`IncomingCloudEventFilter` tried to extract the `ce-type` field from the Kafka message headers while it was included as a cloud event payload field. Now, `ce-type` should be available in the headers.
=> RHCLOUD-26040 Fix cloud events filtering

.rhcicd/stage-backend-post-deployment-tests.yaml, .rhcicd/stage-engine-post-deployment-tests.yaml
The new files will be updated with different tests markers by the QE team soon.
The old file remains in this repo for now to make the transition in app-interface smooth.
=> RHCLOUD-26443 Split the post deployment tests configuration

.rhcicd/stage-backend-post-deployment-tests.yaml, .rhcicd/stage-engine-post-deployment-tests.yaml
The name of the post deployment tests pods cannot exceed 63 characters.
=> RHCLOUD-26443 Fix the post deployment tests run

.rhcicd/stage-backend-post-deployment-tests.yaml, .rhcicd/stage-engine-post-deployment-tests.yaml
This will change the markers so that the tests will be split for the backend and engine repos
=>  [RHCLOUD-26436] Changing markers to split repos

engine/src/main/java/com/redhat/cloud/notifications/exports/ExportEventListener.java
Uploads are currently failing in stage, but we're not logging anything.
=> RHCLOUD-26500 Log exception when an upload to the export service fails

.rhcicd/clowdapp-engine.yaml, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelRoutesTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackRoutesTest.java
Setting `QUARKUS_CAMEL_ROUTES_DISCOVERY_ENABLED` from a deployment param didn't work. In the Camel version we depend on, that config value is fixed at build time.
=> RHCLOUD-26219 Disable Camel routes discovery in the engine

.rhcicd/clowdapp-engine.yaml
By allowing to specify the export service URL with an environment variable, we will be able to more flexibly debug what might be going on.
[[RHCLOUD-2600]](https://issues.redhat.com/browse/RHCLOUD-26500)
=> RHCLOUD-2600 | feature: environment variable for the export service's URL

engine/src/main/java/com/redhat/cloud/notifications/exports/ExportEventListener.java
From now on, since we have moved away from stateless database sessions, the request context needs to be activated if the function that listens to a Kafka topic accesses the database.
[[RHCLOUD-26500]](https://issues.redhat.com/browse/RHCLOUD-26500)
=> RHCLOUD-26500 | feature: activate the request context in the event listener

.rhcicd/clowdapp-backend.yaml
Implements the steps described in the Floorist's documentation[1] to use the Floorist operator instead of the old, more manual way.
*  \[1\]: https://docs.engineering.redhat.com/display/COMPL/Floorist+onboarding
* RHCLOUD-25863
=> RHCLOUD-25863 | feature: migrate to the Floorist operator

engine/src/main/java/com/redhat/cloud/notifications/events/ConnectorReceiver.java, engine/src/main/java/com/redhat/cloud/notifications/processors/eventing/EventingProcessor.java
On rare occasions, the following issue can happen in any environment:
```
2023-06-20 17:12:04,813 INFO  [com.red.clo.not.eve.ConnectorReceiver] (executor-thread-0) Camel notification history update failed because no record was found with [id=4ef1a736-ec9e-4b96-bf49-a385e40ebf94]
```
This PR prevents that by persisting the history in the DB before the engine receives the return Kafka message from the eventing apps.
=> Prevent eventing history update failure

engine/src/main/java/com/redhat/cloud/notifications/exports/ExportError.java, engine/src/test/java/com/redhat/cloud/notifications/exports/ExportEventListenerTest.java
The payload that was being sent to the export service didn't have the correct body, which caused the latter service to respond with an invalid status code to our request.
[RHCLOUD-26500](https://issues.redhat.com/browse/RHCLOUD-26500)
=> RHCLOUD-26500 | fix: incorrect error payload sent to the export service

connector-common/src/main/java/com/redhat/cloud/notifications/connector/ExceptionProcessor.java, connector-common/src/test/java/com/redhat/cloud/notifications/connector/ConnectorRoutesTest.java, connector-google-chat/src/main/java/com/redhat/cloud/notifications/connector/google/chat/GoogleChatExceptionProcessor.java, connector-microsoft-teams/src/main/java/com/redhat/cloud/notifications/connector/microsoft/teams/TeamsExceptionProcessor.java, connector-slack/src/main/java/com/redhat/cloud/notifications/connector/slack/SlackExceptionProcessor.java, connector-slack/src/main/resources/application.properties, connector-slack/src/test/java/com/redhat/cloud/notifications/connector/slack/SlackConnectorRoutesTest.java
This PR changes the log level from `ERROR` to `DEBUG` when a `404 channel_not_found` exception is thrown in the Slack connector. Because of that change, we will no longer receive alerts in Sentry.
It does not change the notification status returned to the `engine` through Kafka. That notification is still marked as failed.
=> RHCLOUD-25673 Better deal with channel_not_found Slack error

connector-google-chat/src/main/java/com/redhat/cloud/notifications/connector/google/chat/GoogleChatExceptionProcessor.java, connector-slack/src/main/java/com/redhat/cloud/notifications/connector/slack/SlackExceptionProcessor.java
⚠️ ~This PR is based on #1906 which needs to be reviewed and merged first.~
This PR changes the log level from `ERROR` to `DEBUG` when a 4xx error is returned in the Google Chat connector. Because of that change, we will no longer receive alerts in Sentry.
It does not change the notification status returned to the `engine` through Kafka. That notification is still marked as failed.
=> Better deal with 4xx errors in Google Chat connector

.rhcicd/clowdapp-engine.yaml
In order to discard that there is an issue with grabbing the export service's URL from the Clowder's configuration file, it is required to let the engine read it from there, instead of overriding the URL. Removing the URL in AppInterface doesn't do it because there is a default value set in here.
[[RHCLOUD-26500]](https://issues.redhat.com/browse/RHCLOUD-26500)
=> RHCLOUD-26500 | refactor: remove the export service's endpoint URL

.rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml, .rhcicd/clowdapp-connector-slack.yaml, .rhcicd/clowdapp-engine.yaml, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelRoutesTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackRoutesTest.java
The Camel routes in `engine` were disabled for testing purposes. This PR reverts that.
=> Revert Camel config in engine

engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelRoutesTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackRoutesTest.java
The Camel routes from `engine` need to be disabled again because we're ready to rely completely on the connectors.
=> Disable Camel routes in the engine

engine/src/main/java/com/redhat/cloud/notifications/templates/extensions/ActionExtension.java, engine/src/main/resources/templates/Common/insightsEmailBody.html, engine/src/main/resources/templates/Default/instantEmailBody.html, engine/src/main/resources/templates/Default/instantEmailTitle.txt, engine/src/test/java/com/redhat/cloud/notifications/EmailTemplatesInDbHelper.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestDefaultTemplate.java
Depends on #2036 
@g-duval I think we will need to do something similar for the default templates when using the drawer.
If the bundle/app/event-type are needed, we could implement something to actually have that information.
=> RHCLOUD-26685 Fix default email templates for cloud events

engine/src/main/resources/application.properties
We were attempting to grab the export service's endpoint from the regular endpoints section, while the URL for the private API needed to be generated by reading the configuration from the private endpoints section. After updating our configuration reader, we are ready to change our configuration keys.
* https://github.com/RedHatInsights/clowder-quarkus-config-source/pull/150
[[RHCLOUD-26703]](https://issues.redhat.com/browse/RHCLOUD-26703)
=> RHCLOUD-26703 | fix: the engine doesn't grab the correct endpoint for the integration

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/SourcesSecretsMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/SourcesSecretsMigrationServiceTest.java
During the migration, we saw that constraint violation exceptions on endpoints with invalid URLs were rolling back the whole operation. The goal of this change is to handle those exceptions in order to be able to continue with the process even when a failure happens, and in order to handle the deletion of any created secrets when the error occurred.
[[RHCLOUD-24734]](https://issues.redhat.com/browse/RHCLOUD-24734)
=> [RHCLOUD-24734] fix: avoid exceptions blocking the migrations

connector-common/src/main/java/com/redhat/cloud/notifications/connector/IncomingCloudEventProcessor.java
The engine only sends the `data` field as JSON in all environments now.
Let's wait until #2035 has been merged before merging this PR though.
=> Remove compatibility mode in IncomingCloudEventProcessor

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
This information was missing from the collection's response, and QE reported it, so this is why we are including it in the responses from now on.
[[RHCLOUD-23167]](https://issues.redhat.com/browse/RHCLOUD-21880)
=> [RHCLOUD-23167] feature: return the "meta" information for the behavior group collection

.rhcicd/clowdapp-engine.yaml
To make sure we always deploy the export-service along the engine :)
=> Make export-service a hard dependency

connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/SplunkCloudEventDataExtractor.java, connector-splunk/src/test/java/com/redhat/cloud/notifications/connector/splunk/SplunkCloudEventDataExtractorTest.java
https://docs.splunk.com/Documentation/Splunk/9.0.5/Data/HECRESTendpoints
While this is not requested, org admins may add the `/services/collector/raw` path at the end of their Splunk URL, in the integrations settings. When that happens, we want to send to events to `/services/collector/event` instead.
=> RHCLOUD-25256 Replace Splunk /raw endpoint with /event endpoint

.rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml, .rhcicd/clowdapp-connector-slack.yaml, .rhcicd/clowdapp-connector-splunk.yaml
The new default values are the ones currently used in all environments where the connectors are deployed.
=> Lower default CPU request/limit for all connectors

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/ExchangeProperty.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/MigrationFilter.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/SplunkCloudEventDataExtractor.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/SplunkRouteBuilder.java, connector-splunk/src/test/java/com/redhat/cloud/notifications/connector/splunk/SplunkConnectorRoutesTest.java, engine/src/main/java/com/redhat/cloud/notifications/processors/eventing/EventingProcessor.java
Related to https://github.com/RedHatInsights/eventing-integrations/pull/210
When `notifications-connector-splunk` will be deployed in production, it will belong to a different Kafka group (`notifications-connector-splunk`) compared to the old eventing app (`eventing-splunk`). Because of that change, the connector will automatically consume the Kafka topic from the smallest Kafka offset available rather than from the offset of the latest message consumed by the `eventing-splunk` Kafka group.
This PR introduces the `NOTIFICATIONS_SPLUNK_CONNECTOR_KAFKA_PROCESSING_ENABLED` feature flag in `engine` which will be used to prevent duplicate processing during the switch from eventing to the connector. When that flag is `true` and a message is produced, the connector will consume that message and …
=> RHCLOUD-27092 Prevent duplicate Kafka processing for Splunk

backend/src/main/java/com/redhat/cloud/notifications/routers/OrgConfigResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/OrgConfigResourceTest.java
The OpenAPI descriptions were describing a bit of a different endpoints than the ones that we had annotated. This was causing the automatically generated clients to not fully comply with the endpoints implemented in the backend, thus causing requests processing to fail.
[[RHCLOUD-27100]](https://issues.redhat.com/browse/RHCLOUD-27100)
=> RHCLOUD-27100 | fix: inaccuracies with OpenAPI descriptions

.rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml, .rhcicd/clowdapp-connector-slack.yaml, .rhcicd/clowdapp-connector-splunk.yaml, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ConnectorConfig.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/EngineToConnectorRouteBuilder.java
This PR makes changes to the Kafka polling strategy easier for connectors.
Changing the max poll records or delay is often needed when long running requests (such as calls to failing external hosts) are performed during the processing of a Kafka message.
=> RHCLOUD-27205 Make Kafka polling strategy easier to configure

pom.xml
Using sonar.coverage.jacoco.xmlReportPaths property will allow all sub modules to append the same report test file
=> [RHCLOUD-27283] Fix Sonar Jacoco config for test coverage report

.rhcicd/clowdapp-connector-servicenow.yaml, .rhcicd/clowdapp-connector-splunk.yaml
`advisor-backend` cannot be used as a ClowdApp dependency because the repository is not public.
This temporary PR fixes the PR check but we may need to add `advisor-backend` back later, with additional changes in app-interface.
=> Fix PR check

.rhcicd/clowdapp-connector-splunk.yaml, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ConnectorConfig.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/SplunkConnectorConfig.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/SplunkRouteBuilder.java, connector-splunk/src/main/resources/application.properties
I suspect that the HTTP timeout settings we had until now for Splunk were ignored by the Camel `https` component.
This PR changes the configuration of these timeouts from `application.properties` to a programmatic approach with some logging at startup and the possibility to override the config values from the deployment params.
=> Configure Splunk HTTPS timeouts programmatically

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/ImageBuilderAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/ImageBuilder/dailyEmailBodyV2.html, engine/src/main/resources/templates/ImageBuilder/dailyEmailTitleV2.txt, engine/src/main/resources/templates/ImageBuilder/launchFailedEmailBodyV2.html, engine/src/main/resources/templates/ImageBuilder/launchFailedInstantEmailTitleV2.txt, engine/src/main/resources/templates/ImageBuilder/launchSuccessInstantEmailBodyV2.html, engine/src/main/resources/templates/ImageBuilder/launchSuccessInstantEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestImageBuilderTemplate.java
This PR adds instant and daily email templates for images launch, part of the [HMS-1551](https://issues.redhat.com/browse/HMS-1551) and [HMS-738](https://issues.redhat.com/browse/HMS-738) epic
successful launch:
failed launch:
daily email:
=> feat(HMS-1551): Add images email templates

.rhcicd/pr_check.sh
The PR checks and ephemeral deployments started to fail because Clowder could not see the "historical-system-profiles" and "system-baseline" services come up, due to an out of memory error.
The specified flags in the PR checks should help solve this issue.
[[RHCLOUD-27503]](https://issues.redhat.com/browse/RHCLOUD-27503)
=> RHCLOUD-27503 | feature: increase resources for specific dependencies

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/SettingsValueByEventTypeJsonForm.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java
The new UI on the users' preferences requires the labels for the bundles and the applications.
```json
{
"bundles": {
"console": {
"applications": {
"integrations": {
"eventTypes": [
{
"name": "integration-disabled",
"label": "Integration disabled",
"fields": [
{
"name": "bundles[console].applications[integrations].eventTypes[integration-disabled].emailSubscriptionTypes[DAILY]",
"label": "Daily digest",
"description": "Daily summary of triggered application events in 24 hours span.",
"initialValue": false,
"component": "descriptiveCheckbox",
"validate": []
}
]
},
{
"name": "integration-test",
"label": "Integration Test",
"fields": [
{
"name": "bundles[console].applications[integrations].eventTypes[integration-test].emailSubscriptionTypes[DAILY]",
"label": "Daily digest",
"description": …
```
=> RHCLOUD-27421 | feature: include labels in bundles and applications

engine/src/main/resources/templates/ImageBuilder/launchFailedEmailBodyV2.html, engine/src/main/resources/templates/ImageBuilder/launchSuccessInstantEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestImageBuilderTemplate.java
This PR removes timestamps from instant emails and adds a `n/a` value to the DNS column when the value is empty (can be empty in some cloud providers).
=> fix(HMS-2321): fix image builder instant email templates

engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/eventing/EventingProcessor.java
This PR moves some code that was duplicated 4 times if we count the ongoing PRs about the `email` and `webhook` connectors.
=> Move duplicated code to ConnectorSender

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/mbop/Constants.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/mbop/MBOPService.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/mbop/MBOPUser.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProviderTest.java
Notifications shouldn't be directly calling the IT service for users, since MBOP has been designed and developed to act as the middleman, thus saving us from having to deal with things like certificates in our application. Therefore, this is the first step to replace that integration.
[[RHCLOUD-23645]](https://issues.redhat.com/browse/RHCLOUD-23645)
=> RHCLOUD-23645 | feature: fetch users from MBOP instead of the IT service

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/engine/EndpointTestService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/event/TestEventHelper.java, common/src/main/java/com/redhat/cloud/notifications/routers/endpoints/EndpointTestRequest.java, common/src/main/java/com/redhat/cloud/notifications/routers/endpoints/InternalEndpointTestRequest.java, common/src/test/java/com/redhat/cloud/notifications/models/event/TestEventHelperTest.java, engine/src/main/java/com/redhat/cloud/notifications/routers/EndpointTestResource.java, engine/src/test/java/com/redhat/cloud/notifications/routers/EndpointTestResourceTest.java
The second step on sending "test events" for integrations was to allow
sending custom messages on those events. This implements it in a way
that the client can decide whether to send a message or not. But if they
do, the message must not be blank.
[[RHCLOUD-25186]](https://issues.redhat.com/browse/RHCLOUD-25186)
=> [RHCLOUD-25186] feature allow overriding default message test endpoint

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java
This will move these APIs to our private.json file which can be obtained in a build's artifacts (i.e. scrolling to the bottom in the summary page of github actions)
e.g.
https://github.com/RedHatInsights/notifications-backend/actions/runs/5927557480
=> Move user preferences APIs to private APIs

docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-connector-google-chat.jvm, docker/Dockerfile.notifications-connector-microsoft-teams.jvm, docker/Dockerfile.notifications-connector-servicenow.jvm, docker/Dockerfile.notifications-connector-slack.jvm, docker/Dockerfile.notifications-connector-splunk.jvm, docker/Dockerfile.notifications-connector-webhook.jvm, docker/Dockerfile.notifications-engine.jvm
This is a test.
I'm discussing with the team responsible for `ubi9/openjdk-17-runtime` to determine if we can switch to that image.
=> Change base image to ubi9/openjdk-17-runtime

docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-connector-google-chat.jvm, docker/Dockerfile.notifications-connector-microsoft-teams.jvm, docker/Dockerfile.notifications-connector-servicenow.jvm, docker/Dockerfile.notifications-connector-slack.jvm, docker/Dockerfile.notifications-connector-splunk.jvm, docker/Dockerfile.notifications-connector-webhook.jvm, docker/Dockerfile.notifications-engine.jvm
`ubi9` isn't certified yet for some environments so we'll stick with `ubi8` for a little bit longer.
=> Use ubi8 instead of ubi9 base Docker image

.rhcicd/clowdapp-connector-email.yaml
RBAC is not listed as a dependency, and that makes the "cdappconfig.json" file not to have the required endpoint for the email connector to work.
=> RHCLOUD-28170 | fix: add RBAC as a dependency

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, connector-email/src/main/resources/application.properties
The ephemeral environment is complaining about not having the environment variable set, and therefore not having a proper value to boot Quarkus with it. Since we already provide a value in the properties file, it might as well be worth specifying it as a default value in the configuration file.
=> RHCLOUD-28170 | fix: the key store location as a default value

.rhcicd/clowdapp-connector-email.yaml
The empty string is causing Clowder to actually apply the environment variable, which in turn causes Quarkus to fail because it cannot load an empty string as a configuration parameter.
=> RHCLOUD-28170 | fix: remove the default value for the "IT keystore location" env var

.rhcicd/clowdapp-connector-email.yaml
The volume which should contain the IT certificate is missing, which makes the deployment fail.
=> RHCLOUD-28170 | fix: missing volume mount for the IT certificate

.rhcicd/clowdapp-connector-email.yaml, .rhcicd/clowdapp-engine.yaml, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, connector-email/src/main/resources/application.properties
The default value seems to be overridden by Clowder even though we have the default configuration value in the code. I am reverting the previous change and adding the environment variable in AppInterface.
Also, the engine is suffering from the same error because no default value is provided for the connector feature flag. I am providing one just in case.
=> RHCLOUD-28170 | fix: revert default value and add one for the engine

connector-email/src/main/resources/application.properties, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java
The connector is named "notifications-connector-email" everywhere, so I think it makes sense to rename it to the simplest name possible. Also, I suspect the mismatch in the name and the sent Kafka header are making the connector's filter to ignore the Kafka messages.
=>  RHCLOUD-28244 | feature: change the email connector's name

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java
The templates are expecting the event wrapper, and not the event itself. This is causing the email connector's email processor to fail when trying to render the templates.
=> feature: pass the event wrapper to the rendering engine

.rhcicd/clowdapp-connector-email.yaml, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/rbac/RBACConstants.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/rbac/RBACPrincipalsRequestPreparerProcessor.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/rbac/authentication/RBACAuthenticationUtilities.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/rbac/group/RBACGroupPrincipalsRequestPreparerProcessor.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/rbac/group/RBACGroupRequestPreparerProcessor.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/RBACPrincipalsRequestPreparerProcessorTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/authentication/RBACAuthenticationUtilitiesDevelopmentKeyTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/authentication/RBACAuthenticationUtilitiesPSKTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/authentication/testprofiles/DevelopmentKeyTestProfile.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/authentication/testprofiles/PSKsTestProfile.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/group/RBACGroupPrincipalsRequestPreparerProcessorTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/group/RBACGroupRequestPreparerProcessorTest.java
The integration with RBAC does not work because the connector is not sending the required PSK authentication header.
=> RHCLOUD-28244 | feature: authenticate RBAC requests

.rhcicd/pr_check.sh
The email connector needs to be set in the extra deployment arguments of the PR check in order for Clowder to deploy it when running the tests.
[[RHCLOUD-28161]](https://issues.redhat.com/browse/RHCLOUD-28161)
=>  RHCLOUD-28161 | feature: email connector in the PR check

common/pom.xml, engine/pom.xml
Our request body is seralized with `Object#toString` instead of Jackson, resulting in an invalid body being sent to the IT Users Service.
See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0#rest-client.
=> RHCLOUD-28340 Fix calls to the IT Users Service

connector-email/src/main/resources/application.properties, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java
Setting the "subtype" in the result endpoint causes the history stub to be stored with an "email_subscription" endpoint type and an "email" subtype, which causes the user interface in the event log page to break, since they do not rightfully expect a subtype when fetching a history element that is associated to an email endpoint.
=> RHCLOUD-28244 | refactor: rename the email connector

common-aggregator/src/main/java/com/redhat/cloud/notifications/models/EmailAggregation.java, database/src/main/resources/db/migration/V1.81.0__RHCLOUD-28341_email_aggregation_sequence.sql
Hibernate 6 changed the way sequences are incremented in the DB.
Our `email_aggregation_id_seq` sequence is currently lagging behind the actual `max(id)` from `email_aggregation` in stage.
This PR:
- changes the JPA annotations we use to declare the sequence, as per the [Hibernate 6 doc](https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators-sequence)
- aligns the sequence increment in the DB (50) with the `SequenceGenerator#allocationSize` default value
- resets the sequence value to the current `max(id)` from `email_aggregation`
It should fix the issue in stage and prevent it from happening in production 🤞
=> RHCLOUD-28341 Fix email aggregation DB sequence

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/connector/dto/EmailNotification.java
The email connector was not being able to extract the organization ID
from the payload because the engine was not sending it. That caused the
email connector not to send the organization ID to the RBAC service,
and that service ended up responding with a 401 instead of the response
we were expecting.
* https://github.com/RedHatInsights/notifications-backend/pull/2163
=> RHCLOUD-28244 | refactor: include the org ID in the payload for the email connector

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EventTypeRepository.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/TemplateRepository.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/RecipientResolver.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/TemplateRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
This PR introduces caching for DB data that rarely changes such as event types and templates.
It also suppresses unneeded calls to IT/RBAC/BOP when users from an org do not need to be retrieved.
=> RHCLOUD-28393 Lower time spent processing RBAC events

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/bop/ssl/BOPTrustManager.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java
We have this option set in the engine, and since the integration does not work without it, we are replicating it in the connector too.
[[RHCLOUD-28136]](https://issues.redhat.com/browse/RHCLOUD-28136)
=>  RHCLOUD-28136 | feature: trust all certificates when calling BOP

.rhcicd/clowdapp-connector-email.yaml, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparer.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparerTest.java
The backoffice proxy is returning a 404 at the moment because the path of the endpoint to send emails is wrong.
The reason for using those environment variable names which don't have the "NOTIFICATIONS_CONNECTOR" prefix is that they get set in AppInterface, and therefore we must honor that naming so that they get properly replaced when the connector gets deployed to stage or production.
=> RHCLOUD-28244 | fix: backoffice proxy's path

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java
Similar to how the BOP endpoint gets built, the IT endpoint needs to strip the schema from the URL in order to be able to build it properly, since otherwise the endpoint throws an exception once it gets used.
=> RHCLOUD-28244 | fix: IT service's URL generation

engine/src/main/java/com/redhat/cloud/notifications/processors/SystemEndpointTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/connector/dto/RecipientSettings.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailProcessorTest.java
The goal is to have the email processor fully tested.
* https://github.com/RedHatInsights/notifications-backend/pull/2163
* https://github.com/RedHatInsights/notifications-backend/pull/2164
[[RHCLOUD-28334]](https://issues.redhat.com/browse/RHCLOUD-28334)
=> RHCLOUD-28334 | feature: email processor tests

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java
The Apache Camel documentation[1] states a different way of setting a custom key store for the connections, which might be why our IT connection is failing with PKI errors in stage.
[1]: https://camel.apache.org/components/next/http-component.html#_setting_up_ssl_for_http_client
=> RHCLOUD-28244 | refactor: use key manager instead of a trust manager

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java
- These APIs are used internally, they are not really user friendly in any way. We should probably create other APIs if customers want to use these.
=> Hide user-preferences API

engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelNotification.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/slack/SlackNotification.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessorTest.java
This is phase 1 of a two-steps change:
- Phase 1: we're passing the top-level `orgId` field to all connectors from the `engine`
- Phase 2: after the `engine` has been deployed in production, we'll use the top-level `orgId` field from all connectors and stop using other sources of org ID
=> RHCLOUD-28235 Unify how org ID is passed to connectors

connector-common/pom.xml, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ConnectorConfig.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/EngineToConnectorRouteBuilder.java, connector-webhook/pom.xml, connector-webhook/src/main/java/com/redhat/cloud/notifications/connector/webhook/WebhookConnectorConfig.java, connector-webhook/src/main/java/com/redhat/cloud/notifications/connector/webhook/WebhookRouteBuilder.java, connector-webhook/src/main/resources/application.properties
After this PR, each connector can be migrated to SEDA separately with almost no effort.
=> RHCLOUD-27242 Move SEDA logic to connector-common module

connector-common/src/main/java/com/redhat/cloud/notifications/connector/IncomingCloudEventProcessor.java, connector-servicenow/src/main/java/com/redhat/cloud/notifications/connector/servicenow/ServiceNowCloudEventDataExtractor.java, connector-servicenow/src/test/java/com/redhat/cloud/notifications/connector/servicenow/ServiceNowCloudEventDataExtractorTest.java, connector-splunk/src/main/java/com/redhat/cloud/notifications/connector/splunk/SplunkCloudEventDataExtractor.java, connector-splunk/src/test/java/com/redhat/cloud/notifications/connector/splunk/SplunkCloudEventDataExtractorTest.java, engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessorTest.java
Camel case doesn't work well with Splunk and SNow, so we're switching to snake case in all connectors.
=> RHCLOUD-28235 Unify how org ID is passed to connectors (snake case)

connector-common/src/main/java/com/redhat/cloud/notifications/connector/IncomingCloudEventProcessor.java, connector-webhook/src/main/java/com/redhat/cloud/notifications/connector/webhook/WebhookCloudEventDataExtractor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java
⚠️ This PR must NOT be merged before https://github.com/RedHatInsights/notifications-backend/commit/7a6f441fcde150ee1f1ee59026540ac6f44a6a66 has been deployed in production.
From now on, connectors should always consume the org ID which is set here:
https://github.com/RedHatInsights/notifications-backend/blob/7a6f441fcde150ee1f1ee59026540ac6f44a6a66/engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java#L46
=> RHCLOUD-28235 Unify how org ID is passed to connectors (phase 2)

.rhcicd/build_deploy.sh
- Updates build deploy script to utilize `security compliance` image tag with format `sc-date-hash` this will make it easier to link the image tags. 
- Example: `sc-092723-7daece1`
=> Update build deploy script.

.rhcicd/clowdapp-backend.yaml, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java
This PR fixes warnings we've had in Sentry since the bump to Quarkus 3:
```
2023-09-27 15:53:37,476 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.opentelemetry.tracer.exporter.otlp.endpoint" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-09-27 15:53:37,479 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.opentelemetry.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
https://quarkus.io/version/3.2/guides/opentelemetry
=> Fix OpenTelemetry configuration keys

connector-email/pom.xml, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java
Calling to IT and RBAC services is a really expensive operation, and usually the responses are quite static. It makes sense to use caching for these usernames in order to avoid having to call for that data each time we need to send an email, specially when there is a huge batch of emails to be sent.
[[RHCLOUD-28138]](https://issues.redhat.com/browse/RHCLOUD-28138)
=> RHCLOUD-28138 | feature: cache the extracted usernames from IT and RBAC calls

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
The idea is to be able to check the status of the connector easily in the dashboard.
* [[RHCLOUD-28097]](https://issues.redhat.com/browse/RHCLOUD-28097)
* [[RHCLOUD-28096]](https://issues.redhat.com/browse/RHCLOUD-28096)
=> RHCLOUD-28097 | feature: update Grafana dashboard for the email connector

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/constants/ExchangeProperty.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparer.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsFilter.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparerTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsFilterTest.java
Basically the users cache was getting overwritten because we were modifying the users' collection directly when filtering it. Summarizing:
1) We created a collection for collecting the users.
2) Cached it.
3) Modified it in the recipients filter.
Since all this was made to the same collection, the cache was modified as a result.
Copying the collections fixes the issue.
[[RHCLOUD-28681]](https://issues.redhat.com/browse/RHCLOUD-28681)
=> RHCLOUD-28681 | fix: cache gets overwritten

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java
The connector issues a warning when sending requests to IT, because they try to set a cookie for a different domain which is also part of IT. Changing the cookie policy to "browser compatibility" might solve the issue.
[[RHCLOUD-28690]](https://issues.redhat.com/browse/RHCLOUD-28690)
=> RHCLOUD-28690 | fix: cookie policy warning

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java
The group principals results need to be cached as well to avoid calling RBAC too many times.
[[RHCLOUD-28138]](https://issues.redhat.com/browse/RHCLOUD-28138)
=> RHCLOUD-28138 | feature: cache the group principals results

.rhcicd/clowdapp-backend.yaml
The Floorist queries are giving indexing errors, apparently because some of the columns need to be converted to strings.
[[RHCLOUD-28708]](https://issues.redhat.com/browse/RHCLOUD-28708)
=> RHCLOUD-28708 | fix: Floorist queries give index error

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregatorTest.java
The current batch size leads to a huge memory consumption and `OutOfMemoryError` sometimes.
=> Lower the aggregation batch size and make it configurable from env var

.rhcicd/clowdapp-recipients-resolver.yaml, recipients-resolver/pom.xml, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/config/RecipientsResolverConfig.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/model/User.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/FetchUsersFromExternalServices.java, recipients-resolver/src/main/resources/application.properties, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/FetchUsersFromExternalServicesTest.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolverTest.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/itservice/ITUserServiceTest.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/rest/RecipientResolverResourceTest.java
- Shared retry policy declaration for all external services
- Shared failure counter var for all external services
- Shared configuration values for all external services
- `User#isActive` is gone
- `User#isAdmin` is primitive now (and renamed)
- ClowdApp template cleanup
- The `test` dependency on `notifications-common` is gone
=> Simplify recipients-resolver logic

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
:warning: Check the `Hide whitespace` option for a much easier review.
We recently moved the aggregation process from the `aggregation` topic to the `ingress` topic. The aggregation process is already slow and is bound to become even slower. We need to make sure it won't have any impact on our throughput and will never slow down our consumption rate with the `ingress` topic.
=> Run the aggregation process from a worker thread

.rhcicd/clowdapp-engine.yaml
This should help fix:
```
RecordTooLargeException
The message is 4021051 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
```
The size of each message is checked _before_ it is compressed and if it exceeds the `max.request.size` setting of the Kafka producer, the exception is thrown. The thing is we are compressing messages sent to `platform.notifications.tocamel`, so we can allow larger messages.
More details about this:
https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#max-request-size
https://issues.apache.org/jira/browse/KAFKA-4169
=> Increase max.request.size for platform.notifications.tocamel

.rhcicd/clowdapp-aggregator.yaml
#2218 removed Kafka entirely from the ClowdApp template while we still need the `ingress` topic.
=> Fix aggregator ClowdApp template

engine/src/main/resources/application.properties
This will fix:
```
2023-10-24 08:26:03,201 WARN  [io.sma.rea.mes.provider] (main) SRMSG00208: The connector 'IncomingConnector{channel:'aggregation', attribute:'mp.messaging.incoming.aggregation'}' has no downstreams
2023-10-24 08:26:03,805 WARN  [io.sma.rea.mes.provider] (main) SRMSG00207: Some components are not connected to either downstream consumers or upstream producers:
- IncomingConnector{channel:'aggregation', attribute:'mp.messaging.incoming.aggregation'} has no downstream
```
=> Remove aggregation config values from application.properties

.rhcicd/pr_check.sh
Until now, whenever we introduced a breaking change in a ClowdApp template and it broke some deployment in ephemeral, we had to deploy that template up to production before ephemeral could be fixed.
Starting now, deploying the new template in stage will be enough to fix ephemeral.
=> Use ClowdApp templates from stage in ephemeral

docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-connector-drawer.jvm, docker/Dockerfile.notifications-connector-email.jvm, docker/Dockerfile.notifications-connector-google-chat.jvm, docker/Dockerfile.notifications-connector-microsoft-teams.jvm, docker/Dockerfile.notifications-connector-servicenow.jvm, docker/Dockerfile.notifications-connector-slack.jvm, docker/Dockerfile.notifications-connector-splunk.jvm, docker/Dockerfile.notifications-connector-webhook.jvm, docker/Dockerfile.notifications-engine.jvm, docker/Dockerfile.notifications-recipients-resolver.jvm
When `-am` is used, Maven will automatically build modules that are dependencies of the current module.
=> Use Maven's --also-make option in Docker files

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmptyRecipientsTest.java
The recent 400s returned by BOP were caused by payloads we sent to BOP with an empty recipients list.
We have a check in `engine` which skips the call to the email connector if engine doesn't find any recipients in the DB and the users preferences are not ignored. However, when there are non-admin subscribers in the DB and the notification is targeting admins only, the connector was sending payloads with empty recipients to BOP, causing the 400.
=> RHCLOUD-29035 Stop calling BOP with an empty recipients list

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/InternalRoleAccessRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/UpdateApplicationRequest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/dto/ApplicationDTO.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/transformer/ApplicationDTOTransformer.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/InternalRoleAccessRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/models/transformer/ApplicationDTOTransformerTest.java
The front end requires visualizing the owner roles for the applications. These changes satisfy that requirement.
[[RHCLOUD-21638]](https://issues.redhat.com/browse/RHCLOUD-21638)
=>  RHCLOUD-21638 | feature: include the roles when returning applications

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailCloudEventDataExtractor.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/constants/ExchangeProperty.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/model/settings/RecipientSettings.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparer.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailCloudEventDataExtractorTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderRHCLOUD28631SingleEmailPerUserTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderRHCLOUD28631Test.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparerTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/it/ITUserRequestPreparerTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/RBACPrincipalsRequestPreparerProcessorTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/rbac/RBACUsersProcessorTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsFilterTest.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/connector/dto/RecipientSettings.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/RecipientSettings.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/request/ActionRecipientSettings.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/request/EndpointRecipientSettings.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/RecipientResolverTest.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/model/RecipientSettings.java
`recipients.emails` will only be used when the email connector is active and `NOTIFICATIONS_CONNECTOR_BOP_SKIP_USERS_RESOLUTION == true`. I'm not updating the old email logic in `engine`.
=> RHCLOUD-29101 Introduce recipients.emails field

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/SubscriptionRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java, backend/src/test/java/com/redhat/cloud/notifications/CrudTestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/InternalPermissionsServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/InternalResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/TemplateResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/EventType.java, database/src/main/resources/db/migration/V1.87.0__RHCLOUD-29084_event_types_subscribed_by_default.sql, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/SubscriptionRepository.java, engine/src/main/java/com/redhat/cloud/notifications/processors/SystemEndpointTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailProcessorTest.java
This PR introduces `EventType#subscribedByDefault` but does not make use of that field yet. The intent here is to keep the existing email or drawer behaviors unchanged while preparing for the event types subscribed by default.
Here are the major changes you'll find while reviewing:
- The event types can be created/updated from the internal REST API to set `subscribedByDefault` to `true`.
- If an event type is subscribed by default in the DB, the user preferences will reflect that immediately. But we won't do that until everything's ready (next PR).
- `SubscriptionType#subscribedByDefault` has precedence over `EventType#subscribedByDefault`. This could be debated (or changed later) but for the time being, it will work for all our use cases.
- We no longer delete from the DB any …
=> RHCLOUD-29084 Introduce EventType#subscribedByDefault

backend/src/test/java/com/redhat/cloud/notifications/routers/internal/models/transformer/ApplicationDTOTransformerTest.java
Default LocalDateTime.toString() method keeps last digit when it ends with 0, but DateTimeFormatter.ISO_DATE_TIME (used on DTO converter) don't.
=> Fix one test instability when nanos ends with 0

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsResolverPreparer.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/pojo/RecipientsQuery.java, engine/src/main/java/com/redhat/cloud/notifications/processors/SystemEndpointTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/RecipientResolver.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/recipientsresolver/ExternalRecipientsResolver.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/recipientsresolver/pojo/RecipientsQuery.java, engine/src/test/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/RecipientResolverTest.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolver.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/rest/RecipientsResolverResource.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/rest/pojo/RecipientsQuery.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolverTest.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/rest/RecipientResolverResourceTest.java
- `isOptIn` is now gone and replaced with `subscribedByDefault` everywhere
- recipients-resolver queries are simpler (getters, setters, equals and hashCode were not really needed)
- recipients-resolver queries are now serialized using snake case
⚠️ Keep in mind while reviewing that `isOptIn == !subscribedByDefault`.
=> RHCLOUD-29084 Get rid of isOptIn for good

common/src/main/java/com/redhat/cloud/notifications/StartupUtils.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, connector-email/src/main/resources/application.properties
Fixes several exceptions, including:
```
Caused by: java.util.NoSuchElementException: SRCFG00040: The config property quarkus.rest-client.export-service.url is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.Converters$BuiltInConverter
```
=> Fix startup exceptions in special environment

.github/workflows/platsec-aggregator.yml, .github/workflows/platsec-backend.yml, .github/workflows/platsec-connector-drawer.yml, .github/workflows/platsec-connector-email.yml, .github/workflows/platsec-connector-google-chat.yml, .github/workflows/platsec-connector-microsoft-teams.yml, .github/workflows/platsec-connector-servicenow.yml, .github/workflows/platsec-connector-slack.yml, .github/workflows/platsec-connector-splunk.yml, .github/workflows/platsec-connector-webhook.yml, .github/workflows/platsec-engine.yml, .github/workflows/platsec-recipients-resolver.yml
This PR changes the way PlatSec scans are triggered:
- they are disabled in drafts
- as soon as a draft is marked as ready for review, the PlatSec scans are executed
This lowers the number of GitHub actions runners we're using in drafts while still making sure PRs are scanned before they're merged.
=> Skip PlatSec scans on drafts

recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolver.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolverTest.java
When an application such as OCM provides a list of users (recipients) in its JSON payload, the `recipients-resolver` module will receive two `RecipientSettings` objects when an email is being sent: one for the email endpoint and the other one for the action built from the JSON payload. The former will contain an empty `users` field and the latter will contain the list provided in the payload.
Before this PR, `recipients-resolver` retrieved all users from the org regardless of the `users` field from the payload because of the empty `users` field from the email endpoint.
After this PR, the intersection of all `users` fields is first determined. Then, that intersection is used for all `RecipientSettings` objects, including the one from the email endpoint.
=> Use an intersection of users in recipients-resolver

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/SourcesSecretsMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/SourcesSecretsMigrationServiceTest.java
The team decided that we are going to run the migrations again but disabling endpoints this time, so that if clients want to keep using the, what now are invalid endpoints, will have to enable them manually and correct the bits that are incorrect.
[[RHCLOUD-24734]](https://issues.redhat.com/browse/RHCLOUD-24734)
=> RHCLOUD-24734 | feature: disable unmigratable endpoints

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/constants/ExchangeProperty.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/metrics/EmailMetricsProcessor.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparer.java
This PR introduces metrics which will give us a better vision of how many email requests we send to the email service and how email messages we send to the end users.
=> Introduce email connector metrics

engine/src/main/resources/templates/OCM/clusterUpdateInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/genericInstantEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOcmTemplate.java
Ocm email templates, use subjet value as title if title property is empty
=> [RHCLOUD-28935] Ocm email templates, use subjet value as title

engine/src/main/resources/templates/OCM/clusterUpdateInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/genericInstantEmailBodyV2.html
This PR changes
```
Thank you for choosing Red Hat OpenShift .
```
to
```
Thank you for choosing Red Hat OpenShift.
```
when the OCM payload doesn't contain a `subscription_plan` value.
=> Remove whitespace from OCM templates footer

engine/src/main/resources/application.properties
Fixes
```
18:38:33 #10 37.45 [WARNING] [io.quarkus.config] Unrecognized configuration key "quarkus.cache.caffeine.bundle.by.id.expire-after-write" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
=> Fix cache config

.rhcicd/sonarqube/Dockerfile
PostgreSQL RPM repository GPG key update - 3 January 2024
Check [this](https://yum.postgresql.org/news/pgdg-rpm-repo-gpg-key-update/) for more details
=> Update Postgres GPG keys for sonar integration

engine/src/main/java/com/redhat/cloud/notifications/templates/DrawerTemplateMigrationService.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Rbac/requestAccessEmailBodyV2.html, engine/src/main/resources/templates/Rbac/tamAccessRequestEmailBodyV2.html, engine/src/main/resources/templates/Rbac/tamAccessRequestEmailTitleV2.txt, engine/src/main/resources/templates/drawer/Rbac/tamAccessRequest.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestRbacTemplate.java
Adding email templates for new event type: rh-new-tam-request-created.
https://issues.redhat.com/browse/RHCLOUD-25247
=> Add email template for TAM event type

.rhcicd/pr_check.sh
Instead of adding the components in the "extra deploy arguments", we can specify them in a dedicated environment variable instead, which makes the script easier to read.
[[RHCLOUD-30424]](https://issues.redhat.com/browse/RHCLOUD-30424)
=> RHCLOUD-30424 | refactor: specify the components that need resources in an env var

.rhcicd/clowdapp-connector-drawer.yaml, .rhcicd/clowdapp-connector-email.yaml, .rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml, .rhcicd/clowdapp-connector-servicenow.yaml, .rhcicd/clowdapp-connector-slack.yaml, .rhcicd/clowdapp-connector-splunk.yaml, .rhcicd/clowdapp-connector-webhook.yaml, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ConnectorConfig.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/EngineToConnectorRouteBuilder.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ExceptionProcessor.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ExchangeProperty.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/IncomingCloudEventProcessor.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/IncomingKafkaReinjectionHeadersProcessor.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/KafkaHeader.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/KafkaReinjectionProcessor.java, connector-common/src/test/java/com/redhat/cloud/notifications/connector/ConnectorRoutesTest.java, connector-common/src/test/java/com/redhat/cloud/notifications/connector/IncomingCloudEventProcessorTest.java, connector-common/src/test/java/com/redhat/cloud/notifications/connector/IncomingKafkaReinjectionHeadersProcessorTest.java, connector-common/src/test/java/com/redhat/cloud/notifications/connector/KafkaReinjectionProcessorTest.java, connector-drawer/src/test/java/com/redhat/cloud/notifications/connector/drawer/DrawerConnectorRoutesTest.java
Another of the improvements for our fault tolerance is to reinject the notifications in the incoming Kafka queue again. By applying a non blocking delay, we ensure that also the connectors will not clog or stop processing more messages while the failed one is waiting to be reinjected.
[[RHCLOUD-28888]](https://issues.redhat.com/browse/RHCLOUD-28888)
=> RHCLOUD-28888 | feature: reinject failed Kafka messages to the channel

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/BasicAuthentication.java
We are moving towards not returning the credentials to the users, and the first step we want to make is to simply remove them from the payloads we return when listing the endpoints.
RHCLOUD-27431
=> RHCLOUD-27431 | refactor: return credentials redacted

common/src/main/java/com/redhat/cloud/notifications/models/WebhookProperties.java, database/src/main/resources/db/migration/V1.94.0__RHCLOUD-29443_remove_secrets_columns.sql
After migrating all the secrets to sources, we decided that it was time to remove both the database columns for the secrets and the feature flag, since storing secrets in Sources is going to be enabled by default.
* https://github.com/RedHatInsights/notifications-backend/pull/2350 
[[RHCLOUD-29443]](https://issues.redhat.com/browse/RHCLOIUD-29443)
=> feature: remove the secrets' columns from the database

.rhcicd/clowdapp-backend.yaml
The change has removing internal accounts from results as the goal.
[[RHCLOUD-31231]](https://issues.redhat.com/browse/RHCLOUD-31231)
=> RHCLOUD-31231 | feature: filter internal RH accounts from results

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/EngineConfig.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/TemplateRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/ConnectorReceiver.java, engine/src/main/java/com/redhat/cloud/notifications/health/KafkaConsumedTotalChecker.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailActorsResolver.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/eventing/EventingProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/test/java/com/redhat/cloud/notifications/EmailTemplatesInDbHelper.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorOpenShiftTemplate.java
This PR moves most of the `engine` feature flags to Unleash. Some flags are not moved because they're no longer used in any environment.
We'll transition from env vars to Unleash in several steps because some special environments may not support Unleash yet. That's why `FeatureFlipper` is still present and, for now, enabled by default.
Unleash is not integrated in the unit tests yet. This will come in a subsequent PR.
=> RHCLOUD-28460 Move engine feature flags to Unleash

.rhcicd/clowdapp-backend.yaml
We got asked about how many endpoint types does an organization have, and if they are enabled, active or not.
=> feature(query): endpoint types group per organization

.rhcicd/clowdapp-backend.yaml
Counts the number of behavior groups associated to event types per organization, and also includes the associated bundle and the event type to them.
=> RHCLOUD-22071 | feature(query): behavior groups associated to event types per org id

.rhcicd/floorist/floorplan.yaml
The template name for Floorist should be different than the one for the back end. I forgot to change it.
[[RHCLOUD-31337]](https://issues.redhat.com/browse/RHCLOUD-31337)
=> RHCLOUD-31337 | fix: the template name is clashing with the backend's one

engine/src/main/java/com/redhat/cloud/notifications/EngineConfig.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailActorsResolver.java
This should allow us to enable the HCC email sender name for selected orgs only.
=> RHCLOUD-31375 Test an Unleash activation strategy based on orgId

.rhcicd/floorist/floorplan.yaml
The Business Insights team cannot properly index the columns which have spaces on them, so the goal of these changes is to replace them with underscores. And since we're at it, in order to make it consistent everywhere and with every query, we are also naming all the columns in lowercase.
[[RHCLOUD-31387]](https://issues.redhat.com/browse/RHCLOUD-31387)
=> RHCLOUD-31387  | fix: column names not being read due to the spaces

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/TemplateRepository.java
We have a FileSystemNotFoundException - getFileSystem on stage.
This PR change the way we use the classLoader context according Quarkus recommendation : https://quarkus.io/guides/class-loading-reference
=> [RHCLOUD-31436] Fix default email template loading on stage

.rhcicd/floorist/floorplan.yaml
This query, without filtering the results by org ID, will help us identify how many behavior groups are associated to which event types.
=> feature(query): behavior groups associated to event types

database/src/main/resources/db/migration/V1.96.0__RHCLOUD-29443_remove_secrets_columns.sql
After marking the "bearer token" property as "@Transient", and deploying that change, it is time to remove the column from the database.
[[RHCLOUD-29443]](https://issues.redhat.com/browse/RHCLOUD-29443)
=> RHCLOUD-29443 | feature: remove the bearer authentication column from the database

connector-common-http/src/main/java/com/redhat/cloud/notifications/connector/http/HttpConnectorConfig.java
Fixes
```
notifications-connector-null.disable-faulty-endpoints.enabled=true
```
which happened because the toggle name was built before the config was injected.
=> RHCLOUD-28460 Fix connectors toggle name

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Inventory/newSystemRegisteredEmailBodyV2.html, engine/src/main/resources/templates/Inventory/newSystemRegisteredEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java
Adds the "new system registered" instant email template for the
Inventory application.
[[RHINENG-7841]](https://issues.redhat.com/browse/RHINENG-7841)
=>  RHINENG-7841 | feature: "new system registered" template for Inventory

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Inventory/systemDeletedEmailBodyV2.html, engine/src/main/resources/templates/Inventory/systemDeletedEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java
Adds the "inventory system deleted" template.
* https://github.com/RedHatInsights/notifications-backend/pull/2529
[[RHINENG-7838]](https://issues.redhat.com/browse/RHINENG-7838)
=> RHINENG-7838 | feature: Inventory system deleted

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Inventory/systemBecameStaleBodyV2.html, engine/src/main/resources/templates/Inventory/systemBecameStaleTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java
Adds the "system became stale" template.
* https://github.com/RedHatInsights/notifications-backend/pull/2532
[[RHINENG-7834]](https://issues.redhat.com/browse/RHINENG 7834)
=> RHINENG 7834 | feature: Inventory system became stale template

engine/src/main/java/com/redhat/cloud/notifications/routers/ReplayResource.java
Without that fetch, `EndpointProcessor` will silently do nothing.
=> Fetch the event type during notification replay

.rhcicd/floorist/floorplan.yaml
Counts the number of events per bundle, application and their status, and also adds another query to group them by organization ID too.
=>  RHCLOUD-22071 | feature(query): count the number of events and group them

common-unleash/src/main/java/com/redhat/cloud/notifications/unleash/LogLevelManager.java
Before this PR, the loggers level was not reset if the variant payload was `[]`.
I'm also aligning the code with the blog post.
=> RHCLOUD-31647 Reset loggers level when the variant payload is empty

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregator.java, engine/src/main/resources/templates/Inventory/dailyEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestSingleDailyTemplate.java
- Adds the required aggregation logic to be able to send the aggregated
daily digest emails with both the old and the new event types.
- Updates the daily digest email for the new Inventory events that we are
onboarding.
[[RHCLOUD-31525]](https://issues.redhat.com/browse/RHCLOUD-31525)
=> RHCLOUD-31525 | feature: Daily digest inventory emails

.rhcicd/clowdapp-backend.yaml
postgresql-rds "-1" images are being deprecated; moving to postgresql-rds:12 instead
=> refactor(dev): update postgresql-rds image tag

.rhcicd/floorist/floorplan.yaml
Removes the org ID filtering because the Business Insights team needs to have them in order to filter the internal ones from the results.
It also sorts the query names by alphabetical order to make it easier to locate them.
* https://github.com/RedHatInsights/notifications-backend/pull/2525
[[RHCLOUD-31648]](https://issues.redhat.com/browse/RHCLOUD-31648)
=> RHCLOUD-31648 | remove org id filtering

.rhcicd/floorist/floorplan.yaml
One of the queries was returning three "display_name" columns instead of having aliased names, and that was causing Floorist to break for having multiple columns in a data frame.
[[RHCLOUD-31927]](https://issues.redhat.com/browse/RHCLOUD-31927)
=> RHCLOUD-31927 | fix: Floorist queries giving error

.rhcicd/floorist/floorplan.yaml
Counts the number of received events from applications and groups them by bundle, application and organization ID.
=> RHCLOUD-22071 | feature: count the received events from apps

.rhcicd/floorist/floorplan.yaml
The tenants are requesting to see which endpoint type the notifications are being sent through.
[[RHCLOUD-27274]](https://issues.redhat.com/browse/RHCLOUD-27274)
=> RHCLOUD-27274 | feature(query): include endpoint types in the results

.dockerignore, .rhcicd/build_deploy.sh
* By generating a unique temporary directory for our builds, we ensure
that we will not share the workspace with the rest of the builds of the
platform.
* By explicitly ignoring the internal directories we ensure that we will
not copy them to our images by accident.
[[RHCLOUD-32001]](https://issues.redhat.com/browse/RHCLOUD32001)
=> RHCLOUD-32001 | Improve dockerfile builds

.rhcicd/clowdapp-aggregator.yaml, aggregator/src/main/java/com/redhat/cloud/notifications/DailyEmailAggregationJob.java
This PR changes the following:
- defaults the value for the prometheus push gateway. 
- This ensures that there will not be deployment errors if prometheus push gateway is not set in a cluster's env. 
The following error occurs if the value is not set.
```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to load config value of type class java.lang.String for: prometheus.pushgateway.url
```
=> Default  prometheus push gateway value.

.rhcicd/floorist/floorplan.yaml
Include the associated application and bundle to the event type.
[[RHCLOUD-27274]](https://issues.redhat.com/browse/RHCLOUD-27274)
=>  RHCLOUD-27274 | feature: include the associated bundle and app to the event type

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailActorsResolver.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailActorsResolverTest.java
We need to provide a way to override the email sender for different clusters than the commercial one.
[[RHCLOUD-31979]](https://issues.redhat.com/browse/RHCLOUD-31979)
=> RHCLOUD-31979 | feature: allow overriding the email sender

backend/pom.xml, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EndpointPage.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/model/Stats.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/models/mappers/v1/endpoint/EndpointMapperTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, backend/src/test/resources/json-schemas/v1/endpoint/endpoint-schema-create.json, backend/src/test/resources/json-schemas/v1/endpoint/endpoint-schema-read.json, backend/src/test/resources/json-schemas/v1/endpoint/implementations/create/endpoint-camel.json, backend/src/test/resources/json-schemas/v1/endpoint/implementations/create/endpoint-webhook.json, common/pom.xml, common/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/CompositeEndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/CreationTimestamped.java, common/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, common/src/main/java/com/redhat/cloud/notifications/models/EndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/SystemSubscriptionProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/WebhookProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/EndpointDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/EndpointStatusDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/EndpointTypeDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/CamelPropertiesDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/EndpointPropertiesDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/SystemSubscriptionPropertiesDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/WebhookPropertiesDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/secrets/BasicAuthenticationDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/mappers/v1/endpoint/EndpointMapper.java, pom.xml
Using DTOs will help us decouple the internal model from the model exposed to the clients, which will give us freedom to perform internal changes without fear of affecting anyone who is integrated with us.
[[RHCLOUD-31165]](https://issues.redhat.com/browse/RHCLOUD-31165)
=> RHCLOUD-31165 | feature: use DTOs for the Endpoint model

common/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/CompositeEndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/EndpointType.java, common/src/main/java/com/redhat/cloud/notifications/models/SystemSubscriptionProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/WebhookProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/EndpointTypeDTO.java
I removed all the annotations for the internal entities, because I assumed we had all the bases covered when I changed the response entity from "Endpoint" to "EndpointDTO" in all of the REST endpoints that we have.
However, there are some other endpoints that return some other entities like behavior groups, which also serialize endpoints. But they serialize the internal model's endpoint, not the DTO model's one. And since we are changing our model slowly by slowly, we decided not to create DTOs for our entire internal model in one single step, since it would be too much work and very hard to review.
Gwenneg suggested bringing the JSON serialization annotations back, and all the tests passed everywhere, but we faced another problem in the UI: it was breaking in certain calls where the …
=> RHCLOUD-31165 | fix: endpoint subentities not properly serialized

docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-connector-drawer.jvm, docker/Dockerfile.notifications-connector-email.jvm, docker/Dockerfile.notifications-connector-google-chat.jvm, docker/Dockerfile.notifications-connector-microsoft-teams.jvm, docker/Dockerfile.notifications-connector-servicenow.jvm, docker/Dockerfile.notifications-connector-slack.jvm, docker/Dockerfile.notifications-connector-splunk.jvm, docker/Dockerfile.notifications-connector-webhook.jvm, docker/Dockerfile.notifications-engine.jvm, docker/Dockerfile.notifications-recipients-resolver.jvm
We aleady removed it in the past (https://github.com/RedHatInsights/notifications-backend/pull/2725) then we restored it because the CVE was fixed on base image.
Unfortunately, a new cve on the same pip package was raised (https://github.com/RedHatInsights/notifications-backend/actions/runs/9256269567/job/25461895905?pr=2725)
=> Remove pip from base image

backend/src/test/java/com/redhat/cloud/notifications/models/mappers/v1/endpoint/EndpointMapperTest.java, backend/src/test/resources/json-schemas/v1/endpoint/endpoint-schema-read.json, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/EndpointDTO.java
I forgot to map the "updated" field in the DTO and that's why the mapper didn't pick it up to map it.
[[RHCLOUD-31165]](https://issues.redhat.com/browse/RHCLOUD-31165)
=> RHCLOUD-31165 | fix: Endpoint's "updated" field not included in payload

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Adds a couple of graphs for the Sources integration:
- Maximum time spent fetching secrets grouped by service.
- Number of fetched secrets by service.
[[RHCLOUD-32981]](https://issues.redhat.com/browse/RHCLOUD-32981)
=> RHCLOUD-32981 | feature: graphs for the Sources integration

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
The graph will allow checking at a glance the size of the payloads we are sending to Kafka from our engine pods.
[[RHCLOUD-33112]](https://issues.redhat.com/browse/RHCLOUD-33112)
=> RHCLOUD-33112 | feature: graph for the producers' sent bytes metric

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Adds a bunch of graphs for the bytes and messages intakes reported by the brokers.
[[RHCLOUD-33112]](https://issues.redhat.com/browse/RHCLOUD-33112)
=> RHCLOUD-33112 | feature: more input and output graphs for Kafka

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
The previous commit did not include all the Kafka topic graphs that I
had created in Grafana.
[[RHCLOUD-33112 ]](https://issues.redhat.com/browse/RHCLOUD-33112)
=> RHCLOUD-33112 | feature more kafka output metrics

engine/src/main/resources/templates/OCM/genericInstantEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOcmTemplate.java
This PR updates the switch statement in the footer of the OCM generic email to account for the requirements of ROSA Approved Access, where a particular message to customers is required.
=> OCM-7765 | feat: Update OCM generic template with additional footer for approved access

engine/src/main/resources/templates/Integrations/integrationDisabledBodyV2.html
https://issues.redhat.com/browse/RHCLOUD-30766
Update the text in the blue button at the bottom of the [integrations-disabled email](https://github.com/RedHatInsights/notifications-backend/blob/25b612fec66f365fc80148e407183cf74fac4c7a/engine/src/main/resources/templates/Integrations/integrationDisabledBodyV2.html) from "Open Integrations in Insights" to "Open Integrations".
Run IntegrationsTemplatesTest and place a breakpoint in [testIntegrationDisabledBodyWithClientError](https://github.com/RedHatInsights/notifications-backend/blob/33e60839a24741fcb5f1b2c5828a858a86c28989/engine/src/test/java/com/redhat/cloud/notifications/templates/IntegrationsTemplatesTest.java#L53) to manually validate the HTML. No automated test as I'm unsure if the HTML structure is stable.
=> [RHCLOUD-30766] Update the blue button text in the integration-disabled email template

engine/src/main/resources/templates/OCM/clusterUpdateInstantEmailBodyV2.html
The template clusterUpdateInstantEmailBodyV2.html contains a "Your" prefix for the event description. This can cause unexpected behaviour as it appends it to all events.
=> OCM-8731 | Remove "Your" from OCM cluster update template

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/test/java/com/redhat/cloud/notifications/TestConstants.java
https://issues.redhat.com/browse/RHCLOUD-29412
Adds a check when creating or updating ServiceNow and Splunk endpoints for a HTTPS URI scheme, throwing a BadRequestException otherwise.
- Added two wrapper tests for ServiceNow and Splunk, which call `testRequireHttpsScheme()`
- Validates that `http` endpoints are rejected when creating or updating a URL, and are accepted when `https` is used
- Validates that other Camel endpoints without an HTTPS requirement (ex. Slack) are not affected.
=> [RHCLOUD-29412] require HTTPS URLs for ServiceNow and Splunk endpoints

engine/src/main/resources/templates/OCM/genericInstantEmailBodyV2.html
This PR updates the OCM generic email template to correctly include the link to the ROSA Approved Access documentation in the footer section when the template_sub_ type is `ocm-approved-access-template`
=> OCM-7765 | chore: Updated the link to the Approved Access documentation in the OCM generic email template

.rhcicd/clowdapp-connector-email.yaml, .rhcicd/clowdapp-connector-slack.yaml, .rhcicd/stage-email-post-deployment-tests.yaml, .rhcicd/stage-slack-post-deployment-tests.yaml
This PR configures Email and Slack connectors for post-deploy testing
=> RHCLOUD-28721 | Onboard more connectors into post-deploy-testing

engine/src/main/resources/templates/Rbac/customGroupCreatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/customGroupUpdatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/customPlatformGroupUpdatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/customRoleCreatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/customRoleUpdatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/nonPlatformRoleUpdatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/platformGroupToCustomEmailBodyV2.html, engine/src/main/resources/templates/Rbac/platformRoleUpdatedEmailBodyV2.html, engine/src/main/resources/templates/Rbac/requestAccessEmailBodyV2.html, engine/src/main/resources/templates/Rbac/roleAddedToPlatformGroupEmailBodyV2.html, engine/src/main/resources/templates/Rbac/roleRemovedFromPlatformGroupEmailBodyV2.html, engine/src/main/resources/templates/Rbac/systemRoleAvailableEmailBodyV2.html
The links that customers are receiving were broken, and therefore when customers clicked on them they were redirected to pages that didn't exist.
[[RHCLOUD-32875]](https://issues.rehdat.com/browse/RHCLOUD-32875)
=> RHCLOUD-32875 | fix: the links for User Access are broken

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
https://issues.redhat.com/browse/RHCLOUD-31596
- Adds a new Boolean query parameter `excludeMutedTypes` to the /api/notifications/v1.0/notifications/eventTypes endpoint, which filters out event types that are [not associated with any behaviorGroup](https://github.com/cam-rod/notifications-backend/blob/9c6e51846d7b62a0a16fcfd8de3a2410fe6ed0e7/backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java#L302)
- Example: `GET /api/notifications/v1.0/notifications/eventTypes?excludeMutedTypes=true`
The new query parameter defaults to false and leaves current requests unmodified.
- Added `testEventTypeFetchingAndExcludeMutedTypes()` to validate that event types across different behaviour groups are included
- Added …
=> add filter for unmuted event types to endpoint `/notifications/eventTypes`

.rhcicd/clowdapp-backend.yaml, backend/pom.xml, backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselPermission.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/ResourcePermission.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/ResourceType.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/WorkspacePermission.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/producer/KesselClientsProducer.java, backend/src/main/java/com/redhat/cloud/notifications/auth/principal/rhid/RhServiceAccountIdentity.java, backend/src/main/java/com/redhat/cloud/notifications/auth/principal/rhid/RhUserIdentity.java, backend/src/main/java/com/redhat/cloud/notifications/config/BackendConfig.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProviderTest.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorizationTest.java, pom.xml
Integrates Kessel within Notifications, so that we use that as the authorization back end to build our internal Quarkus Security Identity.
In order to test this locally the following requirements must be met:
* Build the [relations-client-java](https://github.com/project-kessel/relations-client-java) locally.
* Launch Kessel with the following schema and test relations: https://play.authzed.com/s/_FPmZhrf-I06/schema
* Create an integration.
* Attempt to update it.
[[RHCLOUD-32502]](https://issues.redhat.com/browse/RHCLOUD-32502)
=> RHCLOUD-32502 | Kessel gRPC integration

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java
When dealing with the linked ticket, I initially started playing with the "endpoint creation" handler, and when I moved on to other handlers I forgot to return this handler's permissions back to the original ones.
https://github.com/RedHatInsights/notifications-backend/pull/2704
[[RHCLOUD-32502]](https://issues.redhat.com/browse/RHCLOUD-32502)
=>  RHCLOUD-32502 | fix: endpoint creation requires no permissions

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/exception/KesselExceptionMapper.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/exception/KesselExceptionMapperTest.java
When gRPC throws exceptions Quarkus simply returns the entire body of
the exception in the response to the client. It usually it is not useful
because it's hard to follow, and the client should not really receive
this kind of information.
This change logs the exception with all kinds of information and returns
an "internal server error" response to the client omitting the details
of what caused the error.
- https://github.com/RedHatInsights/notifications-backend/pull/2704
[[RHCLOUD-32502]](https://issues.redhat.com/browse/RHCLOUD-32502)
=> RHCLOUD-32502 | Kessel: proper exception handling

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessorTest.java
We are no longer storing Slack's channel when setting up a Slack endpoint, and that means that the "extras" object might be null or empty. We forgot to add a null check for that object which is causing some payloads to not be sent because of it.
[[RHCLOUD-33871]](https://issues.redhat.com/browse/RHCLOUD-33871)
=> RHCLOUD-33871 | fix: null pointer exception when the "extras" object is null

.rhcicd/clowdapp-connector-drawer.yaml, .rhcicd/clowdapp-connector-email.yaml, .rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml, .rhcicd/clowdapp-connector-servicenow.yaml, .rhcicd/clowdapp-connector-slack.yaml, .rhcicd/clowdapp-connector-splunk.yaml, .rhcicd/clowdapp-connector-webhook.yaml
https://issues.redhat.com/browse/RHCLOUD-31320
All connectors _(except email)_ now have between 40 and 70 threads available:
- 10x Slack threads, due to generous API limits and currently low count.
- 3x drawer threads (limit is unknown)
- 2.5x Splunk, ServiceNow, webhook threads
- 2x Gchat, Teams threads for lower API limits
- ~~7x email threads, due to high demand for aggregated reports~~ no change to email threads due to backend limits
How I decided on the new thread counts:
- Peak and average lag for the different connectors when sending notifications
- Current CPU/memory usage
- Current demand and expected near-term demand
- API rate limits
- while research was done on looking into rate limits for the APIs, it isn't the main driver for determining whether threads should be increased …
=> [RHCLOUD-31320] Increased number of connector threads

.rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml, .rhcicd/clowdapp-connector-servicenow.yaml, .rhcicd/clowdapp-connector-splunk.yaml, .rhcicd/clowdapp-connector-webhook.yaml, connector-common-http/src/main/java/com/redhat/cloud/notifications/connector/http/HttpConnectorConfig.java, connector-common-http/src/main/java/com/redhat/cloud/notifications/connector/http/HttpExceptionProcessor.java, connector-drawer/src/main/resources/application.properties, connector-email/src/main/resources/application.properties, connector-webhook/src/test/java/com/redhat/cloud/notifications/connector/webhook/WebhookConnectorRoutesTest.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/EndpointErrorFromConnectorHelper.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/EndpointErrorFromConnectorHelperTest.java
The feature has been enabled in production and it was worked flawlessly. Therefore, we can leave it as a permanent enabled feature in our application.
[[RHCLOUD-33637]](https://issues.redhat.com/browse/RHCLOUD-33637)
=>  RHCLOUD-33637 | refactor: remove toggle for the faulty endpoints

.rhcicd/floorist/floorplan.yaml
Adds a second FloorPlan that would collect data for building metrics on endpoint and event usage and store those to HMS S3 bucket.
The aggregated counts are group by a day, org, event types and endpoint types, and status. 
7 day window should be enough to cover any possible collection outages.
Note, that technically we can collect all notifications without the aggregation, but that could possibly generate a lot of data.
RHINENG-11314
=> RHINENG-11314: Collect metrics to HMS bucket

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
https://issues.redhat.com/browse/RHCLOUD-31596
This fixes issues with the original version of the `excludeMutedTypes` param on the `notifications/eventTypes` endpoint. The new version works as follows:
- Endpoint captures security context, and if the parameter is set to `excludeMutedTypes=true`, retrieves a list of event type IDs tied to an organization or default behavior group
- IDs are passed into the main query, and if parameter is set to true, will filter the list
The previous implementation listed event types linked to any behavior group globally, making it (almost) a no-op. This fix restores the intended functionality.
- `testEventFetchingAndExcludeMutedTypes` now also adds event types to a default behavior group, and to a different organization. Only event types assigned to …
=> [RHCLOUD-31596] Fix filtering for muted eventTypes

aggregator/src/main/java/com/redhat/cloud/notifications/config/AggregatorConfig.java
It has been enabled by default on the code and the toggle was not being used anywhere.
[[RHCLOUD-33638]](https://issues.redhat.com/browse/RHCLOUD-33638)
=> RHCLOUD-33638 | feature: remove single daily digest toggle

engine/src/main/resources/templates/Errata/bugfixEmailBodyV2.html, engine/src/main/resources/templates/Errata/enhancementEmailBodyV2.html, engine/src/main/resources/templates/Errata/securityEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/ErrataTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestErrataTemplate.java
Updates to the Errata  email body templates:
- Move advisory base URL to context to cut down on message size
- Update enhancement email body to read "Enhancements" rather than "Security updates."
=> Udpate errata email body templates

.rhcicd/clowdapp-backend.yaml
This would simplify the current configuration - it seems that the only reason we have this is because ephemeral had a different set of keys in the secret.  I checked yesterday and they provided both the old set of keys and the ones in the documentation [1].
This would require a followup to remove those parameters from the app-interface config once it has been deployed on their respective environment.
- Ephemeral and prod/stage use the same keys for the secret 
There is no longer a point in using a separate configuration
- Database name is provided by the secret (maybe before it was not)
[1] https://gitlab.cee.redhat.com/service/app-interface#manage-rds-databases-via-app-interface-openshiftnamespace-1yml
=> Update cronjob clowdapp properties

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
https://issues.redhat.com/browse/RHCLOUD-31596
The `api/notifications/v1.0/notifications/eventTypes?excludeMutedTypes=true` query parameter is slightly modified, so that event types associated with default behavior groups are no longer returned. This change is slightly inconsistent with other endpoints, which typically do consider default behavior groups. However, this allows for the endpoint to return a list of event types which the user is able to mute.
**Breaks compatibility** with the previous implementation (#2820), as event types associated with default behaviour groups will no longer be returned.
- Cases `testEventFetchingAndExcludeMutedTypes` and `testEventFetchingByBundleApplicationEventTypeNameAndExcludeMutedTypes` now verify that event types which are only associated with a …
=> [RHCLOUD-31596] Exclude eventType for default behavior groups

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java
We are suffering from timeouts in production when we attempt to modify or delete an existing bundle. This is due to the "events" table being huge, and the "bundle_id" column not being indexed.
Adding an index to that column for this purpose seems overkill for now, especially because these endpoints don't get used very often.
[[RHCLOUD-34047]](https://issues.redhat.com/browse/RHCLOUD-34047)
=> RHCLOUD-34047 | feature: incrase transaction timeouts for the bundles operations

engine/src/main/resources/templates/Errata/bugfixEmailBodyV2.html, engine/src/main/resources/templates/Errata/enhancementEmailBodyV2.html, engine/src/main/resources/templates/Errata/securityEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestErrataTemplate.java
Update the wording of subscription errata notifications to say that subscriptions are impacted rather than systems.l
=> Change wording from systems to subscriptions

pom.xml
Reverts RedHatInsights/notifications-backend#2843
=> Revert "Bump io.quarkiverse.logging.cloudwatch:quarkus-logging-cloudwatch from 6.9.0 to 6.11.0"

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java
Event log fetch is split into 3 SQL requests, it the first one has no results, we can skip 2 other requests because they will have no results as well
=> [RHCLOUD-34067] Avoid useless SQL requests

.rhcicd/clowdapp-connector-email.yaml, .rhcicd/clowdapp-engine.yaml, connector-common/src/main/java/com/redhat/cloud/notifications/connector/EngineToConnectorRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, connector-email/src/main/resources/application.properties, engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/processors/ConnectorSenderTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/eventing/EventingTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java
We are about to integrate with a tenant that is going to send millions
of events per day, and in order to avoid clogging our main Kafka topic
with those events alone, we are going to create:
1. A separate Kafka topic for those events.
2. Allow the email connector to enable consuming from the high volume Kafka
topic.
That way we will keep processing the regular events as normal, without
the high volume traffic affecting that flow.
[[RHCLOUD-34317]](https://issues.redhat.com/browse/RHCLOUD-34317)
=> RHCLOUD-34317 | Send high volume events to the new Kafka topic

connector-email/src/main/resources/application.properties, engine/src/main/resources/application.properties
We have seen that things don't break if the topic name is not correct. The email connector shows lots of warnings, but it keeps processing the events. The engine does not complain about it.
This means that until the high volume topic is enabled in other environments, we should not suffer from errors or crashloops.
[[RHCLOUD-34317]](https://issues.redhat.com/browse/RHCLOUD-34317)
=> RHCLOUd-34317 | refactor: correct the high volume Kafka topic names

database/src/main/resources/db/migration/V1.102.0__RHCLOUD-34808_reduce_event_retention_days.sql, engine/src/test/java/com/redhat/cloud/notifications/db/EventLogCleanerTest.java
We are reducing the event retention to 15 days to be able to handle the huge incoming load that we are about to face due to the TeamNado integration. The UI does not show more than 14 days, so we can safely reduce the event retention to 15 days. This way, we can be sure that all the timezones across the globe will have the 14 days of events available to be able to check them from the UI.
[[RHCLOUD-34808]](https://issues.redhat.com/browse/RHCLOUD-34808)
=> RHCLOUD-34808 | feature: reduce event retention days

pom.xml
Reverts RedHatInsights/notifications-backend#2882
=> Revert "Bump io.quarkiverse.logging.cloudwatch:quarkus-logging-cloudwatch from 6.9.0 to 6.12.0"

.rhcicd/clowdapp-engine.yaml, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, engine/src/main/java/com/redhat/cloud/notifications/config/EngineConfig.java, engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/test/java/com/redhat/cloud/notifications/processors/ConnectorSenderTest.java
The reason for the change is that this way we will be able to manually control when we enable and disable the production and consumption of messages in that topic.
[[RHCLOUD-34317]](https://issues.redhat.com/browse)
=> RHCLOUD-34317 | refactor: move the high volume topic env var to Unleash

.rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml
Backend set as an optional dependency will make clowder fill its details on the IQE pod while not modifying the deployment
=> RHCLOUD-28271 - Add backend as optional dependecy for testing

pom.xml
Fixes
```
[WARNING] Parameter 'encoding' is unknown for plugin 'maven-checkstyle-plugin:3.5.0:check (validate)'
```
=> Fix build warning

recipients-resolver/pom.xml, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/FetchUsersFromExternalServices.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/FetchUsersFromExternalServicesTest.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/MicrometerAssertionHelper.java
By reporting the total requests, the successes and the failures, we will be able to set up some alerts for when the external services we depend on start returning unsuccessful responses.
[[RHCLOUD-34830]](https://issues.redhat.com/browse/RHCLOUD-34830)
=> RHCLOUD-34830 | feature: generate accurate metrics for the recipients resolver

docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-connector-drawer.jvm, docker/Dockerfile.notifications-connector-email.jvm, docker/Dockerfile.notifications-connector-google-chat.jvm, docker/Dockerfile.notifications-connector-microsoft-teams.jvm, docker/Dockerfile.notifications-connector-servicenow.jvm, docker/Dockerfile.notifications-connector-slack.jvm, docker/Dockerfile.notifications-connector-splunk.jvm, docker/Dockerfile.notifications-connector-webhook.jvm, docker/Dockerfile.notifications-engine.jvm, docker/Dockerfile.notifications-recipients-resolver.jvm
The images build is currently unstable (timeouts). I'm trying to fix that.
- `microdnf update` is an alias for `microdnf upgrade` which is the actual command
- `--setopt=install_weak_deps=0`: prevents microdnf from installing additional packages (weak dependencies) we don't need
- `-y`: automatically answer yes for all questions
=> Fine-tune microdnf commands used while building images

engine/src/main/resources/templates/Errata/bugfixEmailBodyV2.html, engine/src/main/resources/templates/Errata/enhancementEmailBodyV2.html, engine/src/main/resources/templates/Errata/securityEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestErrataTemplate.java
Adds a security contact section to the bottom of the Errata email notification template for security, bugfix, and enhancement emails.
=> Add secalert contact information

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/errata/ErrataUserPreferencesMigrationResource.java, backend/src/test/resources/errata/subscriptions/errata_subscriptions.json
* The JSON key for the username is "user_name", and we were attempting to
parse the "username" key, which was causing exceptions.
* The exceptions are supposed to rollback the entire operation, so it is
simply safe to reuse the "try with resources" statement's "catch" block
to roll back the exception if any error occurs.
[[RHCLOUD-34459 ]](https://issues.redhat.com/browse/RHCLOUD-34459)
=> RHCLOUD-34459 | fix username json key

.rhcicd/stage-pagerduty-post-deployment-tests.yaml
https://issues.redhat.com/browse/RHCLOUD-33799
- Add service configuration of post-deploy tests for `notifications-connector-pagerduty`
- The marker `'notif_pagerduty and api'` has been commented out until the backend tests are implemented
No expected impact as per [Slack thread](https://redhat-internal.slack.com/archives/C024CDDPRHD/p1727103498109279)
cc: @Fynardo
=> [RHCLOUD-33799] Add disabled post-deploy tests for PagerDuty

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
In #2993 I accidentally swapped the order of the Splunk "Pods up" and "Restarts" panel. This PR fixes that, and also reverts a couple extraneous changes made in that PR (which cluster is "selected" and the default time range).
=> Fix Splunk pods up and restart Grafana panels

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/test/java/com/redhat/cloud/notifications/models/mappers/v1/endpoint/EndpointMapperTest.java, common/src/main/java/com/redhat/cloud/notifications/models/PagerDutyProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/PagerDutySeverity.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/PagerDutyPropertiesDTO.java, common/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/PagerDutySeverityDTO.java, connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutySeverity.java, connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyConnectorRoutesTest.java, engine/src/main/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessor.java
- Adds PagerDuty Endpoint to `EndpointRepository.createEndpoint` to be persisted
- Adds annotation `@Enumerated(EnumType.STRING)` to field `PagerDutyProperties#severity`
- Creates enum `PagerDutySeverityDTO` for properties DTO
- Fixes parsing of severity in `PagerDutyProcessor` (engine) and `PagerDutyTransformer` (connector) to ensure it remains in lowercase
=> Add PagerDuty to createEndpoint, fix severity enum

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/config/EngineConfig.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/OCM/capacityManagementInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/capacityManagementInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterAccessInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterAccessInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterAddOnInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterAddOnInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterConfigurationInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterConfigurationInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterLifecycleInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterLifecycleInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterNetworkingInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterNetworkingInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterOwnershipInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterOwnershipInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterScalingInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterScalingInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterSecurityInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterSecurityInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/clusterSubscriptionInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/clusterSubscriptionInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/customerSupportInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/customerSupportInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCM/generalNotificationInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/generalNotificationInstantEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/EmailTemplatesInDbHelper.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOcmRefactoredTemplates.java
Refactor OCM email templates to have a 1:1 mapping with event types
=> [RHCLOUD-33227] Refactor OCM email templates to have a 1:1 mapping

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
We recently switched to "gp3" storage which does not use the burst balance, so that metric can be removed. Also, since we are at it, I added the CloudWatch queries to the graphs so that we can directly go to AWS to check them.
[[RHCLOUD-34008]](https://issues.redhat.com/browse/RHCLOUD-34008)
=> RHCLOUD-34008 | feature: adapt the database Graphs

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/AbstractEmailPayloadAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregator.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregationProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/PatchEmailPayloadAggregatorTest.java
In some cases, Patch daily email section could be empty:
In those cases, it should not be included in the daily digest.
=> [RHCLOUD-35533] don't include empty patch daily digest section

.github/workflows/base-image-auto-update.yml
Use jq to query for image digest to remove the need to rely on skopeo inspect output having json keys in particular order. RHINENG-13679
=> fix(CI): use jq in checkimage

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselTestHelper.java, backend/src/test/java/com/redhat/cloud/notifications/db/QueryTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/model/Stats.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EmailsOnlyModeTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Implements the tests and the required helper classes to test making
authenticated and authorized requests while using Kessel as the
authentication and authorization back end.
- https://github.com/RedHatInsights/notifications-backend/pull/3032
[[RHCLOUD-33780]](https://issues.redhat.com/browse/RHCLOUD-33780)
=> RHCLOUD-33780 | feature: Kessel tests for the "EndpointResource"

connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyCloudEventDataExtractor.java, connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyConnectorRoutesTest.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformerTest.java
In testing I discovered that the `PagerDutyTransformer` (part of `notifications-connector-pagerduty`) failed to handle cases where optional fields were not provided. This PR fixes the handling of missing fields, and also adds a new `PagerDutyTransformerTest` class to validate it's handled gracefully.
=> Add additional validation for PagerDutyTransformer

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java
This was missing and caused a crash when trying to send notifications to PagerDuty.
=> Add PagerDutyProperties to EndpointRepository

connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/AuthenticationProcessor.java
The message body is already serialized by PagerDutyTransformer, so it needs to be decoded and then re-encoded.
=> Fix serialization in PagerDuty AuthenticationProcessor

backend/src/test/java/com/redhat/cloud/notifications/routers/EmailsOnlyModeTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/OrgConfigResourceTest.java
feature: tests for the Kessel Inventory integration
Tests that creating and deleting integrations also notifies Kessel
Inventory about it. We also test if the "@Transactional" methods work as
expected and that we will not be creating a desynchronization between
our database and the Kessel Inventory if we suffer from any kind of
errors. More precisely:
- When saving the integration in our database fails, we check that
Kessel does not get an "integration created" request.
- When we succesfully save an integration in our database but sending
the "integration created" request to Kessel fails, we check that the
whole transaction gets rolled back and no integration gets saved in
our database.
- When deleting the integration in our database fails, we check that
Kessel does not get an …
=> RHCLOUD-35769 | feature: Kessel inventory tests

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/Constants.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacServer.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/workspace/RbacWorkspace.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/workspace/WorkspaceType.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/workspace/WorkspaceUtils.java, backend/src/main/java/com/redhat/cloud/notifications/config/BackendConfig.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/OrgConfigResource.java, backend/src/test/java/com/redhat/cloud/notifications/MockServerConfig.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselTestHelper.java, backend/src/test/java/com/redhat/cloud/notifications/auth/rbac/workspace/WorkspaceUtilsTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EmailsOnlyModeTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/OrgConfigResourceTest.java, backend/src/test/resources/rbac-examples/workspaces/multiple-workspaces-response.json, backend/src/test/resources/rbac-examples/workspaces/single-default-workspace-response.json, backend/src/test/resources/rbac-examples/workspaces/single-root-workspace-response.json
In order to be able to check on users' permissions with Kessel, we need to know which workspace they are trying to act upon. And for now, RBAC is going to provide that information.
[[RHCLOUD-35479]](https://issues.redhat.com/browse/RHCLOUD-35479)
=> RHCLOUD-35479 | feature: fetch workspace IDs from RBAC

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/permission/WorkspacePermission.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointEventTypeRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java, common/src/test/java/com/redhat/cloud/notifications/TestConstants.java
These permissions are needed for when the integration with the Kessel Relations API is enabled. The Kessel permissions are derived from the existing ones, so in theory the old RBAC permissions should be mapped with the new ones we have specified here.
[[RHCLOUD-35813]](https://issues.redhat.com/browse/RHCLOUD-35813)
=> RHCLOUD-35813 | feature: implement Kessel permissions for the NotificationsResource

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java
We didn't handle properly the new data model sync when:
Some event types are removed from existing behavior groups using` /eventTypes/{eventTypeId}/behaviorGroups` api.
=> [RHCLOUD-34488] Fix sync between Behavior group and endpoint to event  types data models

backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/workspace/WorkspaceUtils.java, backend/src/test/java/com/redhat/cloud/notifications/MockServerConfig.java, backend/src/test/java/com/redhat/cloud/notifications/auth/rbac/workspace/WorkspaceUtilsTest.java, backend/src/test/resources/rbac-examples/workspaces/missing-count-response.json, backend/src/test/resources/rbac-examples/workspaces/no-workspaces-response.json
Handles a couple more failure cases that we might encounter when fetching the workspaces from RBAC.
[[RHCLOUD-35479]](https://issues.redhat.com/browse/RHCLOUD-35479)
=> RHCLOUD-35479 | feature: handle more failure cases when fetching RBAC workspaces

.rhcicd/clowdapp-backend.yaml, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAssets.java, backend/src/main/java/com/redhat/cloud/notifications/config/BackendConfig.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselAssetsTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
The issue has been fixed and the integration deletion works with Kessel, so it is safe to remove the feature flag.
[[RHCLOUD-35769]](https://issues.redhat.com/browse/RHCLOUD-35769)
=> RHCLOUD-35769 | refactor: remove integration deletion feature flag

backend/src/main/java/com/redhat/cloud/notifications/config/KesselConfigInterceptor.java, backend/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptor, backend/src/main/resources/application.properties
The previous configuration was pointing to the `localhost` URLs, so we needed to make sure that when using Clowder and the JSON configuration file, the proper URLs were being fed to build the Kessel clients.
However, the `clowder-quarkus-config-source` extension we use to resolve the properties always appends the `http` or `https` schemes to the URLs, and since the gRPC clients are expecting a `${HOSTNAME}:${PORT}` string, we had to implement a configuration interceptor to be able to fed the clients with the proper URLs.
[[RHCLOUD-35924]](https://issues.redhat.com/browse/RHCLOUD-35924)
=>  RHCLOUD-35924 | feature: read and intercept the Kessel clients' URLs

.rhcicd/clowdapp-backend.yaml
I forgot to inject the RBAC PSKS in the back end when I developed the workspaces bit for Kessel, and the RBAC team told us that we were using an invalid PSK.
[[RHCLOUD-35479]](https://issues.redhat.com/browse/RHCLOUD-35479)
=> RHCLOUD-35479 | refactor: inject the RBAC PSKS in the back end

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/OrgConfigResource.java
The goal of this method is to make it easier to use workspace permissions and reduce the potential mistakes when checking for permissions: since the method only takes the "WorkspacePermissions" enum, accidentally feeding it with the "IntegrationPermissions" enum will tell you that you might be assigning the wrong permission to the wrong resource.
[[RHCLOUD-35970]](https://issues.redhat.com/browse/RHCLOUD-35970)
=> RHCLOUD-35970 | refactor: add "hasPermissionOnWorkspace" method

.rhcicd/clowdapp-backend.yaml, backend/src/main/java/com/redhat/cloud/notifications/config/BackendConfig.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationServiceTest.java
Implements the required migration endpoint so that Kessel can import the
integrations from Notifications.
- https://github.com/RedHatInsights/notifications-backend/pull/3016
=> RHCLOUD-35454 | feature: Kessel bulk import

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationServiceTest.java
The old "status" has been changed so that we can use Unleash to control which URLs we are filtering, so the old references need to be removed.
I forgot to do it in the "Kessel bulk import" changes.
=> RHCLOUD-35454 | refactor: remove the "Status" references

.rhcicd/clowdapp-backend.yaml
The name of the ClowdApps is wrong, and that's why Clowder cannot find them to include them in our configuration files.
[[RHCLOUD-35924]](https://issues.redhat.com/browse/RHCLOUD-35924)
=> RHCLOUD-35924 | fix: name of the Kessel ClowdApps

.rhcicd/pr_check.sh
These components are deprecated and are going to be removed soon, so it makes no sense to have them here.
[[RHCLOUD-36188]](https://issues.redhat.com/browse/RHCLOUD-36188)
=>  RHCLOUD-36188 | refactor: remove deprecated components

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/resources/application.properties
Unless the "min-level" setting is set to "trace" for the Kessel package, we will not be able to set the logging level to that level using Unleash.
[[RHCLOUD-34485]](https://issues.redhat.com/browse/RHCLOUD-34485)
=> RHCLOUD-34485 | feature: let the Kessel log levels go down to "trace"

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAssets.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselAssetsTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, pom.xml
The back end requested a "workspace_id" field that was not present in the client's API. It turns out they needed to update the client, and in turn, we needed to update our implementation too.
[[RHCLOUD-34485]](https://issues.redhat.com/browse/RHCLOUD-34485)
=> RHCLOUD-34485 | feature: update API for Kessel Inventory's client

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/permission/WorkspacePermission.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorizationTest.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselTestHelper.java, backend/src/test/java/com/redhat/cloud/notifications/db/QueryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
In order to return consistent responses when an unauthorized principal
calls our APIs, we have decided as a team that we will return "not
found" responses.
The reasoning is that many existing services will not let you know
whether the resource exists or not if you are not authorized, so we
thought that following this pattern was a good idea.
[[RHCLOUD-35763]](https://issues.redhat.com/browse/RHCLOUd-35763)
=> RHCLOUD-35763 | feature: return proper authorization responses

engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java
The "payload size" metrics include the "orgId" tag, which incurs in a high cardinality because for every organization that we send a notification for we are generating an individual metric.
[[RHCLOUD-36426]](https://issues.redhat.com/browse/RHCLOUD-36426)
=> RHCLOUD-36426 | fix: high cardinality for the payload sizes

engine/src/main/resources/templates/Errata/securityEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/ErrataTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestErrataTemplate.java
This change adds a severity column for RHSA email notifications (not for RHEA or RHBAs), per CHAINSAW-6. Please refer to that ticket for a preview of the rendered HTML.
There is a corresponding back-end change to Errata Notifications (hosted on gitlab.cee) which updates the json messages we send to the notifications API. This changes in this MR rely on those back-end changes, so we need to coordinate deployment to production (and preferably stage as well, but that's less important.)
(In one test case I changed the severity from "Low" to "Important" to see how the larger word (and largest of the options) affected layout. This doesn't impact the tests, but I left it in as a convenience for when we inspect the layout in the future.)
=> Add severity column

.rhcicd/floorist/floorplan.yaml
The pods need a way to be able to adjust their resource requests and limits, in case they run out of resources while running.
[[RHCLOUD-36454]](https://issues.redhat.com/browse/RHCLOUD-36454)
=> RHCLOUD-36454 | feature: allow setting resource requests and limits for Floorist

backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacClientResponseFilter.java, backend/src/main/resources/application.properties
The goal is to be able to log the key requests and responses that we send, so that we can figure out what the problem is when calling RBAC.
The reason for implementing custom logging instead of using the [REST
Client's logging](https://quarkus.io/guides/rest-client#logging-traffic) is that we want to be able to log the requests only
when we receive a non "2xx" response, since otherwise it would produce
too much noise with all the successful requests that we send.
[[RHCLOUD-36553]](https://issues.redhat.com/browse/RHCLOUD-36553)
=> RHCLOUD-36553 | feature: log RBAC requests and responses

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java
The log message is not properly formatted and therefore it doesn't provide the information we intended to provide when things go wrong.
=> RHCLOUD-35454 | fix: incorrect logging for the Kessel migration service

backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/workspace/WorkspaceUtils.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java, backend/src/main/resources/application.properties
Having traces will allow us to know what is exactly happening when we run the migrations.
=> RHCLOUD-35454 | feature: enhance logging for the Kessel assets migration

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java
When we attempt to insert integrations that already exist in Kessel, we receive an error response from that operation. Activating the "upsert" flag when migrating will help us avoid that.
=> RHCLOUD-35454 | feature: upsert integrations instead of just inserting them

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java
The logs were improperly formatted and that was causing an exception, instead of giving us the expected log message.
=> RHCLOUD-35454 | fix: log formatting errors

backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacClientResponseFilter.java
There are certain failing RBAC requests which do not have headers, and when we try to log them, the code throws an exception because of course the map of requests is null, and we can't access its elements.
[[RHCLOUD-36553]](https://issues.redhat.com/browse/RHCLOUD-36553)
=> RHCLOUD-36553 | fix: RBAC requests without headers fail to be logged

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationServiceTest.java
When RBAC returned a non-200 response, and the "RbacService" class threw a "ClientWebApplicationException", the exception was not properly handled by the migration tool and it stopped the migration's execution.
The intended behavior from the beginning was to continue with the migration even when we faced these kind of errors.
=> RHCLOUD-35454 | fix: RBAC workspace exceptions stop the bulk import for Kessel

.rhcicd/stage-microsoft-teams-post-deployment-tests.yaml
There is a limitation on CJI names that they need to be shorter than 64 characters. 
Based on how CJI names are created, the Teams one gets up to 65 characters
=> Try to fix MSTeams post-deploy CJI as its name could be longer than permitted

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java
We want to avoid blocking Quarkus' event thread, and since the migration uses blocking calls, we want to make sure it does not get killed by Vert.x.
=> RHCLOUD-35454 | feature: run the Kessel migration in a virtual thread

.rhcicd/clowdapp-connector-drawer.yaml
Configures the iqePlugin so we can run tests in post-deploy jobs
Also adds the backend app as an optional dependency to avoid configuration problems
=> Configure post-deploy tests in Drawer connector

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/X509CertificateRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/ValidationResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/ValidationResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/X509CertificatesResourceTest.java
Curently, Notifications GW need to check baet (Bundle + Application + Event Type) existence to valid messages, and also to check certificate CN for tenants who could use their stage environment with Notifications Prod instance.
To get the GW resilient to a database outage/maintenance, we need to cache those data at GW startup, then refresh those periodically when Notifications Backend is available. (If it's not it will have to keep and work with initially loaded  data set)
=> [RHCLOUD-37354] add bulk resources for Notifications GW

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/SubscriptionRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/errata/ErrataEmailPreferencesUserIdFixService.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/SubscriptionRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/errata/ErrataEmailPreferencesUserIdFixServiceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/EventTypeEmailSubscription.java, common/src/main/java/com/redhat/cloud/notifications/models/EventTypeEmailSubscriptionId.java
We had a customer report where they complained that they were still receiving Errata notifications even after unsubscribing from them.
After investigating, we found out that we had multiple and even overlapping email subscriptions for almost the same username. By "almost", I mean that the username was essentially the same, but with different case. For example: UserA and usera.
Notifications takes all the email subscriptions' usernames and makes them lowercase to make a case insensitive comparison. Also, when user preferences are saved, the email subscriptions that are generated are generated with lowercase user IDs.
When we migrated the Errata email subscriptions, some of them contained mixed case user IDs, and we did not realize about that.
What ended up happening was:
- A customer was …
=> RHCLOUD-37310 | fix: rename email subscription user IDs to lowercase

connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformerTest.java, engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/google/chat/GoogleChatProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessorTest.java
https://issues.redhat.com/browse/RHCLOUD-22813
Currently, URLs in PagerDuty and Camel notifications are constructed by the PagerDutyTransformer, or one of three [Qute](https://quarkus.io/guides/qute) templates, respectively. Each one has a slightly different way of handling URLs, and the Camel templates are not the ones currently shown in this repo.
This PR creates a new class, `InsightsUrlsBuilder`, which provides consistent construction of the two URLs for all integrations:
- `data.inventory_url` represents a link to the specific host, cluster, or inventory item in the Console that generated the message. If `data.context.host_url` is provided, it will be used here.
- `data.application_url` links back to the application that generated the event.
The PR will also make it easy to modify …
=> [RHCLOUD-22813] Handle provided context.host_url in integration templates

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
https://issues.redhat.com/browse/RHCLOUD-37376
This replaces old Kafka metrics in Grafana, with new values pulled directly from AWS MSK, as per the migration.
Panel changes:
- _Kafka lag (messages):_ replaces instances of `kafka_consumergroup_group_lag_seconds` with `aws_kafka_sum_offset_lag_sum`, pulled from the CloudWatch Exporter clusters (based on `SumOffsetLag`)
- _Kafka lag (seconds):_ **REMOVE** panel, as AWS does not provide a suitable replacement metric ([relevant Slack message](https://redhat-internal.slack.com/archives/C07FQ00BJV8/p1737623526313699?thread_ts=1737567199.373179&cid=C07FQ00BJV8))
- _Kafka lag (seconds)_ panel is removed
Fun story, because Grafana is provisioned, I'm unable to reupload the JSON file to check if my changes are correct. I was able to get most of the …
=> [RHCLOUD-37376] Replace Kafka lag metrics with AWS MSK metrics

connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java
https://issues.redhat.com/browse/RHCLOUD-22813
Adjust wording in upcoming PagerDuty messages, removes `"Open "` from the title of the Client (Application) URL.
Example of behaviour to be corrected:
=> [RHCLOUD-22813] Adjust wording for PD Client title

.rhcicd/clowdapp-backend.yaml, backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/java/com/redhat/cloud/notifications/config/BackendConfig.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorizationTest.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselTestHelper.java
We were getting reports of integrations not showing up in stage when Kessel Relations was enabled. More specifically, the issue was that after trying to filter integrations by name, some of them did simply not show up in the results even though they were recently created.
After investigating the issue, it turned out that the problem was that we were getting an incomplete set of authorized integration IDs from Kessel, which in turn made us filter the database query results incorrectly, which again, in turn, made us return an inaccurate list of integrations for an organization.
The QE organization which reported the issue had around 2,500 integrations created, and when a request was made to look up for a very specific integration with name "X", Notifications first had to ask Kessel for the …
=> RHCLOUD-37430 | fix: integrations are not being returned sometimes

.rhcicd/floorist/floorplan.yaml
The queries have been adapted to the latest refactors that Notifications has gone through, and also to be flexible enough to answer any questions that we have been asked by PMs and stakeholders.
[[RHCLOUD-27274]](https://issues.redhat.com/browse/RHCLOUD-27274)
=> RHCLOUD-27274 | feature: improve data reporting for Notifications

connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java, connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformerTest.java, database/src/main/resources/db/migration/V1.111.0__RHCLOUD-22813_update_template_host_app_urls.sql, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/google/chat/GoogleChatProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/slack/SlackProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessorTest.java
https://issues.redhat.com/browse/RHCLOUD-22813
This is the second part of #3221, splitting the two breaking changes into a separate PR:
- The removal of `data.environment_url` from `EngineToConnector` messages for PagerDuty and CamelProcessor (Google Chat, Slack, Microsoft Teams)
- Updating the Qute template to the new format described in the other PR, in database migration `V1.111.0`
> [!NOTE]
>
> **One change has been made to the existing format:** Camel messages no longer contain a leading `\n`. This caused unexpected failures while testing the Slack processor, and weirdly did not fail with the Teams processor when it should have.
=> [RHCLOUD-22813] Message link migration

backend/src/main/java/com/redhat/cloud/notifications/db/builder/QueryBuilder.java
The log statement was part of an old debug session and it is not used anymore.
=> refactor: remove unnecessary log

common/src/main/java/com/redhat/cloud/notifications/models/Event.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
Changes introduced by [this PR](https://github.com/RedHatInsights/notifications-backend/pull/3258/files#diff-6bd9650840a80f42278e08cae86b7f1510368200c2114a93a848b62e233cf3a5) breaks message processing during deployment phase, because SQL and java code using updates are not deploy in the same single module.
=> [RHCLOUD-37537] Separate SQL upgrades and Engine updates

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationRequest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationServiceTest.java
The feature allows the requester to specify an organization ID if they want to just migrate that organization, or to leave it empty to migrate the whole database.
[[RHCLOUD-37782]](https://issues.redhat.com/browse/RHCLOUD-37782)
=> RHCLOUD-37782 | feature: restrict Kessel Assets' migration to a specific org

backend/src/main/java/com/redhat/cloud/notifications/auth/annotation/Authorization.java, backend/src/main/java/com/redhat/cloud/notifications/auth/annotation/AuthorizationInterceptor.java, backend/src/main/java/com/redhat/cloud/notifications/auth/annotation/IntegrationId.java, backend/src/main/java/com/redhat/cloud/notifications/auth/annotation/ParameterIndexes.java, backend/src/test/java/com/redhat/cloud/notifications/auth/annotation/AuthorizationInterceptorHelper.java, backend/src/test/java/com/redhat/cloud/notifications/auth/annotation/AuthorizationInterceptorTest.java, backend/src/test/java/com/redhat/cloud/notifications/auth/kessel/KesselTestHelper.java
The implemented annotation allows specifying the legacy RBAC role that will be used when RBAC is enabled, and the Kessel permissions for when that one is being used as the authorization back end.
The goal is to reduce the boilerplate and repetitive code that we have in the codebase, and make it easier for the developers to add authorization in a similar way that it is done with the "RolesAllowed" annotation.
```java
@Authorization(
legacyRBACRole = ConsoleIdentityProvider.RBAC_ROLE,
integrationPermissions = {IntegrationPermission.VIEW},
workspacePermissions = {WorkspacePermission.BUNDLES_VIEW, WorkspacePermission.APPLICATIONS_VIEW}
)
public void method(final SecurityContext securityContext, /* ... more params ... */, @IntegrationId final UUID id) {
}
``` …
=> RHCLOUD-37536 | feature: authorization annotation for improved maintainability

backend/src/main/java/com/redhat/cloud/notifications/routers/engine/GeneralCommunicationsService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/dto/SendGeneralCommunicationRequest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/InternalResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/routers/general/communication/SendGeneralCommunicationResponse.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/GeneralCommunicationsHelper.java, engine/src/main/java/com/redhat/cloud/notifications/events/IntegrationDisabledNotifier.java, engine/src/main/java/com/redhat/cloud/notifications/routers/GeneralCommunicationsResource.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Integrations/generalCommunicationBodyV2.html, engine/src/main/resources/templates/Integrations/generalCommunicationTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/routers/GeneralCommunicationsResourceTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/IntegrationsTemplatesTest.java
The goal of this feature is to be able to send general communications from Red Hat to the customers. We idea is to have all the parts ready and to just modify the template accordingly whenever it is necessary.
- An internal REST service is available now in the back end.
- This service calls to another REST service in the engine, which injects an event of the `general-communication` type in the "ingress" Kafka channel.
[[RHCLOUD-37937]](https://issues.redhat.com/browse/RHCLOUD-37937)
=> RHCLOUD-37937 | feature: send general notifications to customers

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleAuthMechanism.java
When Kessel is enabled, the requests that were authenticated with
Turnpike end up being "unauthorized". In order to help with the
debugging, we are adding a log statement to debug how the incoming
identity headers look like, so that we can adapt our code to them.
=> refactor: log the "x-rh-identity" header

.rhcicd/floorist/floorplan.yaml
The addition of the field is causing the scraping scripts to break, so until the field can be handled by those scripts, we need to remove it.
[[RHCLOUD-38465]](https://issues.redhat.com/browse/RHCLOUD-38465)
=> RHCLOUD-38465 | fix: email subscriptions not reported in Tableau

backend/src/test/java/com/redhat/cloud/notifications/routers/handlers/endpoint/EndpointResourceTest.java
Add test coverage on Kessel Inventory call during system endpoint creation
=> [RHCLOUD-37943] Add test coverage on Kessel Inventory call during system endpoint creation

engine/src/main/java/com/redhat/cloud/notifications/processors/ConnectorSender.java, engine/src/test/java/com/redhat/cloud/notifications/processors/ConnectorSenderTest.java
Today, only email connector is listening internal Kafka High volume topic.
This choice could be revisited in the future regarding what kind of integration type could be enabled by default for all users.
=> [RHCLOUD-38675] Currently, high volume topic is usable only for email notifications

backend/src/main/java/com/redhat/cloud/notifications/models/dto/v1/endpoint/properties/WebhookPropertiesDTO.java, backend/src/test/java/com/redhat/cloud/notifications/models/mappers/v1/endpoint/EndpointMapperTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/handlers/endpoint/EndpointResourceTest.java, database/src/main/resources/db/migration/V1.114.0__RHCLOUD-32168_set_webhook_method_post.sql
We only send "POST" requests to clients with the details of the notifications, so it does not make sense to allow customers to create webhook integrations with any other method in their properties.
[[RHCLOUD-32168]](https://issues.redhat.com/browse/RHCLOUD-32168)
=> RHCLOUD-32168 | fix: webhook properties can be created with any HTTP method

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregatorTest.java
Some tenants send `context` and `events[].payload` data as Json string instead of Json object.
Json transformer used by new aggregation logic must be more permissive to support this format.
=> [RHCLOUD-39099] New Aggregation logic can't parse misformated payloads

aggregator/src/main/java/com/redhat/cloud/notifications/db/EmailAggregationRepository.java
New aggregation logic covers only two days in the past, which is more than enough for a daily aggregation.
The Old aggregation logic don't have minimal date, so in case of org with low activity, the and aggregation command could contain a start date sevral days in the past, even if there is nothing to aggregate until today.
=> [RHCLOUD-39047] Reduce aggregation command trigger noise

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java
Remove exessive useless log entry.
It also generate some clowdwatch exception because its volume could be higher than CW batch limit.
=> Reduce alert noise clowdwatch exception: remove excessive log

.tekton/notifications-aggregator-pull-request.yaml, .tekton/notifications-aggregator-push.yaml, .tekton/notifications-backend-pull-request.yaml, .tekton/notifications-backend-push.yaml, .tekton/notifications-connector-drawer-pull-request.yaml, .tekton/notifications-connector-drawer-push.yaml, .tekton/notifications-connector-email-pull-request.yaml, .tekton/notifications-connector-email-push.yaml, .tekton/notifications-connector-google-chat-pull-request.yaml, .tekton/notifications-connector-google-chat-push.yaml, .tekton/notifications-connector-microsoft-teams-pull-request.yaml, .tekton/notifications-connector-microsoft-teams-push.yaml, .tekton/notifications-connector-pagerduty-pull-request.yaml, .tekton/notifications-connector-pagerduty-push.yaml, .tekton/notifications-connector-servicenow-pull-request.yaml, .tekton/notifications-connector-servicenow-push.yaml, .tekton/notifications-connector-slack-pull-request.yaml, .tekton/notifications-connector-slack-push.yaml, .tekton/notifications-connector-splunk-pull-request.yaml, .tekton/notifications-connector-splunk-push.yaml, .tekton/notifications-connector-webhook-pull-request.yaml, .tekton/notifications-connector-webhook-push.yaml, .tekton/notifications-engine-pull-request.yaml, .tekton/notifications-engine-push.yaml, .tekton/notifications-recipients-resolver-pull-request.yaml, .tekton/notifications-recipients-resolver-push.yaml, renovate.json
This PR introduces 3 changes:
- The `pipelinesascode.tekton.dev/pipeline` annotation which makes the pipeline definitions even shorter.
- A dependency on releases from https://github.com/RedHatInsights/konflux-pipelines instead of depending on `main`. Thanks to this change, we'll catch Konflux build failures that could result from a remote pipeline update.
- Renovate will start creating PRs to update the version of https://github.com/RedHatInsights/konflux-pipelines and automatically merge them as long as the GitHub checks pass.
=> Introduce pipelinesascode.tekton.dev/pipeline

.rhcicd/floorist/floorplan.yaml
This reverts commit 02edae6e162212c7cf98d692ba45a503bc6ec56b. Adds back the missing field since the BI team already took a look and added support to that missing field in the tables.
[[RHCLOUD-36454]](https://issues.redhat.com/browse/RHCLOUD-36454)
=> RHCLOUD-36454 | Revert "fix: email subscriptions not reported in Tableau (#3319)"

.rhcicd/sonarqube/scanner/scan_code.bash, aggregator/src/main/resources/application.properties, aggregator/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, common-template/src/main/resources/application.properties, common/src/main/resources/application.properties, connector-common/src/main/resources/application.properties, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java
With current config, quarkus starts all dev services by default event when not releavant, like starting a postgres container to run connectors unit tests, or staring a default postgres container then stop it and restart a new one with the version specified in `TestLifecycleManager`.
=> Disable quarkus dev services by default

common-template/src/main/resources/templates/email/Common/insightsDailyEmailBody.html, common-template/src/main/resources/templates/email/Common/insightsEmailBody.html, common-template/src/main/resources/templates/email/Secure/Common/insightsDailyEmailBody.html, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregationProcessor.java, engine/src/main/resources/templates/Common/insightsDailyEmailBody.html, engine/src/main/resources/templates/Common/insightsEmailBody.html, engine/src/main/resources/templates/Secure/Common/insightsDailyEmailBody.html, engine/src/main/resources/templates/Secure/Common/insightsEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/EmailTemplatesInDbHelper.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregationProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/secured/TestPendoMessage.java
https://issues.redhat.com/browse/RHCLOUD-39363
Account ID, if available, will no longer be displayed in the headers of emails. See [Slack discussion](https://redhat-internal.slack.com/archives/C024CDDPRHD/p1747732364382949)
None, changes have not been deployed to production as of yet.
Tests cases have been updated to stop checking for account IDs in email headers.
=> [RHCLOUD-39363] Remove optional account ID from emails

.rhcicd/clowdapp-engine.yaml
Fork of #2774 for testing various metrics. Will update description when PR is undrafted.
=> [RHCLOUD-28890] Test engine autoscaler

connector-slack/src/main/java/com/redhat/cloud/notifications/connector/slack/SlackCloudEventDataExtractor.java, connector-slack/src/test/java/com/redhat/cloud/notifications/connector/slack/SlackConnectorRoutesMessageBlocksFormatTest.java
I created RHCLOUD-40365, to refactor existing Slack templates into valid Json.
=> [RHCLOUD-40121] Allow Slack connector to send "Blocks" format notifications

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-recipients-resolver.yaml
Remove not used Kessel dependencies in clowder config to save ressources in ephemeral
=> Remove Kessel Clowder dependencies
