src/main/java/com/redhat/cloud/notifications/models/Endpoint.java
- Uses lowercase names for EndpointTypes
=> Expose WebhookAttributes and EmailAttributes to openapi.json

pom.xml, src/main/java/com/redhat/cloud/notifications/NotificationsApp.java, src/main/java/com/redhat/cloud/notifications/routers/LivenessService.java
Available at /api/notifications/v1.0/health
=> Add health check endpoint for readiness

src/main/java/com/redhat/cloud/notifications/oapi/OASAcceptHeaderMangler.java
when openapi.json is requested.
Same code as in Policies ui-backend.
=> NOTIF-14 Modify the accept header so that Json is returned

pom.xml
with ui-backend (5005) and policy-engine (5006)
=> Put debug on port 5007, so that it does not clash

src/main/java/com/redhat/cloud/notifications/oapi/OASModifier.java, src/main/resources/META-INF/openapi.json, src/main/resources/application.properties
Also bring in an OpenAPI header document.
Also generates operation Ids
This is brought over from Policies
=> POL-358 Mangle OAPi path.

src/main/resources/application.properties, src/test/resources/application.properties
=> Change ports to not clash with polices-*

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java
- Description is marked as required.
=> Adding application.description to returned list in EvenTypes.

checkstyle-suppressions.xml, pom.xml, src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, src/main/java/com/redhat/cloud/notifications/models/Notification.java, src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/webhooks/transformers/PoliciesTransformer.java, src/main/resources/avro/action.avsc, src/main/resources/db/migration/V1.1.0__applications.sql, src/main/resources/db/migration/V1.1.1__event_prefill.sql, src/test/java/com/redhat/cloud/notifications/TestHelpers.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java
Still WIP, but this allows now to automatically generate one. Still needs
=> Avro schema for the ingress data

src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, src/main/java/com/redhat/cloud/notifications/processors/EndpointTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/EventBusTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/email/EmailTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/email/bop/Email.java, src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/webhooks/transformers/PoliciesTransformer.java, src/main/resources/application.properties, src/main/resources/db/migration/V1.1.0__applications.sql, src/main/resources/db/migration/V1.1.1__event_prefill.sql, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/resources/application.properties
This is followup of the work from Avro schema PR to avoid too many conflicting changes.
=> Extend processing to new types, including email integration

pom.xml, src/main/java/com/redhat/cloud/notifications/auth/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/auth/RbacIdentityProvider.java, src/main/resources/application.properties
I couldn't test this locally, as my Docker is fubar'd
=> Try to log RBac-failures.

src/main/java/com/redhat/cloud/notifications/StuffHolder.java, src/main/java/com/redhat/cloud/notifications/auth/RHIdentityAuthMechanism.java, src/main/java/com/redhat/cloud/notifications/routers/AdminService.java, src/main/java/com/redhat/cloud/notifications/routers/LivenessService.java, src/test/java/com/redhat/cloud/notifications/routers/HealthCheckTest.java
Status functionality as in policies-ui-backend.
Also remove auth for /health
=> [NOTIF-72] Create an admin interface, now that Turnpike is enabled

src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java
- Clement's suggestion to ack before processing
=> Ack before processing.

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/models/Application.java, src/main/java/com/redhat/cloud/notifications/models/EventType.java, src/main/resources/db/migration/V1.2.1__NOTIF-76_rename_description.sql, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java
```
$ curl -i localhost:8085/internal/applications
HTTP/1.1 200 OK
Content-Length: 133
Content-Type: application/json
[
{
"id":"b6d81863-1277-42ad-824e-f1034e1faa90",
"name":"Policies",
"display_name":"Policies",
"created":"2020-11-25T07:22:42.781+00:00"
}
]
```
=> [NOTIF-76] Rename "description" to "display_name"

src/main/resources/db/migration/V1.2.2__POL-410_rename_policies.sql, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java
Goes along with https://github.com/RedHatInsights/policies-engine/pull/129
=> POL-410 Changing default values in DB for Policies

src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/models/EndpointPage.java, src/main/java/com/redhat/cloud/notifications/routers/models/Meta.java, src/main/java/com/redhat/cloud/notifications/routers/models/Page.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java
Remaining work to fully support on the UI:
- Total count filtered and unfiltered (by type)
=> NOTIF-30 Supports pagination of integrations

src/main/java/com/redhat/cloud/notifications/db/EndpointEmailSubscriptionResources.java, src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java, src/main/java/com/redhat/cloud/notifications/routers/models/SettingsValues.java, src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
=> NOTIF-100 Add notifications to user preferences

src/main/resources/templates/Policies/dailyEmailBody.html, src/main/resources/templates/Policies/dailyEmailTitle.txt, src/test/java/com/redhat/cloud/notifications/processors/email/EmailTest.java, src/test/java/com/redhat/cloud/notifications/templates/TestPoliciesTemplate.java
It was show before as `...3 system...` instead of `...3 unique systems...`
=> Fixes daily email plural for system / unique systems

src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
- It was querying for defaults in disabled state (null, as the endpoint is enabled)
Not sure how it passed CI. I'm assuming it was because the mvn package vs install issue.
=> NOTIF-91 Fix issue when endpoint was in defaults

src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/resources/db/migration/V1.4.0__NOTIF-115_remove_join_table.sql
application -> event_type is 1:n
So we need no join table. We also add an index on (application, event_type_name) to make sure the ET name is unique per Application
=> NOTIF-115 get rid of join-table for 1:n relation

src/main/java/com/redhat/cloud/notifications/processors/webhooks/transformers/BaseTransformer.java, src/test/java/com/redhat/cloud/notifications/processors/webhook/WebhookTest.java
Now is included as `event_type`.
=> NOTIF-117 Add event_type on the data sent to the webhook

helpers/create_application.py, helpers/helpers.py, src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/models/EventType.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/resources/db/migration/V1.6.0__NOTIF-123_event_type_uuid.sql, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/routers/ApplicationServiceTest.java
Also add (back) a description to the event_type (NOTIF-119)
=> [NOTIF-123] ID of eventTypes is an integer and not a UUID.

src/main/resources/application.properties
Was having errors randomly. It was trying ipv6 on some requests
=> Change localhost to local ipv4

src/main/java/com/redhat/cloud/notifications/db/NotificationResources.java, src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/java/com/redhat/cloud/notifications/routers/OApiService.java
- Add description to 204 contents
- Remove some types that were strange (JsonObject as array)
- Remove internal types
=> NOTIF-142 openapi fixes

build_deploy.sh, src/main/docker/Dockerfile-build.jvm
We would have to figure out how to run the testsuite, non trivial here as the testsuite starts docker container, and the build is now running inside a docker container
=> Multi-step build

src/main/java/com/redhat/cloud/notifications/auth/RbacClientResponseFilter.java, src/main/java/com/redhat/cloud/notifications/routers/RouteRedirector.java, src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, src/test/java/com/redhat/cloud/notifications/openapi/OpenApiTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
I ran a SonarCloud scan a few days ago (before knowing about the SonarQube instance we have) while creating the CodeQL PR and Sonar complained about these.
Nothing critical, but I wanted to make Sonar a bit happier 😄
=> Fix vulnerabilities and code smells detected by Sonar

README.adoc, pom.xml
=> Pull in ClowderConfigSource

src/main/resources/db/migration/V1.10.0__NOTIF-163_rename_insights_bundle.sql, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/OldUserConfigServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
Waiting confirmation for bundle display name
=> NOTIF-163 Rename 'insights' bundle to 'rhel'

src/main/docker/Dockerfile-build.jvm
This is how the Dockerfile looks like in a project generated from https://code.quarkus.io.
=> NOTIF-145 Align Dockerfile-build.jvm with official Quarkus version

src/main/docker/Dockerfile-build.jvm
Copy all (Works on my machine)
=> NOTIF-145 Copy all

src/main/java/com/redhat/cloud/notifications/events/DefaultProcessor.java, src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, src/main/java/com/redhat/cloud/notifications/routers/ApplicationService.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java, src/main/java/com/redhat/cloud/notifications/routers/models/UserConfigPreferences.java, src/main/java/com/redhat/cloud/notifications/templates/Policies.java, src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
Spring cleaning (I'm not sure that expression exists in English 😄).
=> Fix deprecated APIs calls

src/main/java/com/redhat/cloud/notifications/templates/Advisor.java, src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, src/main/java/com/redhat/cloud/notifications/templates/LocalDateTimeExtension.java, src/main/resources/templates/Advisor/insightsEmailBody.html, src/main/resources/templates/Advisor/newRecommendationInstantEmailBody.html, src/main/resources/templates/Advisor/newRecommendationInstantEmailTitle.txt, src/main/resources/templates/Policies/dailyEmailBody.html, src/main/resources/templates/Policies/insightsEmailBody.html, src/main/resources/templates/Policies/instantEmailBody.html, src/test/java/com/redhat/cloud/notifications/TestHelpers.java, src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java
Instant email for `new-recommendation`
=> ADVISOR-1456 Advisor template

src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java
https://flywaydb.org/documentation/command/repair
=> Repair Flyway migration

src/main/java/com/redhat/cloud/notifications/templates/AdvisorOpenshift.java, src/main/resources/templates/AdvisorOpenshift/insightsEmailBody.html, src/main/resources/templates/AdvisorOpenshift/newRecommendationInstantEmailBody.html, src/main/resources/templates/AdvisorOpenshift/newRecommendationInstantEmailTitle.txt, src/test/java/com/redhat/cloud/notifications/TestHelpers.java
**Description:**
Add AdvisorOpenshift email templates for instant notification. This will be
used to send notifications with the new recommendations and issues
detected by Insights Advisor for Openshift clusters
This code is to build emails respecting this template: https://marvelapp.com/prototype/852jaj9/screen/78686731
=> CCXDEV-4514 Advisor Openshift instant email template

src/main/java/com/redhat/cloud/notifications/db/EndpointEmailSubscriptionResources.java, src/main/java/com/redhat/cloud/notifications/migration/policynotification/PoliciesEmailSubscription.java, src/main/java/com/redhat/cloud/notifications/models/EmailSubscription.java, src/main/java/com/redhat/cloud/notifications/models/EmailSubscriptionId.java, src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java, src/main/resources/db/migration/V1.14.0__NOTIF-177_add_endpoint_email_subscriptions_relationship.sql, src/test/java/com/redhat/cloud/notifications/migration/policynotification/PoliciesMigrationServiceTest.java
=> NOTIF-177 Add SQL relationship to endpoint_email_subscriptions

src/main/java/com/redhat/cloud/notifications/templates/Drift.java, src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, src/main/resources/templates/Drift/insightsEmailBody.html, src/main/resources/templates/Drift/newBaselineDriftInstantEmailBody.html, src/main/resources/templates/Drift/newBaselineDriftInstantEmailTitle.txt
This is largely cut-n-paste from Policies email template.  I am unable to test it locally, so any and all help (and forgiveness) is appreciated!
=> [DRFT-334] Add Drift instant notification email template

src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java
This will print most endpoint fields in the log in case of history failure.
=> Log endpoint infos when history creation fails

src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroupAction.java, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java
Found some details while connecting to the `get-behaviors-with-bundle`.
@gwenneg Could you add some tests for these cases? 
Adding comments inline with the fix to explain the problem.
=> Fixing some details found while using behavior groups

src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java
I really need to finish testing the behavior group APIs. The update is currently tested at persistence level and everything's working fine in that area, but there was a bug at API level.
=> NOTIF-188 Fix behavior group update API

.rhcicd/grafana-dashboard-notifications-general.configmap.yaml
[NOTIF-186] Fix some issues with notifications-* dashboards.
=>  [NOTIF-186] Fix some issues with notifications-* dashboards.

src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java
With NOTIF-193, we now have to load manually the endpoints properties
This fixes an issue seen in ci/qa
=> NOTIF-150 Fix behavior group actions

.rhcicd/grafana-dashboard-notifications-general.configmap.yaml, .rhcicd/pods2.json, .rhcicd/pods4.json
=> [NOTIF-185] A few more fixes

src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/main/resources/db/migration/V1.18.0__NOTIF-150_no_default_behavior_group.sql, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, src/test/java/com/redhat/cloud/notifications/events/Lifecycle_BG_ITest.java, src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java
@josejulio Let's get rid of that account-level default behavior group idea. We will probably reintroduce something similar but at app or bundle-level later.
=> NOTIF-150 Remove account-level default behavior group

src/main/java/com/redhat/cloud/notifications/routers/AdminService.java, src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/main/java/com/redhat/cloud/notifications/routers/UserConfigService.java, src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, src/test/java/com/redhat/cloud/notifications/events/Lifecycle_BG_ITest.java, src/test/java/com/redhat/cloud/notifications/routers/AuthenticationTest.java, src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/HealthCheckTest.java, src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
Also use method-level `@Consumes` and `@Produces`.
=> Test the content-type header returned by all REST APIs

pr_check.sh, regenerateGrafanaConfig.sh, validateGrafanaConfig.sh
more notif fixes: moving script to avoid issues.
=> more notif fixes: moving script to avoid issues.

.rhcicd/grafana-dashboard-notifications-general.configmap.yaml
[NOTIF-185] update notifications dashboard manually.
=>  [NOTIF-185] update notifications dashboard manually.

src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, src/main/java/com/redhat/cloud/notifications/routers/NotificationService.java, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, src/test/java/com/redhat/cloud/notifications/events/Lifecycle_BG_ITest.java, src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
@josejulio Here's the new update API for the event type behaviors. It replaces the add, delete and mute operations.
If that's more convenient to you, I can split this PR into two steps:
- PR 1 : new API addition
- PR 2 : old APIs removal
=> NOTIF-150 Add event type behaviors update API

src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java
=> Don't log JSON on webhook call 500 status

pom.xml, src/main/java/com/redhat/cloud/notifications/JsonAccessLoggerHandler.java, src/main/java/com/redhat/cloud/notifications/NotificationsApp.java, src/main/resources/application.properties
Health checks produce logs lines that are unnecessary so we want to get rid of these kind of logs.
=> NOTIF-192 Silence successful health checks logs

src/main/resources/application.properties
Based on #191.
See the migration plan (Google doc) for more details about this.
=> NOTIF-150 Introduce behavior groups - Phase 2.1

src/main/resources/application.properties
This PR should be merged after we're done testing CI.
The resulting Docker image will be the first image to deploy on prod to start the migration.
=> NOTIF-150 Disable Kafka ingress channel

src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java
@josejulio Maybe we'll need an additional frontend check for that one.
=> NOTIF-244 Return 400 on behavior group creation with blank display name

aggregator/src/main/java/com/redhat/cloud/notifications/db/EndpointEmailSubscriptionResources.java
This commit changes the standard query to a native one so we can get rid of some models later.
=> NOTIF-190 Change to native query

backend/src/main/resources/templates/Advisor/newRecommendationInstantEmailBody.html, backend/src/main/resources/templates/Advisor/resolvedRecommendationInstantEmailBody.html, backend/src/test/java/com/redhat/cloud/notifications/templates/TestOpenshiftAdvisorTemplate.java
Link may change again, this is my best guess (and better than broken links)
=> NOTIF-215 Update Advisor email links

backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacIdentityProvider.java
This is based on Mutiny's [retry capabilities](https://smallrye.io/smallrye-mutiny/getting-started/retry).
=> NOTIF-267 Retry on RBAC call failure

backend/src/main/java/com/redhat/cloud/notifications/routers/EmailEndpointMigrationService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/TestEmailEndpointMigrationService.java
This should hopefully fix the email endpoints migration issue on stage. I am not 100% sure it will work because I couldn't reproduce the issue locally with the exact same error message (I got something really close). Anyway, this PR is harmless in case it doesn't fix the issue.
I suspect what happened on stage is a failure during an endpoint deletion because it had history entries in the database and the cascading rule between the `endpoints` and `notifications_history` tables wasn't applied:
```
TABLE "notification_history" CONSTRAINT "notification_history_endpoint_id_fkey" FOREIGN KEY (endpoint_id) REFERENCES endpoints(id) ON UPDATE CASCADE ON DELETE CASCADE
```
It wouldn't be the first time I see issues with `session.remove` and `session.removeAll`. I don't know exactly why but these …
=> Fix EMAIL_SUBSCRIPTION endpoints migration

.github/workflows/build.yml
This should start using the cache for the frontend dependencies
=> Use cache for frontend dependencies

backend/src/main/webapp/package.json, backend/src/main/webapp/src/app/Navigation.tsx, backend/src/main/webapp/src/generated/OpenapiInternal.ts, backend/src/main/webapp/src/index.tsx, backend/src/main/webapp/src/pages/ApplicationPage.tsx, backend/src/main/webapp/src/services/GetBundles.ts, backend/src/main/webapp/src/services/GetEventTypes.ts, backend/src/main/webapp/src/types/Notifications.ts, backend/src/main/webapp/yarn.lock
=> Use types on admin ui

backend/src/main/java/com/redhat/cloud/notifications/db/BehaviorGroupResources.java, backend/src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, backend/src/main/java/com/redhat/cloud/notifications/models/EmailSubscriptionProperties.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/RecipientResolver.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/RequestEmailSubscriptionProperties.java, backend/src/main/resources/db/migration/V1.22.0__NOTIF-153-email_properties.sql, backend/src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java
=> NOTIF-153 Add send options to emails

backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
=> Ack messages before processing

backend/src/main/java/com/redhat/cloud/notifications/routers/models/RenderEmailTemplateRequest.java, backend/src/main/webapp/package.json, backend/src/main/webapp/src/generated/OpenapiInternal.ts, backend/src/main/webapp/src/pages/RenderEmailPage.tsx, backend/src/main/webapp/src/services/RenderEmailRequest.ts, backend/src/main/webapp/yarn.lock
- Generated service code uses . as its base path
- Uses `@Schema` for snake_case properties
I was wrong about the snake_case thing :D.
=> Fix admin console

backend/src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java
This is something I need for event log ui filter.
=> NOTIF-245 When no bundle is specified, return all applications

backend/src/main/resources/db/migration/V1.25.0__NOTIF-291_event_cleaning_warm_up.sql
Draft until we decide to push notifications-backend to prod.
=> NOTIF-291 Ease the first EventLogCleaner run

backend/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java
After the issue we had this week-end, we need to have a better idea of the RBAC calls numbers and durations.
=> Add RbacRecipientUsersProvider metrics

backend/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java
See the [Micrometer doc](https://micrometer.io/docs/concepts#_storing_start_state_in_timer_sample) for details about `Timer.Sample`.
=> Improve RBAC metrics and increase elements per page

backend/src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java
@josejulio How do you like this new version? 😃
If you like it, I'll write everything like this.
=> Get rid of the reactive tests crazy nesting

backend/src/main/java/com/redhat/cloud/notifications/NotificationsApp.java
Reverts RedHatInsights/notifications-backend#583
=> Revert "Add a gauge which displays when an application started"

backend/src/main/java/com/redhat/cloud/notifications/routers/EventService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java
@josejulio I also changed `/event` to `/events` to be consistent with other APIs.
=> NOTIF-308 Fix EventService path

backend/src/main/java/com/redhat/cloud/notifications/db/ApplicationResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/InternalService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/InternalServiceTest.java
I noticed NOTIF-276 would require an event type update API but we didn't have one until now.
=> NOTIF-276 Add event type update API

backend/src/test/java/com/redhat/cloud/notifications/TestThreadHelper.java, backend/src/test/java/com/redhat/cloud/notifications/db/BehaviorGroupResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/EmailAggregationResourcesTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/ModelInstancesHolder.java, backend/src/test/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProviderTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationServiceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigServiceTest.java
Here comes another boring review 😄
This is the second and hopefully last PR preparing our tests for the Quarkus 2 bump. Tests are even flatter in this PR than in #555!
As usual, checking `Hide whitespace changes` before starting the review is strongly recommended for an easier review.
=> NOTIF-273 Prepare tests for the Quarkus 2 bump (continued)

backend/src/main/java/com/redhat/cloud/notifications/processors/email/RecipientResolver.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/RecipientResolverTest.java
@josejulio We don't need that anymore, right?
=> Remove RBAC user query feature flag

backend/src/main/java/com/redhat/cloud/notifications/routers/LivenessService.java
See [Reactive health checks](https://quarkus.io/guides/smallrye-health#reactive-health-checks) from the Quarkus doc for more details.
=> Implement AsyncHealthCheck in LivenessService

backend/src/main/resources/templates/Rhosak/actionRequiredBody.html, backend/src/main/resources/templates/Rhosak/actionRequiredTitle.txt
/cc @josejulio @gwenneg @akoserwal @davidffrench
=> feat(rhosak): add first iteration of action-required email template

backend/src/main/resources/templates/Rhosak/actionRequiredBody.html, backend/src/main/resources/templates/Rhosak/dailyRhosakEmailsBody.html, backend/src/main/resources/templates/Rhosak/instanceCreatedBody.html, backend/src/main/resources/templates/Rhosak/instanceDeletedBody.html, backend/src/main/resources/templates/Rhosak/rhosakEmailBody.html, backend/src/main/resources/templates/Rhosak/serviceDisruptionBody.html, backend/src/main/resources/templates/Rhosak/serviceDisruptionTitle.txt
~~ Opening as draft as I still need to test it using the email editor. ~~
Tested and happy with the rendering. We can go with this for now.
=> fix(rhosak): add logo and rename skeleton template to make it rhosak specific

backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/DriftEmailPayloadAggregator.java, backend/src/test/java/com/redhat/cloud/notifications/DriftTestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/DriftEmailPayloadAggregatorTest.java, backend/src/test/java/com/redhat/cloud/notifications/templates/TestDriftTemplate.java
Previously the aggregator was not grouping systems for each baseline.
This PR fixes this behavior
=> [DRFT-690] - Drift daily email should group baseline and system

backend/src/main/resources/templates/Rhosak/rhosakEmailBody.html
Thanks to @pmuir for pointing me to this link
/cc @gwenneg @josejulio would you mind giving this a look? Thanks
=> fix(rhosak): replace RHOSAK SVG logo

backend/src/main/java/com/redhat/cloud/notifications/templates/Rhosak.java, backend/src/main/resources/templates/Rhosak/dailyRhosakEmailsBody.html, backend/src/main/resources/templates/Rhosak/dailyRhosakEmailsTitle.txt, backend/src/main/resources/templates/Rhosak/scheduledUpgradeBody.html, backend/src/main/resources/templates/Rhosak/scheduledUpgradeTitle.txt
Also allow all events to be Instant or Daily. The user will have to create a behaviour group and decide how they want to receive them.
Closes MGDSTRM-5089
/cc @davidffrench @akoserwal for internal review 
/cc @gwenneg @josejulio for anything notifications backend related.
=> feat(rhosak): add initial scheduled upgrade template

backend/src/main/resources/templates/Rhosak/serviceDisruptionBody.html
@machi1990 @gwenneg @josejulio
=> fix: updating the content

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
=> Add RDS graph + fixed JVM Metrics

backend/src/main/webapp/package.json, backend/src/main/webapp/src/services/GetBundles.ts, backend/src/main/webapp/yarn.lock
This is one way to fix the leak, guards the `set` in a `is mounted` block.
=> Fixes leak found by Alex

backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregator.java, backend/src/main/resources/templates/Rhosak/dailyRhosakEmailsBody.html, backend/src/main/resources/templates/Rhosak/dailyRhosakEmailsTitle.txt
Closes https://issues.redhat.com/browse/MGDSTRM-5330
/cc @akoserwal @davidffrench @josejulio @gwenneg
=> feat(rhosak): add daily digest aggregator and email template

backend/src/main/resources/templates/Rhosak/instanceCreatedBody.html, backend/src/main/resources/templates/Rhosak/instanceCreatedTitle.txt, backend/src/main/resources/templates/Rhosak/instanceDeletedBody.html, backend/src/main/resources/templates/Rhosak/instanceDeletedTitle.txt
Closes https://issues.redhat.com/browse/MGDSTRM-5528 and https://issues.redhat.com/browse/MGDSTRM-5529
/cc @akoserwal @davidffrench @josejulio @gwenneg
=> feat: add instance created / deleted for RHOSAK application

backend/src/main/java/com/redhat/cloud/notifications/models/Event.java, backend/src/main/java/com/redhat/cloud/notifications/models/Notification.java, backend/src/main/java/com/redhat/cloud/notifications/models/NotificationHistory.java, backend/src/main/resources/db/migration/V1.31.0__NOTIF-291_event_log_cleaning.sql, backend/src/test/java/com/redhat/cloud/notifications/db/EventLogCleanerTest.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java
This PR will be a draft until I've verified the data migration won't cause any issue with the current production data (I'll write app-interface queries tomorrow) but you can already review it.
=> NOTIF-291 Finish the event log schema migration and clean code

backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregator.java
=> fix(rhosak): change typo in payload key

backend/src/main/java/com/redhat/cloud/notifications/db/FlywayWorkaround.java
This will help debugging ephemeral.
=> Log the Flyway JDBC URL

backend/src/main/java/com/redhat/cloud/notifications/models/Application.java, backend/src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java, backend/src/main/java/com/redhat/cloud/notifications/models/Bundle.java, backend/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, backend/src/main/java/com/redhat/cloud/notifications/models/CurrentStatus.java, backend/src/main/java/com/redhat/cloud/notifications/models/EmailSubscriptionProperties.java, backend/src/main/java/com/redhat/cloud/notifications/models/EventType.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EventLogEntry.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/EventLogEntryAction.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/RenderEmailTemplateRequest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/RequestEmailSubscriptionProperties.java, backend/src/main/java/com/redhat/cloud/notifications/routers/models/UserConfigPreferences.java
`quarkus-smallrye-openapi` was updated and now correctly deals with `@JsonNaming(SnakeCaseStrategy.class)`.
=> Remove `@Schema` annotations

backend/src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointService.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointServiceTest.java
- Add missing properties in camel update
~~edit: need to update tests~~
=> Support multiple types in the endpoint listing API

backend/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java
Check `Hide whitespace` for an easier review.
=> NOTIF-377 Persist Kafka messages ID before processing

admin-console/src/main/webapp/package.json, admin-console/src/main/webapp/src/pages/ApplicationPage.tsx, admin-console/src/main/webapp/src/services/GetApplication.ts, admin-console/src/main/webapp/src/services/GetBundleAction.ts, admin-console/src/main/webapp/src/services/GetBundles.ts, admin-console/src/main/webapp/src/types/Notifications.ts, admin-console/src/main/webapp/yarn.lock
https://user-images.githubusercontent.com/86322239/141199186-93bff849-d3c1-4cc1-b519-33d5d6df9bc3.mov
=>  NOTIF-365 admin ui bundle name issue

aggregator/src/main/java/com/redhat/cloud/notifications/DailyEmailAggregationJob.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacClientResponseFilter.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacIdentityProvider.java, backend/src/main/java/com/redhat/cloud/notifications/db/EndpointResources.java, backend/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, backend/src/main/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilter.java, backend/src/main/java/com/redhat/cloud/notifications/routers/RouteRedirector.java, backend/src/main/java/com/redhat/cloud/notifications/routers/filters/MaintenanceModeRequestFilter.java
[Logging levels in Quarkus](https://quarkus.io/guides/logging#logging-levels)
=> Replace JUL with org.jboss.logging.Logger

admin-console/src/main/webapp/src/pages/ApplicationPage.tsx
form fixes that you recommended, my guess is these also got lost when I rebased that other branch.
=> form fixes

.rhcicd/clowdapp-backend.yaml, backend/src/main/resources/db/migration/V1.32.0__NOTIF-299_notifications-db-cleaner.sql, backend/src/test/java/com/redhat/cloud/notifications/db/EventLogCleanerTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/KafkaMessagesCleanerTest.java
I tested this on ephemeral already.
=> NOTIF-299 Run the backend DB cleaning jobs from a CronJob - Phase 1

backend/src/main/java/com/redhat/cloud/notifications/routers/models/SettingsValueJsonForm.java
Depends on https://github.com/RedHatInsights/user-preferences-frontend/pull/94
=> NOTIF-346 Add warning message when selecting an instant email

.rhcicd/clowdapp-backend.yaml
This is required to temporarily disable the Kafka topics on prod.
=> Prepare Clowder prod deployment

aggregator/src/main/java/com/redhat/cloud/notifications/db/EmailAggregationResources.java
This fixes a query I broke in #821 🤦‍♂️
=> Fix aggregator query

backend/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, backend/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java
I'll take care of the `FromCamelHistoryFiller` tests another day. 😃
=> Test CamelTypeProcessor

backend/src/main/java/com/redhat/cloud/notifications/NotificationsApp.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, pom.xml
We'll talk about that during the team sync.
=> Downgrade Quarkus back to 2.3.1.Final

backend/src/main/java/com/redhat/cloud/notifications/models/AggregationCommand.java, backend/src/main/java/com/redhat/cloud/notifications/models/EmailAggregationKey.java, backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, backend/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
This PR will give us the possibility to monitor and analyze the aggregation commands processing in the backend.
=> Add log entries and metrics to aggregation commands processing

.rhcicd/clowdapp-backend.yaml, backend/src/main/resources/application.properties
The old url will be deprecated soon.
=> Update BOP URL

.rhcicd/deploy_acceptance.yml
We will also need https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/30350 but in no particular order
=> Fixing deploy_acceptance.yml

backend/src/main/resources/ephemeral/ephemeral_data.json
Based on the information from https://issues.redhat.com/browse/NOTIF-398, this should work.
=> Add Ansible bundle to ephemeral data

.rhcicd/pr_check_backend.sh
Now we are updating marker in IQE-notification hence updating PR check marker.
=> [RFR] Update PR check marker

backend/src/main/java/com/redhat/cloud/notifications/health/KafkaConsumedTotalChecker.java
Checking periodically made sense at first because the check was initially based on `kafka.consumer.fetch.manager.records.consumed.rate` which is a gauge. But the latest version is based on a counter, so we can simply check once every 5 minutes and fail as soon as the number of processed messages didn't increase since the previous check.
=> Check the Kafka health once instead of periodically

.rhcicd/pr_check_backend.sh
As per @dgaikwad's instructions on Slack.
=> Disable UI IQE tests

.rhcicd/clowdapp-backend.yaml
Related to https://github.com/RedHatInsights/notifications-backend/pull/875.
=> Update Kafka health check env vars

backend/pom.xml, common/pom.xml, docker/Dockerfile.notifications-backend.jvm, engine/pom.xml, pom.xml
This is preparation work for the notifications-backend split. Step 3: new (empty) modules.
=> NOTIF-450 Introduce common and engine modules

.rhcicd/clowdapp-aggregator.yaml
=> PROMETHEUS_PUSHGATEWAY should be optional

.rhcicd/clowdapp-engine.yaml
This is preparation work for the notifications-backend split. Step 6: `engine` ClowdApp template. It will be used shortly in app-interface.
=> NOTIF-450 Add notifications-engine ClowdApp template

.rhcicd/pr_check.sh, docker/Dockerfile.notifications-engine.jvm
This is the `engine` image that will be deployed on prod eventually.
=> NOTIF-450 Build engine image during PR check

.rhcicd/build_deploy.sh
[app-interface!32196](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/32196) needs to be merged first.
=> NOTIF-450 Publish notifications-engine image on quay.io

engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailBody.html, engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailTitle.txt, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailBody.html, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailTitle.txt
Adjustments suggested by our PM
=> fix(templates): RHICOMPL-2595 adjusted email templates for compliance

backend/src/main/resources/ephemeral/ephemeral_data.json
This was requested by the Compliance team. Stage has been updated already.
cc @skateman
=> Update Compliance event types on ephemeral

engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailBody.html, engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailTitle.txt, engine/src/main/resources/templates/Compliance/insightsEmailBody.html, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailBody.html, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailTitle.txt
Making it consistent with our mockups.
=> RHICOMPL-2638 adjust templates for compliance notifications

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java
This reverts commit 737c96d265a6a5d0766da9a357cad8ec5b02c7b7.
=> Revert "NOTIF-444 Add info logging for dynamic metrics (#954)"

pom.xml
=> [NOTIF-478] Bump avro to 1.11

.rhcicd/clowdapp-backend.yaml
=> adding keystore secret mount to backend pod

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml
=> Mount volume in notifications-engine instead of -backend

database/src/main/resources/db/migration/V1.39.0__events_order_by_indexes.sql
=> Index the events creation date to speed up ordering

docker/Dockerfile.notifications-backend.jvm, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/AbstractEmailPayloadAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/RecipientResolver.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilter.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/RecipientResolverTest.java
My IDE was broken when I tried to find these earlier 😄
=> NOTIF-450 Cleanup TODOs

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacServiceToService.java
=> NOTIF-488 Move @Blocking to EventConsumer

.github/workflows/build.yml, pom.xml
Do we have coverage already somewhere else?
This seems to be working.
https://app.codecov.io/gh/RedHatInsights/notifications-backend/branch/coverage-test
=> Pushes coverage to codecov.io

backend/src/main/resources/application.properties, common/src/main/java/com/redhat/cloud/notifications/openbridge/Bridge.java, common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeApiService.java, common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeHelper.java, engine/src/main/resources/application.properties
This is quicker and more stable. The bridge list is a paged entity and there is no guarantee right now, that our bridge is in the first page.
=> Use the bridge uuid instead of bridge name.

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml
Those externalise the entries from application.properties for Clowder usage.
=> Clowdapp files for OpenBridge use

admin-console/src/main/webapp/src/app/App.tsx, admin-console/src/main/webapp/src/generated/OpenapiInternal.ts, admin-console/src/main/webapp/src/services/ServerInfo.ts, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/ServerInfo.java
- Will warn when using prod or when the environment could not be found
A little heads up to let us know that we are in prod.
=> Introduce warning alert on admin ui

engine/src/main/resources/templates/Advisor/deactivatedRecommendationInstantEmailBody.html, engine/src/main/resources/templates/Advisor/deactivatedRecommendationInstantEmailTitle.txt
- https://issues.redhat.com/browse/ADVISOR-1989 for ADVISOR-1990
=> Template for Advisor deactivated recommendation notifications

backend/src/main/java/com/redhat/cloud/notifications/db/InternalRoleAccessResources.java, backend/src/main/java/com/redhat/cloud/notifications/models/InternalRoleAccess.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalPermissionService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/InternalApplicationUserPermission.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/models/InternalUserPermissions.java, backend/src/test/java/com/redhat/cloud/notifications/CrudTestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/InternalPermissionsServiceTest.java
Updates the response to include the display name of the application
=> NOTIF-482 Update response format for all access list

sonar-project.properties
Trying to enable sonarqube scanning for this project.
I found that the project has some java binaries so we need to set a path.
https://sonarqube.corp.redhat.com/dashboard?id=console.redhat.com%3Anotifications-backend
=> Adding sonar properties

engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailBody.html, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailBody.html
Followup on [this](https://github.com/RedHatInsights/notifications-backend/pull/1086/files#diff-15a148a5c825b965a2b5548111184aba93c2aeb8ea2c5bd03b57ad35f9547b95R14) for compliance.
=> RHICOMPL-2782: adjust URLs to work both in stage and prod

admin-console/src/main/webapp/src/app/App.tsx, admin-console/src/main/webapp/src/app/PermissionContext.ts, admin-console/src/main/webapp/src/components/CreateEditApplicationModal.tsx, admin-console/src/main/webapp/src/generated/OpenapiInternal.ts, admin-console/src/main/webapp/src/pages/ApplicationPage.tsx, admin-console/src/main/webapp/src/pages/BundlePage.tsx, admin-console/src/main/webapp/src/services/Applications/CreateApplication.ts, admin-console/src/main/webapp/src/services/Permissions.ts, admin-console/src/main/webapp/src/types/Notifications.ts
- Allows to add applications with the owner role
- Disables CRUD when the  permission is not granted to the application
- Handle permission refresh
Depends on:
- https://github.com/RedHatInsights/notifications-backend/pull/1084
- https://github.com/RedHatInsights/notifications-backend/pull/1083
- https://github.com/RedHatInsights/notifications-backend/pull/1082
- https://github.com/RedHatInsights/notifications-backend/pull/1059
=> NOTIF-482 Updates admin-console to handle the app permissions

engine/src/main/java/com/redhat/cloud/notifications/templates/Advisor.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java
- https://issues.redhat.com/browse/NOTIF-545
=> Add new Advisor event-type 'deactivated-recommendation'

.github/codeql/codeql-config.yml
=> Update codeql ignore path

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Sources.java, engine/src/main/resources/templates/Sources/availabilityStatusEmailBody.html, engine/src/main/resources/templates/Sources/availabilityStatusEmailTitle.txt, engine/src/main/resources/templates/Sources/insightsEmailBody.html
Onboarding ticket: https://issues.redhat.com/browse/NOTIF-513
Source's ticket:https://issues.redhat.com/browse/RHCLOUD-16269
**Email Template:**
**Subject**: 1.1.1990 - Availability Status Change in Application
**Body**:
Application's availability status was changed for  from **available** to 
**unavailable**.
For more information please check summary page of [MySource](MySource) source.
=> Setting up a email templates for Source's Availability Status event type

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
we are misusing the concept of timers here. But that's the only thing working at the moment.
=> Add timer as emails sent metric

pom.xml
mvn quarkus:update suggests:
[INFO] Recommended Quarkus platform BOM updates:
[INFO] Add:    io.quarkus.platform:quarkus-bom:pom:2.7.5.Final
[INFO] Remove: io.quarkus:quarkus-bom:pom:2.7.5.Final
This is the PR for it.
=> Change Quarkus platform group id

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
This reverts commit 170b8646cb0c5026ed2844da1967df1bb95aafc3.
=> Revert "Add timer as emails sent metric (#1156)"

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java
This PR adds an integrity check which verifies that an event type and a behavior group have the same bundle parent before associating them in the `event_type_behavior` table.
=> NOTIF-598 Add EventTypeBehavior integrity check

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java
=> NOTIF-484 Update migration code for RBAC templates

engine/src/main/resources/templates/Sources/availabilityStatusEmailBody.html, engine/src/main/resources/templates/Sources/availabilityStatusEmailTitle.txt
Subject: Source XXX has availability status change for _Application_
Body: _Application's_ availability status was changed for from **available** to **unavailable**.
For more information please check summary page of **MySource** source.
cc @josejulio 
~~please check especially conditions in `availabilityStatusEmailTitle.txt` - I was not sure how to check strings and whether I can  have nested conditions, thanks!~~
=> fix typos and changes for source's email templates

backend/src/main/java/com/redhat/cloud/notifications/auth/ConsoleIdentityProvider.java, backend/src/main/java/com/redhat/cloud/notifications/auth/rbac/RbacRestClientRequestFilter.java, backend/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, common/src/main/java/com/redhat/cloud/notifications/Base64Utils.java, common/src/main/java/com/redhat/cloud/notifications/db/converters/BasicAuthenticationConverter.java, common/src/main/java/com/redhat/cloud/notifications/models/BasicAuthentication.java, common/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, common/src/test/java/com/redhat/cloud/notifications/Base64UtilsTest.java, database/src/main/resources/db/migration/V1.49.0__NOTIF-195_encoded_basic_auth.sql, engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilter.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/rbac/AuthRequestFilterTest.java
ℹ️ DB data before this PR:
| Environment | `endpoint_webhooks` | `camel_properties` |
| - | - | - |
| Stage | 0 record with `basic_authentication` data  | 29 records with empty/null `basic_authentication` data and 2 records with non empty `basic_authentication` data |
| Prod | 0 record with `basic_authentication` data | 13 records with empty/null `basic_authentication` data |
=> NOTIF-195 Encode endpoint property

backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/Event.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/db/EventLogCleanerTest.java, pom.xml
This depends on https://github.com/RedHatInsights/insights-schemas-java/pull/45 and a release of the schema project.
=> NOTIF-499 Use incoming Event ID if present.

.editorconfig, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/ValidationResourceTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/PoliciesEmailPayloadAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/RhosakEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/itservice/pojo/request/ITUserRequestTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateFactoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOpenshiftAdvisorTemplate.java
Feel free to add or change something :-)
I had the same config in the intelliJ settings, but it somehow did not work. With the editorconfig file it seems to be working and this is also the better solution so we don't have to change the settings on our local machines. So if you need something, feel free to add or change it... :)
=> Add editorconfig so we do use the same settings

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
This reverts commit 19426fb7db2fe431468f618ec7d40b0c9dd05f61.
=> Revert "Just updating the dashboaersion (#1219)"

engine/src/main/resources/templates/Rbac/customGroupUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/customPlatformGroupUpdatedEmailBody.html
The role added/removed from group does not show the name correctly.
=> Fix some issues of rbac found in stage

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EventRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java
- It wasn't working correctly when the application was part of other bundle
=> NOTIF-579 Bundle and application filter work well together

admin-console/src/main/webapp/src/components/Applications/CreateEditApplicationModal.tsx
This reverts commit e52867fdc30ace9b9b42ac7936c856bce774eb0f.
Merged by mistake
=> Revert "require non-admin to select role (#1239)"

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/test/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationServiceTest.java
- Adding patch
Related PR: https://github.com/RedHatInsights/notifications-backend/pull/1231
=> Syncing EmailTemplateMigrationService

engine/src/main/resources/templates/Vulnerability/anyCveKnownExploitBody.html, engine/src/main/resources/templates/Vulnerability/newCveCritSeverityEmailBody.html, engine/src/main/resources/templates/Vulnerability/newCveHighCvssEmailBody.html, engine/src/main/resources/templates/Vulnerability/newCveSecurityRuleBody.html
- We switched to the context in events - fix
- Email titles were incorrect - fix
=> Fix vulnerability template titles and links

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
I would like to change the Grafana Dashboard after this counter is available in prometheus.
=> NOTIF-680 Add exception counter

admin-console/src/main/webapp/src/components/EventTypes/EventTypeTable.tsx, admin-console/src/main/webapp/src/components/EventTypes/Table/EventTypeExpandableRow.tsx, admin-console/src/main/webapp/src/components/EventTypes/Table/InstantEmailCell.tsx, admin-console/src/main/webapp/src/generated/OpenapiInternal.ts, admin-console/src/main/webapp/src/pages/ApplicationPage.tsx, admin-console/src/main/webapp/src/pages/ApplicationPage/useEventTypes.ts, admin-console/src/main/webapp/src/services/EmailTemplates/GetInstantTemplates.tsx, admin-console/src/main/webapp/src/types/Notifications.ts
- Makes it a separate component
- pulls up the logic
=> Refactor EventTypes table

.rhcicd/clowdapp-backend.yaml
Reverts RedHatInsights/notifications-backend#1292
=> Revert "Add back original cronjob until i fix the clowderized version"

common/src/main/java/com/redhat/cloud/notifications/models/Event.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepository.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/RecipientResolver.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java
Reverts #1270.
The temp log entries were not supposed to be deployed on prod. Our prod logs currently contain lots of things like this:
```
2022-06-17 06:16:00,699 INFO  [com.red.clo.not.rec.RecipientResolver] (executor-thread-429) recipientUsers: [com.redhat.cloud.notifications.recipients.User@4026ad61, com.redhat.cloud.notifications.recipients.User@d6b16662, com.redhat.cloud.notifications.recipients.User@d6b166de, com.redhat.cloud.notifications.recipients.User@ff7b7173, com.redhat.cloud.notifications.recipients.User@c75ab1cb, com.redhat.cloud.notifications.recipients.User@c827c4c5, com.redhat.cloud.notifications.recipients.User@c82811af, com.redhat.cloud.notifications.recipients.User@c4cfbe45, com.redhat.cloud.notifications.recipients.User@11494262, …
```
=> Revert #1270

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepository.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/BehaviorGroupRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/NotificationResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/BehaviorGroup.java
=> NOTIF-369 Forbid behavior groups display names duplicates

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/NotificationHistoryRepository.java, engine/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/NotificationHistoryRepositoryTest.java
See the migration script comments for details about this PR.
=> Prevent error if an endpoint is gone when the history is written

.rhcicd/clowdapp-backend.yaml, .rhcicd/run_org_id_populator.yaml
#1271 is too big and hard to rebase, so I'm breaking it down into smaller PRs.
This is step 2: adding the missing `orgId` populator jobs.
ℹ️ Check `Hide whitespace` for an easier review.
=> NOTIF-603 Add orgId populator jobs

engine/src/test/java/com/redhat/cloud/notifications/templates/DbQuteEngineTest.java, pom.xml
This PR is part of a memory leak investigation on prod.
=> Downgrade Quarkus to 2.9.2.Final

engine/src/main/java/com/redhat/cloud/notifications/templates/CostManagement.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/resources/templates/CostManagement/MissingCostModelEmailBody.html, engine/src/main/resources/templates/CostManagement/MissingCostModelEmailTitle.txt, engine/src/main/resources/templates/CostManagement/insightsEmailBody.html
Adding first notification for cost mgmt
=> Adding cost mgmt cost model notification

aggregator/src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java
Same as https://github.com/RedHatInsights/notifications-backend/pull/1344, but for `aggregator` this time.
=> RHCLOUD-20150 Connect to managed Kafka using Clowder

admin-console/src/main/webapp/src/components/Applications/CreateEditApplicationModal.tsx
I think I got that right, it was confusing to me when I demoed this to QE and I want to test the autodeployment to stage so I will merge myself
=> Fix the helper text

engine/src/main/resources/templates/EdgeManagement/imageCreationBody.html
=> Fix typo on included template

admin-console/src/main/webapp/src/components/EmailTemplates/EmailTemplateCard.tsx, admin-console/src/main/webapp/src/components/EmailTemplates/EmailTemplateTable.tsx, admin-console/src/main/webapp/src/pages/ApplicationPage.tsx, admin-console/src/main/webapp/src/pages/BundlePage.tsx, admin-console/src/main/webapp/src/pages/BundlePage/BehaviorGroupTable.tsx
- Using skeleton for loading the breadcrumbs to prevent from
breaking the layout
=> Simplify breadcrumbs and move them to a section

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/MalwareDetection.java, engine/src/main/resources/templates/MalwareDetection/detectedMalwareInstantEmailBody.html, engine/src/main/resources/templates/MalwareDetection/detectedMalwareInstantEmailTitle.txt, engine/src/main/resources/templates/MalwareDetection/insightsEmailBody.html
https://issues.redhat.com/browse/YARA-266
=> Adding templates for malware detection

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java
Requested by Sources team (@lpichler)
=> Log action id on event consumer

backend/src/main/java/com/redhat/cloud/notifications/oapi/OApiFilter.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/itservice/pojo/request/AllOf.java
The security-schema related warnings come from an issue in Quarkus https://github.com/quarkusio/quarkus/issues/27373
=> NOTIF-753 Fix some OpenAPI issues

aggregator/src/main/java/com/redhat/cloud/notifications/models/EmailAggregationKey.java, aggregator/src/test/java/com/redhat/cloud/notifications/models/EmailAggregation.java, common/src/main/java/com/redhat/cloud/notifications/models/Event.java, engine/src/main/java/com/redhat/cloud/notifications/models/EmailAggregation.java, engine/src/main/java/com/redhat/cloud/notifications/models/EmailAggregationKey.java
@josejulio I just realized that this should have been done in #1428. Please deploy this PR on prod ASAP (tomorrow is fine).
=> Fix accountId and orgId constraints

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/EmailPayloadAggregatorFactory.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Inventory.java, engine/src/main/resources/templates/Inventory/dailyEmailBody.html, engine/src/main/resources/templates/Inventory/dailyEmailTitle.txt, engine/src/main/resources/templates/Inventory/insightsEmailBody.html, engine/src/main/resources/templates/Inventory/validationErrorEmailBody.html, engine/src/main/resources/templates/Inventory/validationErrorEmailTitle.txt, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java
Adds Inventory email templates.
Related Jira task: [ESSNTL-2740](https://issues.redhat.com/browse/ESSNTL-2740)
=> Adds Inventory email templates

common/src/main/java/com/redhat/cloud/notifications/models/Event.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java, pom.xml
Requires https://github.com/RedHatInsights/insights-schemas-java/pull/60
=> Remove casts introduced in previous schema change

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregator.java, engine/src/main/resources/templates/Inventory/dailyEmailBody.html, engine/src/main/resources/templates/Inventory/validationErrorEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java
This PR changes host_id for request_id on the email templates as that is a more reliable information.
Also updates the tests accordingly.
=> Updates inventory email templates and tests

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java
@josejulio Do you like this better? 😃
=> NOTIF-512 Reset endpoint server errors on endpoint update

engine/src/main/resources/templates/ConsoleNotifications/integrationDisabledBody.html
As requested by Jerome on Slack.
=> NOTIF-512 Update integration disabled body template

.github/workflows/checkupdate.yml
Copied from `notifications-gw`.
=> Automatically update ubi-minimal base image

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/ResourceOptimizationService.java, engine/src/main/resources/templates/ResourceOptimizationService/dailyEmailBody.html, engine/src/main/resources/templates/ResourceOptimizationService/dailyEmailTitle.txt, engine/src/main/resources/templates/ResourceOptimizationService/insightsEmailBody.html
Epic card - [https://issues.redhat.com/browse/RHIROS-646](https://issues.redhat.com/browse/RHIROS-646)
=> RHIROS-803 Add daily email template for ROS

backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/TemplateResourceTest.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSender.java, engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java, pom.xml
Based on @pilhuhn's work in #1395. This PR only has one goal: bumping Quarkus.
#1395 is still needed for changes unrelated to the Quarkus bump itself.
=> Bump Quarkus to 2.12.2.Final

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/EmailPayloadAggregatorFactory.java
If forgot this class existed 😄
=> RHIROS-804 Add ROS to EmailPayloadAggregatorFactory

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/ValidationResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/ValidationResourceTest.java
This is part 1.
See also [part 2](https://github.com/RedHatInsights/notifications-gw/pull/258).
=> NOTIF-496 Return 400 when validating invalid b/a/et triplet

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
- We had a query that didn't took into account the active filter Decided to unify both queries into a single one
=> NOTIF-701 Unify endpoints query

admin-console/src/main/webapp/src/Routes.tsx, admin-console/src/main/webapp/src/components/EmailTemplates/EmailTemplateForm.tsx, admin-console/src/main/webapp/src/components/EmailTemplates/EmailTemplateTable.tsx, admin-console/src/main/webapp/src/pages/EmailTemplatePage.tsx, admin-console/src/main/webapp/src/services/EmailTemplates/CreateTemplate.tsx, admin-console/src/main/webapp/src/services/EmailTemplates/GetTemplate.ts, admin-console/src/main/webapp/src/services/EmailTemplates/GetTemplates.tsx, admin-console/src/main/webapp/src/types/Notifications.ts
=> Edit templates in Admin UI

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
We will need migrations to update the name of repeated endpoints
=> NOTIF-370 Prevent from creating integrations with the same name

aggregator/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java
This was already done in `backend` recently.
=> Use fixed postgres major version in tests

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/CamelProperties.java, common/src/main/java/com/redhat/cloud/notifications/models/Endpoint.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java
Was checking the code and found this. Forgot this was still around
=> NOTIF-429 followup - removing properties from CamelProperties

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, database/src/main/resources/db/migration/V1.63.0__NOTIF-803_fix-endpoint-status.sql
Integrations that are under our control are created with `READY` status directly.
=> NOTIF-803 New Integrations are created with correct status

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregator.java, engine/src/main/resources/templates/Inventory/dailyEmailBody.html, engine/src/main/resources/templates/Inventory/validationErrorEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/InventoryTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestInventoryTemplate.java
Christian Marineau requested that the request ID in the emails is removed and display name added in its place.
=> Inventory - changes from request ID to display name

engine/src/main/resources/templates/Drift/dailyEmailBody.html, engine/src/main/resources/templates/Drift/newBaselineDriftInstantEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestDriftTemplate.java
Handle personification in drift email templates
=> [DRFT-906] Handle personification in email templates

database/src/main/resources/db/migration/V1.64.0__NOTIF-820_fix_endpoint_status_again.sql, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java
~Based on #1545.~ (rebased)
⚠️ This PR **MUST NOT** be merged before #1545 has been deployed on prod. ⚠️
=> NOTIF-820 Do not process endpoints that are not READY

engine/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregator.java, engine/src/main/resources/templates/Inventory/dailyEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/InventoryEmailAggregatorTest.java
This change fixes the problem of the aggregator always having only one item and updates related tests.
=> Fixes Inventory EmailAggregator

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml
This PR depends on two app-interface MRs that I will not link here.
I'll undraft it when app-interface is ready.
=> NOTIF-804 Load RHOSE client_id and secret from actual secrets

engine/src/main/java/com/redhat/cloud/notifications/events/FromOpenBridgeHistoryFiller.java
RHOSE relies on the [error handling strategies](https://quarkus.io/guides/kafka#error-handling) provided by Quarkus when a failure happens during the processing of one of our events.
Until now, we retrieved the `dead-letter-cause` field returned by RHOSE in case of error and it was persisted in the DB. Unfortunately, that field was empty most of the time and we were unable to understand why the error happened and how to fix it.
After adding some debug log entries on stage, I found out that RHOSE can also return the cause of the error with the `dead-letter-reason` field. This PR retrieves that field and persists it alongside with `dead-letter-cause`.
=> NOTIF-832 Retrieve and persist dead-letter-reason header from RHOSE

backend/src/main/java/com/redhat/cloud/notifications/routers/internal/RhoseTest.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/RhoseTestHelper.java, backend/src/test/java/com/redhat/cloud/notifications/ProdTestProfile.java, backend/src/test/java/com/redhat/cloud/notifications/routers/internal/RhoseTestHelperTest.java
=> Add a RHOSE development helper class

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/events/FromCamelHistoryFiller.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, pom.xml
=> Bump Quarkus from 2.12.3.Final to 2.13.3.Final

backend/src/main/java/com/redhat/cloud/notifications/RunOnBackendStartup.java
It will help debugging potential issues.
[[RHCLOUD-22065]](https://issues.redhat.com/browse/RHCLOUD-22065)
=> [RHCLOUD-22065] feature: log Sources URL on startup

engine/src/main/java/com/redhat/cloud/notifications/RunOnEngineStartup.java
This isn't needed yet but we need to trigger another deployment on stage 😄
=> Log Sources URL at startup in engine

backend/src/main/java/com/redhat/cloud/notifications/db/Query.java
Fix the log to correctly write the sortColumn
=> Log the sort column

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointReadyChecker.java
Looks like RHOSE is not answering with the deleted type and instead returning a 404.
Check if we were deleting an endpoint and delete it if that's the case.
=> Fix delete endpoint

backend/src/main/java/com/redhat/cloud/notifications/db/Query.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EventResource.java, backend/src/main/java/com/redhat/cloud/notifications/routers/NotificationResource.java, backend/src/test/java/com/redhat/cloud/notifications/db/QueryTest.java
Validates that the "limit", "offset" and "pageNumber" parameters have valid values, and returns a 400 if they don't.
[[RHCLOUD-22361]](https://issues.redhat.com/browse/RHCLOUD-22361)
=> [RHCLOUD-22361] Feature: validate query parameters

engine/src/main/resources/templates/Advisor/dailyEmailBody.html, engine/src/main/resources/templates/Advisor/dailyEmailTitle.txt
This depends on the Java stuff Paul Wayper is working on
For https://issues.redhat.com/browse/ADVISOR-2876 as part of https://issues.redhat.com/browse/ADVISOR-2022
=> Add HTML templates for Advisor daily email

common/src/main/java/com/redhat/cloud/notifications/models/EndpointType.java, database/src/main/resources/db/migration/V1.70.1__RHCLOUD-22943_cleanup.sql
=> RHCLOUD-22943 Migrate from endpoints ordinal to name in DB (step 3)

engine/src/main/resources/templates/Advisor/dailyEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/AdvisorEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java
Add some extra tests of the HTML output as well.
=> Fix width styling of Advisor daily email metrics cards

backend/src/main/java/com/redhat/cloud/notifications/routers/JaxRsExceptionMapper.java, backend/src/main/java/com/redhat/cloud/notifications/routers/JsonParseExceptionMapper.java, camel-sender-demo/pom.xml, pom.xml
I had to make a small change in exception mappers. Everything's explained in the code comments.
=> Bump Quarkus to 2.15.1.Final

engine/src/main/java/com/redhat/cloud/notifications/events/CamelHistoryFillerHelper.java
This PR contains a workaround that will fix the Camel-related actions status on prod immediately. We'll migrate the SQL schema and remove this workaround in a subsequent PR.
=> RHCLOUD-23511 Ensure invocation time does not exceed DB capacity

common/src/main/java/com/redhat/cloud/notifications/routers/sources/SecretUtils.java, pom.xml
`StringUtils` is no longer available on the classpath.
=> Bump insights-notification-schemas-java from 0.17 to 0.18

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Policies.java, engine/src/main/resources/templates/Common/insightsEmailBody.html, engine/src/main/resources/templates/Policies/dailyEmailBodyV2.html, engine/src/main/resources/templates/Policies/dailyEmailTitleV2.txt, engine/src/main/resources/templates/Policies/instantEmailBodyV2.html, engine/src/main/resources/templates/Policies/instantEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/templates/TestPoliciesTemplateV2.java
Update policy templates according new UXD guidelines.
New daily template will look like :
=> RHCLOUD-23514 update policy templates

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Compliance.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/TemplateService.java, engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailBodyV2.html, engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailTitleV2.txt, engine/src/main/resources/templates/Compliance/dailyEmailBodyV2.html, engine/src/main/resources/templates/Compliance/dailyEmailTitleV2.txt, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailBodyV2.html, engine/src/main/resources/templates/Compliance/reportUploadFailedEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestComplianceTemplate.java
=> [RHCLOUD-23628] update compliance templates

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointReadyCheckerTest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeHelper.java, engine/src/main/java/com/redhat/cloud/notifications/events/FromOpenBridgeHistoryFiller.java, engine/src/main/java/com/redhat/cloud/notifications/processors/rhose/RhoseTypeProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/CamelTypeProcessorTest.java
After this PR, `FromOpenBridgeHistoryFiller` will be disabled by default on dev machine but it will keep running every 10 seconds on ephemeral, stage and prod.
=> RHCLOUD-23576 Remove OB feature flags

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, common/src/main/java/com/redhat/cloud/notifications/openbridge/BridgeAuth.java
This should make the migration to V2 of the RHOSE REST API easier.
=> RHCLOUD-23885 Simplify RHOSE processors create/update/delete operations

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProvider.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/rbac/RbacServiceToService.java, engine/src/test/java/com/redhat/cloud/notifications/recipients/rbac/RbacRecipientUsersProviderTest.java
This PR more or less reverts the following PRS:
- https://github.com/RedHatInsights/notifications-backend/pull/1170
- https://github.com/RedHatInsights/notifications-backend/pull/1209
- https://github.com/RedHatInsights/notifications-backend/pull/1000
=> RHCLOUD-23644 Add back RBAC integration to retrieve users

engine/src/main/resources/templates/Rbac/customGroupCreatedEmailBody.html, engine/src/main/resources/templates/Rbac/customGroupDeletedEmailBody.html, engine/src/main/resources/templates/Rbac/customGroupUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/customPlatformGroupUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/customRoleCreatedEmailBody.html, engine/src/main/resources/templates/Rbac/customRoleDeletedEmailBody.html, engine/src/main/resources/templates/Rbac/customRoleUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/nonPlatformRoleUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/platformGroupToCustomEmailBody.html, engine/src/main/resources/templates/Rbac/platformRoleUpdatedEmailBody.html, engine/src/main/resources/templates/Rbac/systemRoleAvailableEmailBody.html
Rbac label have to be updated to Access User on email templates
=> [RHCLOUD-23939] Update Rbac label to User Access on email templates

backend/src/main/java/com/redhat/cloud/notifications/routers/UserConfigResource.java
We had this API hidden from the openapi. Lets make it visible to allow others to update this setting.
=> Include user config API in the openapi file

.rhcicd/clowdapp-engine.yaml, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateFactory.java, engine/src/main/java/com/redhat/cloud/notifications/templates/Patch.java, engine/src/main/resources/templates/Common/insightsEmailBody.html, engine/src/main/resources/templates/Patch/dailyEmailBodyV2.html, engine/src/main/resources/templates/Patch/dailyEmailTitleV2.txt, engine/src/main/resources/templates/Patch/newAdvisoriesInstantEmailBodyV2.html, engine/src/main/resources/templates/Patch/newAdvisoriesInstantEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/PatchTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestPatchTemplate.java
=> [RHCLOUD-23955] update Patch email templates according UXD guidelines

engine/src/test/java/com/redhat/cloud/notifications/templates/TestRbacTemplate.java
Fix unit test on Rbac templatedue to a late modification
=> [RHCLOUD-23884] Fix unit test on Rbac email template update

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Up to now when a processor was not ready to be updated, we still sent the update request, which would result in an unnecessary call to RHOSE and an error report for us. This should spare RHOSE from receiving that request.
I chose to use an `InternalServerErrorException` because all of the web application exceptions are catched, so sending a `BadRequest` would still be wrapped in a `5xx` response to the client.
[[RHCLOUD-22281]](https://issues.redhat.com/browse/RHCLOUD-22281)
=> [RHCLOUD-22281] feature: don't update a processor if it is not ready to be updated

engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepository.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EmailAggregationRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessorTest.java
Limit loaded EmailAggregation elements to prevent heap overflow
=> [RHCLOUD-24419] Limit loaded EmailAggregation

.rhcicd/clowdapp-backend.yaml, .rhcicd/clowdapp-engine.yaml
Use flags in a consistent way by making the restrictive mode the default
=> [RHCLOUD-24563] Set restrictive env config as default value

common/src/main/java/com/redhat/cloud/notifications/routers/sources/SecretUtils.java
These metrics will help us understand if we need caching the incoming secrets for a better performance in Notifications.
[[RHCLOUD-24704]](https://issues.redhat.com/browse/RHCLOUD-24704)
=>  [RHCLOUD-24704] feature: measure the time it takes to call to Sources

engine/src/main/resources/templates/Advisor/dailyEmailBodyV2.html, engine/src/main/resources/templates/Secure/Advisor/dailyEmailBody.html, engine/src/test/java/com/redhat/cloud/notifications/processors/email/aggregators/AdvisorEmailAggregatorTest.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAdvisorTemplate.java
=> [RHCLOUD-24767] Better management of line breaks for advisor template

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
=> [RHCLOUD-25096] add slack metrics to Grafana

common/src/main/java/com/redhat/cloud/notifications/models/NotificationsConsoleCloudEvent.java, engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/request/ActionRecipientSettings.java, pom.xml
- Using ObjectMapper from lib
- Using Notifications generated object instead of custom made
=> Update event-schema to 1.3.0

admin-console/src/main/webapp/package.json, admin-console/src/main/webapp/src/components/EventTypes/CreateEditModal.tsx, admin-console/src/main/webapp/src/generated/OpenapiInternal.ts, admin-console/src/main/webapp/src/pages/ApplicationPage.tsx, admin-console/src/main/webapp/src/services/EventTypes/CreateEventTypes.ts, admin-console/src/main/webapp/src/services/EventTypes/GetEventTypes.ts, admin-console/src/main/webapp/src/types/Notifications.ts, admin-console/src/main/webapp/yarn.lock, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java, common/src/main/java/com/redhat/cloud/notifications/models/EventType.java
=> Allow to update FQN of event types

.rhcicd/build_deploy.sh
Creating a conditional in the build deploy script for the security and compliance branch.
=> Security updates and adding conditional to build deploy

.rhcicd/build_deploy.sh
Adding the build date to the security compliance tag in the build script
=> Adding date to security compliance tag

engine/src/main/java/com/redhat/cloud/notifications/cloudevent/transformers/PolicyTriggeredCloudEventTransformer.java, engine/src/test/java/com/redhat/cloud/notifications/cloudevent/transformers/CloudEventTransformerTest.java, engine/src/test/java/com/redhat/cloud/notifications/cloudevent/transformers/PolicyTriggeredCloudEventTransformerTest.java, engine/src/test/resources/cloudevents/cloudevent.json, engine/src/test/resources/cloudevents/policies-with-null-tag-values.json, engine/src/test/resources/cloudevents/policies.json
- Adds tests for the CloudEventTransformers
=> Fix policies with null tag values

engine/pom.xml, engine/src/main/java/com/redhat/cloud/notifications/exports/ResultsTransformer.java, engine/src/main/java/com/redhat/cloud/notifications/exports/TransformationException.java, engine/src/main/java/com/redhat/cloud/notifications/exports/transformers/event/CSVEventTransformer.java, engine/src/main/java/com/redhat/cloud/notifications/exports/transformers/event/JSONEventTransformer.java, engine/src/test/java/com/redhat/cloud/notifications/exports/transformers/TransformersHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/exports/transformers/event/CSVEventTransformerTest.java, engine/src/test/java/com/redhat/cloud/notifications/exports/transformers/event/JSONEventTransformerTest.java, engine/src/test/resources/resultstransformers/event/expectedResult.csv, engine/src/test/resources/resultstransformers/event/expectedResult.json
The transformers will take care of transforming the data in the precise
way we want it to be exported.
=> [RHCLOUD-25597] Export service integration — Entity transformations

engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java
The notification history update fails in stage because the history record hasn't been created yet when the engine receives the return message. The reason behind that is pretty simple: we're calling Camel with a blocking call (REST) and that call includes the response that is sent through Kafka. The history is created after the Kafka response has been sent and processed, so it can't be updated.
This PR moves the history record creation before the call to Camel and guarantees that the return message will update the history.
=> RHCLOUD-26020 Persist the notification history before calling Camel

engine/src/main/java/com/redhat/cloud/notifications/processors/eventing/EventingProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/processors/eventing/EventingTypeProcessorTest.java
These headers are not used on the consumer side of the Kafka topic.
=> RHCLOUD-26040 Remove Kafka headers from EventingProcessor

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java
I want to make sure we didn't miss a poison pill that would block the beginning of the Kafka messages processing from the `ingress` channel.
=> Check Kafka poison pills

engine/src/main/java/com/redhat/cloud/notifications/events/EventConsumer.java, engine/src/test/java/com/redhat/cloud/notifications/events/EventConsumerTest.java
This PR will most likely be reverted.
=> Test a different EventConsumer method signature

.rhcicd/clowdapp-engine.yaml
This will help debug issues in stage.
=> RHCLOUD-25597 | feature: allow enabling the debug log for the export service

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/RunOnEngineStartup.java
See https://quarkus.io/guides/rest-client-reactive#logging-traffic
=> RHCLOUD-26500 Investigate the cause of 404 while uploading exports

common/src/test/java/com/redhat/cloud/notifications/MicrometerAssertionHelper.java, engine/src/main/java/com/redhat/cloud/notifications/exports/ExportEventListener.java, engine/src/test/java/com/redhat/cloud/notifications/exports/ExportEventListenerMockServerTest.java, engine/src/test/java/com/redhat/cloud/notifications/exports/ExportEventListenerTest.java
This will allow us to understand which errors we are suffering from in this particular integration.
=> RHCLOUD-25597 | feature: use different metrics for the failures

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
These Grafana dashboards will help us identify whether the service is working as expected or if, on the other hand, we should investigate and take action because of a misbehavior.
=> RHCLOUD-25597 | feature: Grafana dashboards for the exports service integration

connector-common/src/main/java/com/redhat/cloud/notifications/connector/CloudEventDataExtractor.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/EngineToConnectorRouteBuilder.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/IncomingCloudEventProcessor.java, connector-common/src/main/java/com/redhat/cloud/notifications/connector/OutgoingCloudEventBuilder.java, connector-common/src/test/java/com/redhat/cloud/notifications/connector/ConnectorRoutesTest.java, connector-google-chat/src/main/java/com/redhat/cloud/notifications/connector/google/chat/GoogleChatRouteBuilder.java, connector-google-chat/src/test/java/com/redhat/cloud/notifications/connector/google/chat/GoogleChatConnectorRoutesTest.java, connector-microsoft-teams/src/main/java/com/redhat/cloud/notifications/connector/microsoft/teams/TeamsExceptionProcessor.java, connector-microsoft-teams/src/main/java/com/redhat/cloud/notifications/connector/microsoft/teams/TeamsRouteBuilder.java, connector-microsoft-teams/src/test/java/com/redhat/cloud/notifications/connector/microsoft/teams/TeamsConnectorRoutesTest.java, connector-slack/src/test/java/com/redhat/cloud/notifications/connector/slack/SlackConnectorRoutesTest.java
This PR contains preparation work for the `notifications-connector-splunk` implementation.
=> RHCLOUD-26616 Prepare Splunk connector implementation

.rhcicd/clowdapp-connector-servicenow.yaml, connector-common/src/main/java/com/redhat/cloud/notifications/connector/ConnectorConfig.java, connector-servicenow/src/main/java/com/redhat/cloud/notifications/connector/servicenow/ServiceNowConnectorConfig.java, connector-servicenow/src/main/java/com/redhat/cloud/notifications/connector/servicenow/ServiceNowRouteBuilder.java, connector-servicenow/src/main/resources/application.properties
Same as #2092 but for ServiceNow.
=> Configure ServiceNow HTTPS timeouts programmatically

.github/workflows/platsec-connector-email.yml, .rhcicd/build_deploy.sh, .rhcicd/pr_check.sh, docker/Dockerfile.notifications-connector-email.jvm
These files are required to be able to build, deploy and test the email connector.
[[RHCLOUD-28089]](https://issues.redhat.com/browse/RHCLOUD-28089)
=>  RHCLOUD-28089 | feature: build, deploy and test files for the email connector

backend/src/main/java/com/redhat/cloud/notifications/oapi/OApiFilter.java
- Adds the approved description for integrations and notifications
=> Change the openapi description depending on what is being requested

docker/Dockerfile.notifications-aggregator.jvm, docker/Dockerfile.notifications-backend.jvm, docker/Dockerfile.notifications-connector-email.jvm, docker/Dockerfile.notifications-connector-google-chat.jvm, docker/Dockerfile.notifications-connector-microsoft-teams.jvm, docker/Dockerfile.notifications-connector-servicenow.jvm, docker/Dockerfile.notifications-connector-slack.jvm, docker/Dockerfile.notifications-connector-splunk.jvm, docker/Dockerfile.notifications-connector-webhook.jvm, docker/Dockerfile.notifications-engine.jvm
Some packages updates may be available and not yet included into the base image when we're building our own images.
=> Add microdnf update to Dockerfiles

engine/src/main/java/com/redhat/cloud/notifications/events/ConnectorReceiver.java, engine/src/main/java/com/redhat/cloud/notifications/events/EndpointErrorFromConnectorHelper.java, engine/src/test/java/com/redhat/cloud/notifications/events/ConnectorReceiverTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/EndpointErrorFromConnectorHelperTest.java
if original endpoint has been deleted
=> [RHCLOUD-28513] avoid npe on connector returns 

.rhcicd/clowdapp-engine.yaml
=> Remove old param from engine ClowdApp template

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
I think I can make these dashboards look better.
[[RHCLOUD-28097]](https://issues.redhat.com/browse/RHCLOUD-28097)
=> RHCLOUD-28097 | Grafana dashboards bis

engine/src/main/java/com/redhat/cloud/notifications/processors/webhooks/WebhookTypeProcessor.java
=> Stop logging payloads sent to BOP

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/Environment.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderTest.java, pom.xml
```
./mvnw io.quarkus.platform:quarkus-maven-plugin:3.4.1:update -N -Dstream=3.4
```
=> Bump Quarkus to 3.4.1

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
The async aggregation logic is unstable as showed by the tests on `master`. I'm reverting the process to sync until this issue is resolved.
@g-duval Next time, I'll use a feature flag 😅
=> Revert async aggregation

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
The previous code doesn't work well in stage, so I'm trying something slightly different.
=> Run AsyncAggregation with a different context

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/OCMServiceLogs/severityCriticalInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityCriticalInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCMServiceLogs/severityDebugInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityDebugInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCMServiceLogs/severityErrorInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityErrorInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCMServiceLogs/severityFatalInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityFatalInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCMServiceLogs/severityInfoInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityInfoInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCMServiceLogs/severityMajorInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityMajorInstantEmailTitleV2.txt, engine/src/main/resources/templates/OCMServiceLogs/severityWarningInstantEmailBodyV2.html, engine/src/main/resources/templates/OCMServiceLogs/severityWarningInstantEmailTitleV2.txt
These templates will be used to perform a first end-to-end test.
=> RHCLOUD-28935 Create dummy templates for OCM Service Logs

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/bop/BOPRequestPreparer.java
=> RHCLOUD-29101 Debug: log the recipients

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailCloudEventDataExtractor.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/constants/ExchangeProperty.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsResolverPreparer.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/pojo/RecipientsQuery.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailCloudEventDataExtractorTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderRHCLOUD28631SingleEmailPerUserTest.java, connector-email/src/test/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilderRHCLOUD28631Test.java, engine/src/main/java/com/redhat/cloud/notifications/processors/SystemEndpointTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/connector/dto/EmailNotification.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/recipientsresolver/pojo/RecipientsQuery.java, engine/src/test/java/com/redhat/cloud/notifications/processors/email/EmailProcessorTest.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolver.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/rest/RecipientsResolverResource.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/rest/pojo/RecipientsQuery.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolverTest.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/rest/RecipientResolverResourceTest.java
This is the last part of the "event types subscribed by default" implementation.
=> RHCLOUD-29084 Support event types subscribed by default in connectors

admin-console/src/main/webapp/src/components/EventTypes/CreateEditModal.tsx, admin-console/src/main/webapp/src/components/EventTypes/EventTypeTable.tsx, admin-console/src/main/webapp/src/generated/OpenapiInternal.ts, admin-console/src/main/webapp/src/pages/ApplicationPage.tsx, admin-console/src/main/webapp/src/pages/BundlePage/BehaviorGroupTable.tsx, admin-console/src/main/webapp/src/services/Applications/CreateApplication.ts, admin-console/src/main/webapp/src/services/EventTypes/CreateEventTypes.ts, admin-console/src/main/webapp/src/services/EventTypes/GetEventTypes.ts, admin-console/src/main/webapp/src/types/Notifications.ts
=> Adding subscribed by default on the admin UI

.rhcicd/clowdapp-backend.yaml
Based on https://github.com/RedHatInsights/clowder/pull/869.
=> Support multiple API paths

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/OCM/genericInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/genericInstantEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/OcmTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOcmTemplate.java
Add OCM generic template for lifecycle, configuration and subscription events
=> [RHCLOUD-28935] Add OCM generic template

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/ApplicationRepository.java
Hide not visible event types on event types configuration screens
=> [RHCLOUD-29473] Hide not visible event types on event types

connector-email/pom.xml, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailRouteBuilder.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/constants/Routes.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsQuery.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/processors/recipients/RecipientsResolverRequestPreparer.java
Here's some additional cleanup after the big PR.
=> Remove dependencies and route from the email connector

backend/src/main/resources/application.properties, pom.xml
This reverts commit 5a1fb7326b2d8cdb418adb49a2ad11e5fa847cc0.
=> Revert "Bump to quarkus 3.5.3 (#2409)"

aggregator/src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java, engine/src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java
This PR only affects `aggregator` and `engine`.
| Kafka security protocol | Before | After |
| - | - | - |
| SSL | Truststore from Clowder config not supported 🔴 | Truststore from Clowder config supported 🟢 |
| SASL_SSL | Truststore from Clowder config not supported if `kafka.sasl.mechanism == "PLAIN"` 🔴 | Truststore from Clowder config supported regardless of the `kafka.sasl.mechanism` value 🟢 |
ℹ️ The two files modified in this PR are strictly identical.
=> RHCLOUD-30042 Better support of Kafka truststore from Clowder

engine/src/main/resources/templates/Common/insightsEmailBody.html, engine/src/main/resources/templates/Secure/Common/insightsEmailBody.html
=> Fix common email template footer

engine/src/main/resources/templates/Common/insightsEmailBody.html, engine/src/main/resources/templates/Common/insightsEmailBodyLight.html
* Fix daily digest anchors
* Fix extra spacing on titles, introduced by <p> tag
=> [RHCLOUD-31282] Fix extra spacing on sections title and anchors

.rhcicd/clowdapp-engine.yaml, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/DrawerNotificationRepository.java, backend/src/test/java/com/redhat/cloud/notifications/routers/DrawerResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java, common/src/main/java/com/redhat/cloud/notifications/models/DrawerEntryPayload.java, common/src/main/java/com/redhat/cloud/notifications/models/DrawerNotification.java, common/src/main/java/com/redhat/cloud/notifications/models/DrawerNotificationId.java, connector-drawer/src/main/java/com/redhat/cloud/notifications/connector/drawer/DrawerPayloadBuilder.java, connector-drawer/src/main/java/com/redhat/cloud/notifications/connector/drawer/DrawerRouteBuilder.java, connector-drawer/src/main/java/com/redhat/cloud/notifications/connector/drawer/model/DrawerEntry.java, connector-drawer/src/main/java/com/redhat/cloud/notifications/connector/drawer/model/DrawerEntryPayload.java, connector-drawer/src/main/java/com/redhat/cloud/notifications/connector/drawer/model/DrawerUser.java, connector-drawer/src/main/java/com/redhat/cloud/notifications/connector/drawer/recipients/RecipientsResolverResponseProcessor.java, connector-drawer/src/test/java/com/redhat/cloud/notifications/connector/drawer/DrawerConnectorRoutesTest.java, database/src/main/resources/db/migration/V1.95.0__update_drawer_notification_insert_function.sql, engine/src/main/java/com/redhat/cloud/notifications/EngineConfig.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/DrawerNotificationRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/ConnectorReceiver.java, engine/src/main/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessor.java, engine/src/main/resources/application.properties, engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java, engine/src/test/java/com/redhat/cloud/notifications/db/repositories/DrawerNotificationRepositoryTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessorTest.java
1.  Remove old drawer integration engine
2. Change drawer notification data model from one UUID per record to composit id based on event id + userid
=> [RHCLOUD-30730] Update drawer integration

.rhcicd/clowdapp-engine.yaml, engine/src/main/java/com/redhat/cloud/notifications/log/LogConfig.java, engine/src/main/java/com/redhat/cloud/notifications/log/LogLevelManager.java
This is experimental. To be implemented in all apps later.
=> RHCLOUD-26188 Change engine logs level from Unleash

engine/src/main/resources/templates/OCM/clusterUpdateInstantEmailBodyV2.html, engine/src/main/resources/templates/OCM/genericInstantEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/OcmTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOcmTemplate.java
=> [RHCLOUD-30965] Add doc_references parameter on OCM templates

.rhcicd/floorist/floorplan.yaml
Query for the email subscriptions grouped by org ID.
=> RHCLOUD-22071 | feature(query): email susbscriptions by org ID

docker/Dockerfile-backend
Same Dockerfile than before with a tiny change: `./mvnw` is replaced with `../mvnw`.
=> RHCLOUD-30193 Test Docker build from Konflux

admin-console/pom.xml, aggregator/pom.xml, backend/pom.xml, common-aggregator/pom.xml, common-unleash/pom.xml, common/pom.xml, connector-common-authentication/pom.xml, connector-common-http/pom.xml, connector-common/pom.xml, connector-drawer/pom.xml, connector-email/pom.xml, connector-google-chat/pom.xml, connector-microsoft-teams/pom.xml, connector-servicenow/pom.xml, connector-slack/pom.xml, connector-splunk/pom.xml, connector-webhook/pom.xml, database/pom.xml, engine/pom.xml, recipients-resolver/pom.xml
This looks required by Konflux.
=> RHCLOUD-30193 Add relativePath to all modules POMs

backend/src/main/java/com/redhat/cloud/notifications/routers/engine/ReplayService.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/InternalResource.java, engine/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/routers/ReplayResource.java, engine/src/test/java/com/redhat/cloud/notifications/routers/ReplayResourceTest.java
This PR is meant to fix an incident. It will be reverted later.
=> Replay skipped notifications

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Adding option to be able to view perf dashboard in grafana
=> adding option for perf grafana

connector-common-http/src/main/java/com/redhat/cloud/notifications/connector/http/HttpConnectorConfig.java
This should have been included in #2567.
=> Do NOT disable faulty endpoints by default

.rhcicd/floorist/floorplan.yaml
Lists the used event types per organization.
[[RHCLOUD-27274]](https://issues.redhat.com/browse/RHCLOUD-27274)
=> RHCLOUD-27274 | feature(query): used event types per organization

engine/src/main/resources/templates/OCM/clusterUpdateInstantEmailBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/templates/TestOcmTemplate.java
=> [RHCLOUD-31862] Implement OCM ROSA HCP email template

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Until now, when the endpoint creation failed due to an internal error,
which wasn't very common, that endpoint's secrets were left in Sources
and were not cleaned up.
This happened because our endpoint creation resource handler was
annotated with the "@transactional" method, and there was no exception
handling that would catch any errors and would try to delete the
"non-saved" endpoint's secrets from Sources.
Therefore, firstly the secrets would be created, and then we would
attempt to save the endpoint in the database. So if any exception was
thrown in the process, those secrets would remain undeleted in Sources.
The introduced changes take care of this problem by making the "endpoint
creation" function call an internal endpoint creation function instead,
which gets wrapped in a …
=> feature: clean up Sources secrets when endpoint creation fails

.rhcicd/floorist/floorplan.yaml
The stakeholders have requested us to add the event type to the query.
RHCLOUD-27274
=> RHCLOUD-27274 | feature: add the event type to the query

aggregator/pom.xml, backend/pom.xml, connector-common/pom.xml, connector-webhook/src/main/java/com/redhat/cloud/notifications/connector/webhook/WebhookRouteBuilder.java, engine/pom.xml, pom.xml
Check migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.10
=> [RHCLOUD-32475] Bump Quarkus to 3.10.x

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Reverts RedHatInsights/notifications-backend#2735, since I broke Grafana in stage.
=> Revert "RHCLOUD-32981 | feature: graphs for the Sources integration"

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Adds a couple of graphs for the Sources integration:
- Maximum time spent fetching secrets grouped by service.
- Number of fetched secrets by service.
[[RHCLOUD-32981]](https://issues.redhat.com/browse/RHCLOUD-32981)
=> RHCLOUD-32981 | feature: graphs for the Sources integration

engine/src/main/resources/templates/AnsibleServiceOnAws/notifyCustomerProvisionSuccessEmailBodyV2.html, engine/src/main/resources/templates/AnsibleServiceOnAws/notifyCustomerProvisionSuccessEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/TestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestAnsibleServiceOnAwsTemplate.java
This PR adds the Ansible as a service email template.
=> Add SaaS email notification

engine/src/main/java/com/redhat/cloud/notifications/templates/EmailTemplateMigrationService.java, engine/src/main/resources/templates/Errata/bugfixEmailBodyV2.html, engine/src/main/resources/templates/Errata/bugfixEmailTitleV2.txt, engine/src/main/resources/templates/Errata/enhancementEmailBodyV2.html, engine/src/main/resources/templates/Errata/enhancementEmailTitleV2.txt, engine/src/main/resources/templates/Errata/securityEmailBodyV2.html, engine/src/main/resources/templates/Errata/securityEmailTitleV2.txt, engine/src/test/java/com/redhat/cloud/notifications/ErrataTestHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/templates/TestErrataTemplate.java
3 similar email templates has been added like:
=> [RHCLOUD-33898] Initiate teamnado email templates

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Includes a couple of nice graphs for the CPU and memory usage.
[[RHCLOUD-34047]](https://issues.redhat.com/browse/RHCLOUD-34047]
=> RHCLOUD-34047 | feature: graphs for the production database's health

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
With the incoming integration with TeamNado it will be critical to be able to check how the database is doing at a glance.
[[RHCLOUD-34008]](https://issues.redhat.com/browse/RHCLOUD-34008)
=> RHCLOUD-34008 | feature: production database's health graphs

backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrlValidator.java, common/src/test/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrlValidatorTest.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, pom.xml
This reverts commit e29e01e321275e8d2341136eb94759381996fc30.
=> Revert "[RHCLOUD-34067] Bump Quarkus to 3.12.3 (#2859)"

backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java, common/src/main/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrlValidator.java, common/src/test/java/com/redhat/cloud/notifications/models/validation/ValidNonPrivateUrlValidatorTest.java, connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/config/EmailConnectorConfig.java, pom.xml
Reverts RedHatInsights/notifications-backend#2863
=> Revert "Revert "[RHCLOUD-34067] Bump Quarkus to 3.12.3 (#2859)""

.rhcicd/stage-google-chat-post-deployment-tests.yaml, .rhcicd/stage-microsoft-teams-post-deployment-tests.yaml
Onboard a few more connectors into post-deploy testing
=> Rhcloud 28271/connector tests

.rhcicd/clowdapp-connector-google-chat.yaml, .rhcicd/clowdapp-connector-microsoft-teams.yaml
Add missing testing filed in clowdapps:
- Google-chat
- Microsoft-teams
=> RHCLOUD 28271: Clowdapp testing config

engine/src/main/resources/templates/AnsibleServiceOnAws/notifyCustomerProvisionSuccessEmailBodyV2.html
Jira Issue: https://issues.redhat.com/browse/AAP-29288
Add link to environment detail page instead list of instance.
=> add link to specific instance instead full list

connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyCloudEventDataExtractorTest.java
The build is broken in `master`. This PR will fix it.
=> Bump connector-pagerduty to Quarkus 3.14

engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java
This created lots of errors (harmless ones) recently in prod.
=> Add missing param in log entry

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
These graphs will help us identify at a simple glance if we are having issues fetching users.
[[RHCLOUD-34830]](https://issues.redhat.com/browse/RHCLOUD-34830)
=> RHCLOUD-34830 | feature: graphs for the recipients resolver

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
Convert max spent time into average spent time to be more representative
=> [RHCLOUD-35170] Update grafana dashboard:

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
https://issues.redhat.com/browse/RHCLOUD-33772
Add Grafana panels and data for the PagerDuty connector.
=> [RHCLOUD-33772] Add connector-pagerduty in stage for Grafana

backend/src/main/java/com/redhat/cloud/notifications/RunOnBackendStartup.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointEventTypeRepository.java, engine/src/main/java/com/redhat/cloud/notifications/config/EngineConfig.java, engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, engine/src/main/java/com/redhat/cloud/notifications/events/EndpointProcessor.java, engine/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, engine/src/test/java/com/redhat/cloud/notifications/events/EndpointProcessorTest.java, engine/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, engine/src/test/java/com/redhat/cloud/notifications/routers/ReplayResourceTest.java
Also add data migration from old data model to the new one.
=> [RHCLOUD-34489] Be able to use endpoint to event type direct link in engine.

backend/pom.xml, backend/src/main/java/com/redhat/cloud/notifications/oapi/OApiFilter.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/resources/application.properties, backend/src/test/java/com/redhat/cloud/notifications/openapi/OpenApiTest.java, pom.xml
This PR is about searching rest operations schemas dependencies, and keeping only those.
=> [RHCLOUD-35655] Cleanup integration openApi

backend/src/test/java/com/redhat/cloud/notifications/routers/EventResourceTest.java
Implements the tests to test making authenticated and authorized
requests while using Kessel as the authentication and authorization
back end.
- https://github.com/RedHatInsights/notifications-backend/pull/3030
[[RHCLOUD-33780]](https://issues.redhat.com/browse/RHCLOUD-33780)
=> RHCLOUD-33780 | feature: Kessel tests for the "EventResource"

backend/src/test/java/com/redhat/cloud/notifications/routers/OrgConfigResourceTest.java
Implements the tests to test making authenticated and authorized
requests while using Kessel as the authentication and authorization
back end.
- https://github.com/RedHatInsights/notifications-backend/pull/3030
[[RHCLOUD-33780]](https://issues.redhat.com/browse/RHCLOUD-33780)
=> RHCLOUD-33780 | feature: Kessel tests for the "OrgConfigResource"

engine/src/test/java/com/redhat/cloud/notifications/db/repositories/EndpointRepositoryTest.java
https://issues.redhat.com/browse/RHCLOUD-35800
This issue adds test cases to persist endpoints and properties for each [EndpointType](https://github.com/RedHatInsights/notifications-backend/blob/f701efe8f6d7dbd778238a1a2fa372d285cd8d26/common/src/main/java/com/redhat/cloud/notifications/models/EndpointType.java), and then attempt to retrieve them. This tests the method [`EndpointRepository.loadProperties(List<Endpoint>)`](https://github.com/RedHatInsights/notifications-backend/blob/d589d7668407f37579de3eab2167dba624e8d3f1/engine/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java#L336-L348), which caused some issues while testing the PagerDuty integration (see #3051)
Renamed an existing test case and refactored into a separate method. No impacts detected …
=> [RHCLOUD-35800] Add tests for retrieving EndpointProperties implementations from database

connector-email/src/main/java/com/redhat/cloud/notifications/connector/email/EmailCloudEventDataExtractor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/ExternalAuthorizationCriterion.java, engine/src/main/java/com/redhat/cloud/notifications/processors/ExternalAuthorizationCriterionExtractor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/drawer/DrawerNotificationToConnector.java, engine/src/main/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailAggregator.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailProcessor.java, engine/src/main/java/com/redhat/cloud/notifications/processors/email/connector/dto/EmailNotification.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/recipientsresolver/ExternalRecipientsResolver.java, engine/src/main/java/com/redhat/cloud/notifications/recipients/recipientsresolver/pojo/RecipientsQuery.java, engine/src/test/java/com/redhat/cloud/notifications/processors/ExternalAuthorizationCriteriaExtractorTest.java, engine/src/test/java/com/redhat/cloud/notifications/processors/drawer/DrawerProcessorTest.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/model/ExternalAuthorizationCriterion.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/FetchUsersFromExternalServices.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolver.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/resolver/kessel/KesselService.java, recipients-resolver/src/main/java/com/redhat/cloud/notifications/recipients/rest/pojo/RecipientsQuery.java, recipients-resolver/src/test/java/com/redhat/cloud/notifications/recipients/resolver/RecipientsResolverTest.java
Name and structure updates from ADR-53 reviews
=> Update kessel criterion for email integration

connector-common/src/main/resources/application.properties, engine/src/main/resources/application.properties
See https://github.com/quarkusio/quarkus/discussions/45032
=> Add config workaround to fix build failures related to redpanda

backend/src/main/java/com/redhat/cloud/notifications/db/repositories/SubscriptionRepository.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/TemplateRepository.java, backend/src/test/java/com/redhat/cloud/notifications/CrudTestHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/db/ResourceHelpers.java, backend/src/test/java/com/redhat/cloud/notifications/events/LifecycleITest.java, backend/src/test/java/com/redhat/cloud/notifications/routers/UserConfigResourceTest.java, database/src/main/resources/db/migration/V1.109.0__RHCLOUD-36892_delete_inconsistent_daily_subscriptions.sql
This PR adds consistency checks on email and drawer subscriptions.
It forbid user subscription it the linked event type don't have a template for the selected subscription type.
=> [RHCLOUD-36892] Forbid inconsistent user subscriptions

backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/test/java/com/redhat/cloud/notifications/routers/EndpointResourceTest.java
Before this patch, if reporting the integration deletion to the Kessel Inventory failed, the secrets were deleted from Sources but the integration deletion would be rolled back in the database, which left it in an invalid state unable to fetch the associated secrets from Sources.
With this patch:
- If deleting the integration from the database goes wrong, the transaction gets rolled back and nothing gets changed.
- If deleting the integration from Kessel goes wrong, the transaction is rolled back and the above point applies.
- If deleting the integration's secrets' from Sources goes wrong, the first point still applies and we make sure that the integration gets recreated in Inventory.
This should give us enough resiliency to avoid invalid states with integrations in Notifications and the …
=> RHCLOUD-35158 | feature: improve resilience when deleting the secrets from Sources

aggregator/src/main/java/com/redhat/cloud/notifications/db/EmailAggregationRepository.java, aggregator/src/test/java/com/redhat/cloud/notifications/DailyEventAggregationJobTest.java, aggregator/src/test/java/com/redhat/cloud/notifications/db/EmailAggregationRepositoryTest.java, aggregator/src/test/java/com/redhat/cloud/notifications/helpers/ResourceHelpers.java
[RHCLOUD-37252] Update new aggregation logic to be closer to legacy aggregation, to be able to compare result during migration phase
=> [RHCLOUD-37252] Update new aggregation logic

backend/src/main/java/com/redhat/cloud/notifications/db/Query.java, backend/src/main/java/com/redhat/cloud/notifications/db/builder/Parameters.java, backend/src/main/java/com/redhat/cloud/notifications/db/builder/QueryBuilder.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/EndpointResource.java, backend/src/main/resources/application.properties, common/src/main/java/com/redhat/cloud/notifications/models/CompositeEndpointType.java
In order to identify the strange behavior when fetching the endpoints in the stage environmen, we need to see what we are issuing to the database, with which parameters and what is being returned.
[[RHCLOUD-37430]](https://issues.redhat.com/browse/RHCLOUD-37430)
=> RHCLOUD-37430 | feature: log statements when fetching integrations for debugging purposes

.rhcicd/grafana/grafana-dashboard-notifications-general.configmap.yaml
https://issues.redhat.com/browse/RHCLOUD-37376
Followup to #3251, removing the space left by removal of the "Kafka Lag (seconds)" panel
=> [RHCLOUD-37376] Rearrange Grafana panels

engine/src/main/java/com/redhat/cloud/notifications/config/KafkaChannelManager.java
This reverts commit 99ccdedcd275962acb1854e4626b0982dffda9b1.
=> Revert "Use Subscriber API in KafkaChannelManager (#3277)"

database/src/main/resources/db/migration/V1.113.0__RHCLOUD-37954_delete_orphan_email_endpoints.sql
Sql script to delete orphan email endpoints (EMAIL_SUBSCRIPTION).
=> [RHCLOUD-37954] Delete orphan email endpoints

engine/src/main/resources/templates/Integrations/generalCommunicationBodyV2.html, engine/src/test/java/com/redhat/cloud/notifications/templates/IntegrationsTemplatesTest.java
The PM validated the email and suggested one change to make. Other than that, we are good to send the communication in production.
[[RHCLOUD-37937]](https://issues.redhat.com/browse/RHCLOUD-37937)
=> RHCLOUD-37937 | refactor: wording

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselAuthorization.java, backend/src/main/java/com/redhat/cloud/notifications/db/repositories/EndpointRepository.java, backend/src/main/java/com/redhat/cloud/notifications/routers/internal/kessel/KesselAssetsMigrationService.java
this feature has been designed as a one shot test service, that's why no tests were implemented.
=> [RHCLOUD-38590] Add a Kessel integrations consistency check service

backend/src/main/java/com/redhat/cloud/notifications/config/BackendConfig.java
Reverts RedHatInsights/notifications-backend#3372
=> Revert "Force Konflux to rebuild"

common-template/src/main/resources/templates/google_chat/Errata/newSubscriptionBugfixErrata.json, common-template/src/main/resources/templates/google_chat/Errata/newSubscriptionEnhancementErrata.json, common-template/src/main/resources/templates/google_chat/Errata/newSubscriptionSecurityErrata.json, common-template/src/main/resources/templates/ms_teams/Errata/newSubscriptionBugfixErrata.json, common-template/src/main/resources/templates/ms_teams/Errata/newSubscriptionEnhancementErrata.json, common-template/src/main/resources/templates/ms_teams/Errata/newSubscriptionSecurityErrata.json, common-template/src/main/resources/templates/slack/Errata/newSubscriptionBugfixErrata.md, common-template/src/main/resources/templates/slack/Errata/newSubscriptionEnhancementErrata.md, common-template/src/main/resources/templates/slack/Errata/newSubscriptionSecurityErrata.md, common-template/src/test/java/google_chat/TestErrataNotificationsTemplate.java, common-template/src/test/java/ms_teams/TestErrataNotificationsTemplate.java, common-template/src/test/java/slack/TestErrataNotificationsTemplate.java
https://issues.redhat.com/browse/RHCLOUD-38890
Forgot to add query params to the errata templates in #3394
=> [RHCLOUD-38890] Add query params to errata templates

backend/src/main/java/com/redhat/cloud/notifications/auth/kessel/KesselInventoryAuthorization.java
Add debug logs on Kessel inventory listNotificationsIntegrations requests
Add a warn log if listNotificationsIntegrations is longer than 300ms
=> Add debug logs on Kessel inventory listNotificationsIntegrations requests

common-template/pom.xml, common-template/src/main/java/com/redhat/cloud/notifications/qute/templates/mapping/OpenShift.java, common-template/src/main/resources/templates/ms_teams/Common/adaptive-card-schema.json, common-template/src/main/resources/templates/ms_teams/Common/incoming-webhook-schema.json, common-template/src/main/resources/templates/ms_teams/OCM/ocmDefault.json, common-template/src/test/java/ms_teams/AdaptiveCardValidatorHelper.java, common-template/src/test/java/ms_teams/TestDefaultTemplate.java, common-template/src/test/java/ms_teams/TestErrataNotificationsTemplate.java, common-template/src/test/java/ms_teams/TestOcmTemplate.java, engine/src/test/java/com/redhat/cloud/notifications/processors/camel/teams/TeamsProcessorTest.java
Validates ms teams templates using schema validation specified on [Microsoft teams documentation](https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1%2Cdotnet#microsoft-teams-webhook)
=> [RHCLOUD-40023] Improve Ms teams adaptive cards tests

.rhcicd/clowdapp-engine.yaml
This reverts commit c6d4fba2032032ec92a65ceeee18cdf84e7131c3.
=> Revert "Enable autoscaler via engine ClowdApp (#2798)"

.rhcicd/clowdapp-engine.yaml
Reverts RedHatInsights/notifications-backend#3486
=> Revert "Revert "Enable autoscaler via engine ClowdApp (#2798)""
